/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module APU(\ADDR[0] , \ADDR[1] , \ADDR[2] , \ADDR[3] , \ADDR[4] , clk, reset, ce, \DIN[0] , \DIN[1] , \DIN[2] , \DIN[3] , \DIN[4] , \DIN[5] , \DIN[6] , \DIN[7] , \DOUT[0] , \DOUT[1] , \DOUT[2] , \DOUT[3] , \DOUT[4] 
, \DOUT[5] , \DOUT[6] , \DOUT[7] , MW, MR, \audio_channels[0] , \audio_channels[1] , \audio_channels[2] , \audio_channels[3] , \audio_channels[4] , \Sample[0] , \Sample[1] , \Sample[2] , \Sample[3] , \Sample[4] , \Sample[5] , \Sample[6] , \Sample[7] , \Sample[8] , \Sample[9] , \Sample[10] 
, \Sample[11] , \Sample[12] , \Sample[13] , \Sample[14] , \Sample[15] , DmaReq, DmaAck, \DmaAddr[0] , \DmaAddr[1] , \DmaAddr[2] , \DmaAddr[3] , \DmaAddr[4] , \DmaAddr[5] , \DmaAddr[6] , \DmaAddr[7] , \DmaAddr[8] , \DmaAddr[9] , \DmaAddr[10] , \DmaAddr[11] , \DmaAddr[12] , \DmaAddr[13] 
, \DmaAddr[14] , \DmaAddr[15] , \DmaData[0] , \DmaData[1] , \DmaData[2] , \DmaData[3] , \DmaData[4] , \DmaData[5] , \DmaData[6] , \DmaData[7] , odd_or_even, IRQ);
  input \ADDR[0] ;
  wire \ADDR[0] ;
  input \ADDR[1] ;
  wire \ADDR[1] ;
  input \ADDR[2] ;
  wire \ADDR[2] ;
  input \ADDR[3] ;
  wire \ADDR[3] ;
  input \ADDR[4] ;
  wire \ADDR[4] ;
  input clk;
  wire clk;
  input reset;
  wire reset;
  input ce;
  wire ce;
  input \DIN[0] ;
  wire \DIN[0] ;
  input \DIN[1] ;
  wire \DIN[1] ;
  input \DIN[2] ;
  wire \DIN[2] ;
  input \DIN[3] ;
  wire \DIN[3] ;
  input \DIN[4] ;
  wire \DIN[4] ;
  input \DIN[5] ;
  wire \DIN[5] ;
  input \DIN[6] ;
  wire \DIN[6] ;
  input \DIN[7] ;
  wire \DIN[7] ;
  output \DOUT[0] ;
  wire \DOUT[0] ;
  output \DOUT[1] ;
  wire \DOUT[1] ;
  output \DOUT[2] ;
  wire \DOUT[2] ;
  output \DOUT[3] ;
  wire \DOUT[3] ;
  output \DOUT[4] ;
  wire \DOUT[4] ;
  output \DOUT[5] ;
  wire \DOUT[5] ;
  output \DOUT[6] ;
  wire \DOUT[6] ;
  output \DOUT[7] ;
  wire \DOUT[7] ;
  input MW;
  wire MW;
  input MR;
  wire MR;
  input \audio_channels[0] ;
  wire \audio_channels[0] ;
  input \audio_channels[1] ;
  wire \audio_channels[1] ;
  input \audio_channels[2] ;
  wire \audio_channels[2] ;
  input \audio_channels[3] ;
  wire \audio_channels[3] ;
  input \audio_channels[4] ;
  wire \audio_channels[4] ;
  output \Sample[0] ;
  wire \Sample[0] ;
  output \Sample[1] ;
  wire \Sample[1] ;
  output \Sample[2] ;
  wire \Sample[2] ;
  output \Sample[3] ;
  wire \Sample[3] ;
  output \Sample[4] ;
  wire \Sample[4] ;
  output \Sample[5] ;
  wire \Sample[5] ;
  output \Sample[6] ;
  wire \Sample[6] ;
  output \Sample[7] ;
  wire \Sample[7] ;
  output \Sample[8] ;
  wire \Sample[8] ;
  output \Sample[9] ;
  wire \Sample[9] ;
  output \Sample[10] ;
  wire \Sample[10] ;
  output \Sample[11] ;
  wire \Sample[11] ;
  output \Sample[12] ;
  wire \Sample[12] ;
  output \Sample[13] ;
  wire \Sample[13] ;
  output \Sample[14] ;
  wire \Sample[14] ;
  output \Sample[15] ;
  wire \Sample[15] ;
  output DmaReq;
  wire DmaReq;
  input DmaAck;
  wire DmaAck;
  output \DmaAddr[0] ;
  wire \DmaAddr[0] ;
  output \DmaAddr[1] ;
  wire \DmaAddr[1] ;
  output \DmaAddr[2] ;
  wire \DmaAddr[2] ;
  output \DmaAddr[3] ;
  wire \DmaAddr[3] ;
  output \DmaAddr[4] ;
  wire \DmaAddr[4] ;
  output \DmaAddr[5] ;
  wire \DmaAddr[5] ;
  output \DmaAddr[6] ;
  wire \DmaAddr[6] ;
  output \DmaAddr[7] ;
  wire \DmaAddr[7] ;
  output \DmaAddr[8] ;
  wire \DmaAddr[8] ;
  output \DmaAddr[9] ;
  wire \DmaAddr[9] ;
  output \DmaAddr[10] ;
  wire \DmaAddr[10] ;
  output \DmaAddr[11] ;
  wire \DmaAddr[11] ;
  output \DmaAddr[12] ;
  wire \DmaAddr[12] ;
  output \DmaAddr[13] ;
  wire \DmaAddr[13] ;
  output \DmaAddr[14] ;
  wire \DmaAddr[14] ;
  output \DmaAddr[15] ;
  wire \DmaAddr[15] ;
  input \DmaData[0] ;
  wire \DmaData[0] ;
  input \DmaData[1] ;
  wire \DmaData[1] ;
  input \DmaData[2] ;
  wire \DmaData[2] ;
  input \DmaData[3] ;
  wire \DmaData[3] ;
  input \DmaData[4] ;
  wire \DmaData[4] ;
  input \DmaData[5] ;
  wire \DmaData[5] ;
  input \DmaData[6] ;
  wire \DmaData[6] ;
  input \DmaData[7] ;
  wire \DmaData[7] ;
  output odd_or_even;
  wire odd_or_even;
  output IRQ;
  wire IRQ;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire ClkL;
  wire Cycles_0_;
  wire Cycles_10_;
  wire Cycles_11_;
  wire Cycles_12_;
  wire Cycles_13_;
  wire Cycles_14_;
  wire Cycles_15_;
  wire Cycles_1_;
  wire Cycles_2_;
  wire Cycles_3_;
  wire Cycles_4_;
  wire Cycles_5_;
  wire Cycles_6_;
  wire Cycles_7_;
  wire Cycles_8_;
  wire Cycles_9_;
  wire DisableFrameInterrupt;
  wire \Dmc.ActivationDelay_0_ ;
  wire \Dmc.ActivationDelay_1_ ;
  wire \Dmc.BitsUsed_0_ ;
  wire \Dmc.BitsUsed_1_ ;
  wire \Dmc.BitsUsed_2_ ;
  wire \Dmc.BytesLeft_0_ ;
  wire \Dmc.BytesLeft_10_ ;
  wire \Dmc.BytesLeft_11_ ;
  wire \Dmc.BytesLeft_1_ ;
  wire \Dmc.BytesLeft_2_ ;
  wire \Dmc.BytesLeft_3_ ;
  wire \Dmc.BytesLeft_4_ ;
  wire \Dmc.BytesLeft_5_ ;
  wire \Dmc.BytesLeft_6_ ;
  wire \Dmc.BytesLeft_7_ ;
  wire \Dmc.BytesLeft_8_ ;
  wire \Dmc.BytesLeft_9_ ;
  wire \Dmc.Cycles_0_ ;
  wire \Dmc.Cycles_1_ ;
  wire \Dmc.Cycles_2_ ;
  wire \Dmc.Cycles_3_ ;
  wire \Dmc.Cycles_4_ ;
  wire \Dmc.Cycles_5_ ;
  wire \Dmc.Cycles_6_ ;
  wire \Dmc.Cycles_7_ ;
  wire \Dmc.Cycles_8_ ;
  wire \Dmc.HasSampleBuffer ;
  wire \Dmc.IrqEnable ;
  wire \Dmc.Loop ;
  wire \Dmc.SampleAddress_0_ ;
  wire \Dmc.SampleAddress_1_ ;
  wire \Dmc.SampleAddress_2_ ;
  wire \Dmc.SampleAddress_3_ ;
  wire \Dmc.SampleAddress_4_ ;
  wire \Dmc.SampleAddress_5_ ;
  wire \Dmc.SampleAddress_6_ ;
  wire \Dmc.SampleAddress_7_ ;
  wire \Dmc.SampleLen_0_ ;
  wire \Dmc.SampleLen_1_ ;
  wire \Dmc.SampleLen_2_ ;
  wire \Dmc.SampleLen_3_ ;
  wire \Dmc.SampleLen_4_ ;
  wire \Dmc.SampleLen_5_ ;
  wire \Dmc.SampleLen_6_ ;
  wire \Dmc.SampleLen_7_ ;
  wire FrameInterrupt;
  wire FrameSeqMode;
  wire IrqCtr_0_;
  wire IrqCtr_1_;
  wire \Noi.Enabled ;
  wire \Noi.EnvLoop ;
  wire \Noi.LenCtr_0_ ;
  wire \Noi.LenCtr_1_ ;
  wire \Noi.LenCtr_2_ ;
  wire \Noi.LenCtr_3_ ;
  wire \Noi.LenCtr_4_ ;
  wire \Noi.LenCtr_5_ ;
  wire \Noi.LenCtr_6_ ;
  wire \Noi.LenCtr_7_ ;
  wire \Sq1.Enabled ;
  wire \Sq1.EnvLoop ;
  wire \Sq1.LenCtr_0_ ;
  wire \Sq1.LenCtr_1_ ;
  wire \Sq1.LenCtr_2_ ;
  wire \Sq1.LenCtr_3_ ;
  wire \Sq1.LenCtr_4_ ;
  wire \Sq1.LenCtr_5_ ;
  wire \Sq1.LenCtr_6_ ;
  wire \Sq1.LenCtr_7_ ;
  wire \Sq2.Enabled ;
  wire \Sq2.EnvLoop ;
  wire \Sq2.LenCtr_0_ ;
  wire \Sq2.LenCtr_1_ ;
  wire \Sq2.LenCtr_2_ ;
  wire \Sq2.LenCtr_3_ ;
  wire \Sq2.LenCtr_4_ ;
  wire \Sq2.LenCtr_5_ ;
  wire \Sq2.LenCtr_6_ ;
  wire \Sq2.LenCtr_7_ ;
  wire \Tri.Enabled ;
  wire \Tri.LenCtrHalt ;
  wire \Tri.LenCtr_0_ ;
  wire \Tri.LenCtr_1_ ;
  wire \Tri.LenCtr_2_ ;
  wire \Tri.LenCtr_3_ ;
  wire \Tri.LenCtr_4_ ;
  wire \Tri.LenCtr_5_ ;
  wire \Tri.LenCtr_6_ ;
  wire \Tri.LenCtr_7_ ;
  wire Wrote4017;
  NAND2BX0P5H7R _0668_ (
    .AN(Cycles_4_),
    .B(Cycles_12_),
    .Y(_0126_)
  );
  NAND3BX0P5H7R _0669_ (
    .AN(Cycles_13_),
    .B(Cycles_5_),
    .C(Cycles_8_),
    .Y(_0127_)
  );
  NOR2X0P5H7R _0670_ (
    .A(_0126_),
    .B(_0127_),
    .Y(_0128_)
  );
  NOR2BX1P4H7L _0671_ (
    .AN(Cycles_0_),
    .B(Cycles_3_),
    .Z(_0129_)
  );
  NOR2X0P5H7R _0672_ (
    .A(Cycles_2_),
    .B(Cycles_14_),
    .Y(_0130_)
  );
  NOR2X1P4H7L _0673_ (
    .A(Cycles_9_),
    .B(Cycles_6_),
    .Y(_0131_)
  );
  NAND2BX0P5H7R _0674_ (
    .AN(Cycles_1_),
    .B(Cycles_7_),
    .Y(_0132_)
  );
  NOR2BX1H7R _0675_ (
    .AN(_0131_),
    .B(_0132_),
    .Z(_0133_)
  );
  NOR3BX0P5H7R _0676_ (
    .AN(Cycles_15_),
    .B(Cycles_11_),
    .C(Cycles_10_),
    .Y(_0134_)
  );
  AND4X0P5H7R _0677_ (
    .A(_0129_),
    .B(_0130_),
    .C(_0133_),
    .D(_0134_),
    .Y(_0135_)
  );
  NAND4BBX0P5H7R _0678_ (
    .AN(Cycles_15_),
    .BN(Cycles_11_),
    .C(Cycles_10_),
    .D(Cycles_14_),
    .Y(_0136_)
  );
  NOR2BX1H7R _0679_ (
    .AN(_0129_),
    .B(_0136_),
    .Z(_0137_)
  );
  NOR2BX1P4H7L _0680_ (
    .AN(Cycles_12_),
    .B(Cycles_4_),
    .Z(_0138_)
  );
  NOR3BX0P5H7R _0681_ (
    .AN(Cycles_13_),
    .B(Cycles_5_),
    .C(Cycles_8_),
    .Y(_0139_)
  );
  AND2X1H7R _0682_ (
    .A(_0138_),
    .B(_0139_),
    .Y(_0140_)
  );
  NOR2BX1P4H7L _0683_ (
    .AN(Cycles_2_),
    .B(FrameSeqMode),
    .Z(_0141_)
  );
  AND4X1P4H7L _0684_ (
    .A(_0137_),
    .B(_0133_),
    .C(_0140_),
    .D(_0141_),
    .Y(_0142_)
  );
  AND2X0P5H7L _0685_ (
    .A(Cycles_9_),
    .B(Cycles_6_),
    .Y(_0143_)
  );
  NOR3BX0P5H7R _0686_ (
    .AN(Cycles_1_),
    .B(Cycles_2_),
    .C(Cycles_7_),
    .Y(_0144_)
  );
  NAND4X0P5H7L _0687_ (
    .A(_0128_),
    .B(_0137_),
    .C(_0143_),
    .D(_0144_),
    .Y(_0145_)
  );
  AOAI211X1P4H7L _0688_ (
    .A0(_0128_),
    .A1(_0135_),
    .B0(_0142_),
    .C0(_0145_),
    .Y(_0146_)
  );
  NOR2BX1P4H7L _0689_ (
    .AN(Cycles_11_),
    .B(Cycles_15_),
    .Z(_0147_)
  );
  NOR2X0P5H7R _0690_ (
    .A(Cycles_7_),
    .B(Cycles_1_),
    .Y(_0148_)
  );
  AND4X0P5H7R _0691_ (
    .A(_0129_),
    .B(_0130_),
    .C(_0147_),
    .D(_0148_),
    .Y(_0149_)
  );
  INVX0P5H7R _0692_ (
    .A(Cycles_10_),
    .Y(_0150_)
  );
  AND4X0P5H7R _0693_ (
    .A(_0150_),
    .B(_0138_),
    .C(_0143_),
    .D(_0139_),
    .Y(_0151_)
  );
  NAND2X0P5H7R _0694_ (
    .A(_0149_),
    .B(_0151_),
    .Y(_0152_)
  );
  NOR3X0P7H7L _0695_ (
    .A(_0150_),
    .B(_0126_),
    .C(_0127_),
    .Y(_0153_)
  );
  AND3X1P4H7R _0696_ (
    .A(_0131_),
    .B(_0153_),
    .C(_0149_),
    .Y(_0154_)
  );
  AOI21X0P5H7R _0697_ (
    .A0(_0146_),
    .A1(_0152_),
    .B0(_0154_),
    .Y(_0155_)
  );
  INVX0P7H7L _0698_ (
    .A(\DIN[7] ),
    .Y(_0156_)
  );
  NAND2X0P7H7L _0699_ (
    .A(\ADDR[4] ),
    .B(MW),
    .Y(_0157_)
  );
  NAND2X0P5H7R _0700_ (
    .A(\ADDR[0] ),
    .B(\ADDR[1] ),
    .Y(_0158_)
  );
  NAND2BX0P5H7R _0701_ (
    .AN(odd_or_even),
    .B(\ADDR[2] ),
    .Y(_0159_)
  );
  OR4X1P4H7L _0702_ (
    .A(\ADDR[3] ),
    .B(_0157_),
    .C(_0158_),
    .D(_0159_),
    .Y(_0160_)
  );
  INVX0P7H7L _0703_ (
    .A(ce),
    .Y(_0161_)
  );
  BUFX1P4H7L _0704_ (
    .A(_0161_),
    .Y(_0162_)
  );
  AOI21X0P5H7R _0705_ (
    .A0(Wrote4017),
    .A1(FrameSeqMode),
    .B0(_0162_),
    .Y(_0163_)
  );
  OAI21X0P5H7R _0706_ (
    .A0(_0156_),
    .A1(_0160_),
    .B0(_0163_),
    .Y(_0164_)
  );
  INVX0P5H7R _0707_ (
    .A(reset),
    .Y(_0165_)
  );
  BUFX0P5H7R _0708_ (
    .A(_0165_),
    .Y(_0166_)
  );
  OA221X0P5H7R _0709_ (
    .A0(ce),
    .A1(ClkL),
    .B0(_0155_),
    .B1(_0164_),
    .C0(_0166_),
    .Y(_0000_)
  );
  AOA211X1H7L _0710_ (
    .A0(_0131_),
    .A1(_0153_),
    .B0(_0151_),
    .C0(_0149_),
    .Y(_0167_)
  );
  INVX0P5H7R _0711_ (
    .A(Wrote4017),
    .Y(_0168_)
  );
  OAI211X1P4H7L _0712_ (
    .A0(_0146_),
    .A1(_0167_),
    .B0(_0168_),
    .C0(_0160_),
    .Y(_0169_)
  );
  NAND2BX0P5H7R _0713_ (
    .AN(Cycles_0_),
    .B(ce),
    .Y(_0170_)
  );
  NAND2X0P5H7R _0714_ (
    .A(_0162_),
    .B(Cycles_0_),
    .Y(_0171_)
  );
  OAOI211X0P5H7R _0715_ (
    .A0(_0169_),
    .A1(_0170_),
    .B0(_0171_),
    .C0(reset),
    .Y(_0001_)
  );
  OAI21X0P5H7R _0716_ (
    .A0(_0161_),
    .A1(_0168_),
    .B0(_0165_),
    .Y(_0172_)
  );
  AOI2BB1X0P5H7R _0717_ (
    .A0N(_0161_),
    .A1N(_0160_),
    .B0(_0172_),
    .Y(_0173_)
  );
  AOI211X0P5H7R _0718_ (
    .A0(_0131_),
    .A1(_0153_),
    .B0(_0151_),
    .C0(_0161_),
    .Y(_0174_)
  );
  AOI21X0P5H7R _0719_ (
    .A0(_0160_),
    .A1(_0149_),
    .B0(_0161_),
    .Y(_0175_)
  );
  NOR3X1P4H7L _0720_ (
    .A(_0172_),
    .B(_0174_),
    .C(_0175_),
    .Y(_0176_)
  );
  AOI21X1P4H7L _0721_ (
    .A0(_0146_),
    .A1(_0173_),
    .B0(_0176_),
    .Y(_0177_)
  );
  BUFX1H7L _0722_ (
    .A(_0177_),
    .Y(_0178_)
  );
  AND4X1P4H7L _0723_ (
    .A(ce),
    .B(Cycles_2_),
    .C(Cycles_1_),
    .D(Cycles_0_),
    .Y(_0179_)
  );
  AND2X1P4H7L _0724_ (
    .A(Cycles_6_),
    .B(Cycles_5_),
    .Y(_0180_)
  );
  AND3X1P4H7L _0725_ (
    .A(Cycles_7_),
    .B(Cycles_4_),
    .C(Cycles_3_),
    .Y(_0181_)
  );
  AND4X1P4H7L _0726_ (
    .A(Cycles_8_),
    .B(_0179_),
    .C(_0180_),
    .D(_0181_),
    .Y(_0182_)
  );
  AND2X1H7L _0727_ (
    .A(Cycles_9_),
    .B(_0182_),
    .Y(_0183_)
  );
  XNOR2X0P5H7R _0728_ (
    .A(Cycles_10_),
    .B(_0183_),
    .Y(_0184_)
  );
  NOR2X0P5H7R _0729_ (
    .A(_0178_),
    .B(_0184_),
    .Y(_0002_)
  );
  NAND2X0P5H7R _0730_ (
    .A(Cycles_10_),
    .B(_0183_),
    .Y(_0185_)
  );
  XOR2X0P5H7R _0731_ (
    .A(Cycles_11_),
    .B(_0185_),
    .Y(_0186_)
  );
  NOR2X0P5H7R _0732_ (
    .A(_0178_),
    .B(_0186_),
    .Y(_0003_)
  );
  AND4X1P4H7L _0733_ (
    .A(Cycles_9_),
    .B(Cycles_11_),
    .C(Cycles_10_),
    .D(_0182_),
    .Y(_0187_)
  );
  XNOR2X0P5H7R _0734_ (
    .A(Cycles_12_),
    .B(_0187_),
    .Y(_0188_)
  );
  NOR2X0P5H7R _0735_ (
    .A(_0178_),
    .B(_0188_),
    .Y(_0004_)
  );
  NAND3BX0P5H7R _0736_ (
    .AN(Cycles_13_),
    .B(Cycles_12_),
    .C(_0187_),
    .Y(_0189_)
  );
  OAI2BB1X0P5H7R _0737_ (
    .A0N(Cycles_12_),
    .A1N(_0187_),
    .B0(Cycles_13_),
    .Y(_0190_)
  );
  AOI21X0P5H7R _0738_ (
    .A0(_0189_),
    .A1(_0190_),
    .B0(_0177_),
    .Y(_0005_)
  );
  NAND3X0P5H7R _0739_ (
    .A(Cycles_13_),
    .B(Cycles_12_),
    .C(_0187_),
    .Y(_0191_)
  );
  XOR2X1H7L _0740_ (
    .A(Cycles_14_),
    .B(_0191_),
    .Y(_0192_)
  );
  NOR2X0P5H7R _0741_ (
    .A(_0178_),
    .B(_0192_),
    .Y(_0006_)
  );
  NAND4X0P5H7R _0742_ (
    .A(Cycles_14_),
    .B(Cycles_13_),
    .C(Cycles_12_),
    .D(_0187_),
    .Y(_0193_)
  );
  XOR2X1H7L _0743_ (
    .A(Cycles_15_),
    .B(_0193_),
    .Y(_0194_)
  );
  NOR2X0P7H7L _0744_ (
    .A(_0178_),
    .B(_0194_),
    .Y(_0007_)
  );
  NAND2X0P5H7R _0745_ (
    .A(ce),
    .B(Cycles_0_),
    .Y(_0195_)
  );
  XOR2X0P5H7R _0746_ (
    .A(Cycles_1_),
    .B(_0195_),
    .Y(_0196_)
  );
  NOR2X0P5H7R _0747_ (
    .A(_0178_),
    .B(_0196_),
    .Y(_0008_)
  );
  OAI2BB1X0P5H7R _0748_ (
    .A0N(Cycles_1_),
    .A1N(Cycles_0_),
    .B0(Cycles_2_),
    .Y(_0197_)
  );
  NAND4BX0P5H7R _0749_ (
    .AN(Cycles_2_),
    .B(Cycles_1_),
    .C(Cycles_0_),
    .D(ce),
    .Y(_0198_)
  );
  AOI21X0P5H7R _0750_ (
    .A0(_0162_),
    .A1(Cycles_2_),
    .B0(reset),
    .Y(_0199_)
  );
  AOAI211X0P5H7R _0751_ (
    .A0(_0197_),
    .A1(_0198_),
    .B0(_0169_),
    .C0(_0199_),
    .Y(_0009_)
  );
  XNOR2X0P5H7R _0752_ (
    .A(Cycles_3_),
    .B(_0179_),
    .Y(_0200_)
  );
  NOR2X0P5H7R _0753_ (
    .A(_0178_),
    .B(_0200_),
    .Y(_0010_)
  );
  NAND2X0P5H7R _0754_ (
    .A(Cycles_3_),
    .B(_0179_),
    .Y(_0201_)
  );
  XOR2X0P5H7R _0755_ (
    .A(Cycles_4_),
    .B(_0201_),
    .Y(_0202_)
  );
  NOR2X0P5H7R _0756_ (
    .A(_0178_),
    .B(_0202_),
    .Y(_0011_)
  );
  AND3X1P4H7L _0757_ (
    .A(Cycles_4_),
    .B(Cycles_3_),
    .C(_0179_),
    .Y(_0203_)
  );
  XNOR2X0P5H7R _0758_ (
    .A(Cycles_5_),
    .B(_0203_),
    .Y(_0204_)
  );
  NOR2X0P5H7R _0759_ (
    .A(_0178_),
    .B(_0204_),
    .Y(_0012_)
  );
  NAND2X0P5H7R _0760_ (
    .A(Cycles_5_),
    .B(_0203_),
    .Y(_0205_)
  );
  XOR2X0P5H7R _0761_ (
    .A(Cycles_6_),
    .B(_0205_),
    .Y(_0206_)
  );
  NOR2X0P5H7R _0762_ (
    .A(_0178_),
    .B(_0206_),
    .Y(_0013_)
  );
  NAND2X0P5H7R _0763_ (
    .A(_0168_),
    .B(_0160_),
    .Y(_0207_)
  );
  NAND2X0P5H7R _0764_ (
    .A(ce),
    .B(_0152_),
    .Y(_0208_)
  );
  NAND2X0P5H7R _0765_ (
    .A(_0180_),
    .B(_0203_),
    .Y(_0209_)
  );
  XNOR2X0P5H7R _0766_ (
    .A(Cycles_7_),
    .B(_0209_),
    .Y(_0210_)
  );
  OAI211X1P4H7L _0767_ (
    .A0(_0146_),
    .A1(_0208_),
    .B0(_0210_),
    .C0(_0165_),
    .Y(_0211_)
  );
  OAOI211X0P5H7R _0768_ (
    .A0(_0154_),
    .A1(_0207_),
    .B0(ce),
    .C0(_0211_),
    .Y(_0014_)
  );
  AND3X0P5H7R _0769_ (
    .A(_0179_),
    .B(_0180_),
    .C(_0181_),
    .Y(_0212_)
  );
  XNOR2X0P5H7R _0770_ (
    .A(Cycles_8_),
    .B(_0212_),
    .Y(_0213_)
  );
  NOR2X0P5H7R _0771_ (
    .A(_0177_),
    .B(_0213_),
    .Y(_0015_)
  );
  XNOR2X0P5H7R _0772_ (
    .A(Cycles_9_),
    .B(_0182_),
    .Y(_0214_)
  );
  NOR2X0P5H7R _0773_ (
    .A(_0177_),
    .B(_0214_),
    .Y(_0016_)
  );
  NOR2X0P5H7R _0774_ (
    .A(_0161_),
    .B(_0157_),
    .Y(_0215_)
  );
  NOR2X0P5H7R _0775_ (
    .A(\ADDR[3] ),
    .B(_0158_),
    .Y(_0216_)
  );
  NAND3X0P5H7R _0776_ (
    .A(\ADDR[2] ),
    .B(_0215_),
    .C(_0216_),
    .Y(_0217_)
  );
  NOR2BX1H7L _0777_ (
    .AN(\DIN[6] ),
    .B(_0217_),
    .Z(_0218_)
  );
  BUFX1P4H7L _0778_ (
    .A(_0165_),
    .Y(_0219_)
  );
  AOA211X0P7H7L _0779_ (
    .A0(DisableFrameInterrupt),
    .A1(_0217_),
    .B0(_0218_),
    .C0(_0219_),
    .Y(_0017_)
  );
  NAND3BX2H7L _0780_ (
    .AN(\ADDR[1] ),
    .B(\ADDR[2] ),
    .C(\ADDR[0] ),
    .Y(_0220_)
  );
  NOR2X1P4H7L _0781_ (
    .A(_0157_),
    .B(_0220_),
    .Y(_0221_)
  );
  INVX1P4H7L _0782_ (
    .A(\DIN[4] ),
    .Y(_0222_)
  );
  NOR2X0P5H7R _0783_ (
    .A(_0222_),
    .B(\DOUT[4] ),
    .Y(_0223_)
  );
  AOAI211X1P4H7L _0784_ (
    .A0(_0221_),
    .A1(_0223_),
    .B0(DmaAck),
    .C0(ce),
    .Y(_0224_)
  );
  BUFX1P4H7L _0785_ (
    .A(_0224_),
    .Y(_0225_)
  );
  OR2X1P4H7L _0786_ (
    .A(\Dmc.BytesLeft_9_ ),
    .B(\Dmc.BytesLeft_8_ ),
    .Y(_0226_)
  );
  OR4X1P4H7L _0787_ (
    .A(\Dmc.BytesLeft_7_ ),
    .B(\Dmc.BytesLeft_11_ ),
    .C(\Dmc.BytesLeft_10_ ),
    .D(_0226_),
    .Y(_0227_)
  );
  OR4X3H7L _0788_ (
    .A(\Dmc.BytesLeft_3_ ),
    .B(\Dmc.BytesLeft_2_ ),
    .C(\Dmc.BytesLeft_1_ ),
    .D(\Dmc.BytesLeft_0_ ),
    .Y(_0228_)
  );
  OR4X3H7L _0789_ (
    .A(\Dmc.BytesLeft_6_ ),
    .B(\Dmc.BytesLeft_5_ ),
    .C(\Dmc.BytesLeft_4_ ),
    .D(_0228_),
    .Y(_0229_)
  );
  OAI21X3H7L _0790_ (
    .A0(_0227_),
    .A1(_0229_),
    .B0(DmaAck),
    .Y(_0230_)
  );
  BUFX3H7L _0791_ (
    .A(_0230_),
    .Y(_0231_)
  );
  NOR3X0P5H7R _0792_ (
    .A(\DmaAddr[0] ),
    .B(_0231_),
    .C(_0225_),
    .Y(_0232_)
  );
  AOA211X0P5H7L _0793_ (
    .A0(\DmaAddr[0] ),
    .A1(_0225_),
    .B0(_0232_),
    .C0(_0219_),
    .Y(_0018_)
  );
  BUFX1P4H7L _0794_ (
    .A(_0230_),
    .Y(_0233_)
  );
  BUFX3P5H7L _0795_ (
    .A(_0230_),
    .Y(_0234_)
  );
  AND4X1P4H7L _0796_ (
    .A(\DmaAddr[3] ),
    .B(\DmaAddr[2] ),
    .C(\DmaAddr[1] ),
    .D(\DmaAddr[0] ),
    .Y(_0235_)
  );
  AND4X1P4H7L _0797_ (
    .A(\DmaAddr[6] ),
    .B(\DmaAddr[5] ),
    .C(\DmaAddr[4] ),
    .D(_0235_),
    .Y(_0236_)
  );
  NAND4X0P5H7R _0798_ (
    .A(\DmaAddr[9] ),
    .B(\DmaAddr[8] ),
    .C(\DmaAddr[7] ),
    .D(_0236_),
    .Y(_0237_)
  );
  NOR3X0P5H7R _0799_ (
    .A(\DmaAddr[10] ),
    .B(_0234_),
    .C(_0237_),
    .Y(_0238_)
  );
  AOA211X1P4H7L _0800_ (
    .A0(_0221_),
    .A1(_0223_),
    .B0(DmaAck),
    .C0(ce),
    .Y(_0239_)
  );
  BUFX1P4H7L _0801_ (
    .A(_0239_),
    .Y(_0240_)
  );
  AOAI211X1P4H7L _0802_ (
    .A0(\Dmc.SampleAddress_4_ ),
    .A1(_0233_),
    .B0(_0238_),
    .C0(_0240_),
    .Y(_0241_)
  );
  INVX0P5H7R _0803_ (
    .A(DmaAck),
    .Y(_0242_)
  );
  AOI2BB1X1P4H7L _0804_ (
    .A0N(_0227_),
    .A1N(_0229_),
    .B0(_0242_),
    .Y(_0243_)
  );
  BUFX1H7L _0805_ (
    .A(_0224_),
    .Y(_0244_)
  );
  AOAI211X0P5H7R _0806_ (
    .A0(_0243_),
    .A1(_0237_),
    .B0(_0244_),
    .C0(\DmaAddr[10] ),
    .Y(_0245_)
  );
  AOI21X0P5H7R _0807_ (
    .A0(_0241_),
    .A1(_0245_),
    .B0(reset),
    .Y(_0019_)
  );
  NAND2X0P5H7L _0808_ (
    .A(\DmaAddr[7] ),
    .B(_0236_),
    .Y(_0246_)
  );
  NAND4X0P5H7R _0809_ (
    .A(\DmaAddr[9] ),
    .B(\DmaAddr[8] ),
    .C(\DmaAddr[11] ),
    .D(\DmaAddr[10] ),
    .Y(_0247_)
  );
  OR2X0P5H7R _0810_ (
    .A(_0246_),
    .B(_0247_),
    .Y(_0248_)
  );
  NAND2BX0P5H7R _0811_ (
    .AN(\Dmc.SampleAddress_5_ ),
    .B(_0231_),
    .Y(_0249_)
  );
  OAI21X1P4H7L _0812_ (
    .A0(_0233_),
    .A1(_0248_),
    .B0(_0249_),
    .Y(_0250_)
  );
  BUFX1P4H7L _0813_ (
    .A(_0239_),
    .Y(_0251_)
  );
  INVX0P5H7R _0814_ (
    .A(\DmaAddr[10] ),
    .Y(_0252_)
  );
  OAI21X0P5H7R _0815_ (
    .A0(_0252_),
    .A1(_0237_),
    .B0(_0243_),
    .Y(_0253_)
  );
  AOI21X0P5H7R _0816_ (
    .A0(_0251_),
    .A1(_0253_),
    .B0(\DmaAddr[11] ),
    .Y(_0254_)
  );
  AOI211X1P4H7L _0817_ (
    .A0(_0240_),
    .A1(_0250_),
    .B0(_0254_),
    .C0(reset),
    .Y(_0020_)
  );
  BUFX1H7L _0818_ (
    .A(_0224_),
    .Y(_0255_)
  );
  NAND2X1P4H7L _0819_ (
    .A(\Dmc.SampleAddress_6_ ),
    .B(_0234_),
    .Y(_0256_)
  );
  OA31X1P4H7L _0820_ (
    .A0(\DmaAddr[12] ),
    .A1(_0230_),
    .A2(_0248_),
    .B0(_0256_),
    .Y(_0257_)
  );
  BUFX1P4H7L _0821_ (
    .A(_0243_),
    .Y(_0258_)
  );
  AOAI211X1P4H7L _0822_ (
    .A0(_0258_),
    .A1(_0248_),
    .B0(_0255_),
    .C0(\DmaAddr[12] ),
    .Y(_0259_)
  );
  OAOI211X1H7L _0823_ (
    .A0(_0255_),
    .A1(_0257_),
    .B0(_0259_),
    .C0(reset),
    .Y(_0021_)
  );
  AND4X0P5H7R _0824_ (
    .A(\DmaAddr[9] ),
    .B(\DmaAddr[12] ),
    .C(\DmaAddr[11] ),
    .D(\DmaAddr[10] ),
    .Y(_0260_)
  );
  NAND4X1P4H7L _0825_ (
    .A(\DmaAddr[8] ),
    .B(\DmaAddr[7] ),
    .C(_0236_),
    .D(_0260_),
    .Y(_0261_)
  );
  NOR3X0P5H7R _0826_ (
    .A(\DmaAddr[13] ),
    .B(_0234_),
    .C(_0261_),
    .Y(_0262_)
  );
  AOAI211X1P4H7L _0827_ (
    .A0(\Dmc.SampleAddress_7_ ),
    .A1(_0233_),
    .B0(_0262_),
    .C0(_0240_),
    .Y(_0263_)
  );
  AOAI211X0P5H7R _0828_ (
    .A0(_0243_),
    .A1(_0261_),
    .B0(_0244_),
    .C0(\DmaAddr[13] ),
    .Y(_0264_)
  );
  AOI21X0P5H7R _0829_ (
    .A0(_0263_),
    .A1(_0264_),
    .B0(reset),
    .Y(_0022_)
  );
  NAND2X1P4H7L _0830_ (
    .A(\DmaAddr[14] ),
    .B(_0251_),
    .Y(_0265_)
  );
  NOR2BX1H7R _0831_ (
    .AN(\DmaAddr[13] ),
    .B(_0261_),
    .Z(_0266_)
  );
  MUX2X1H7L _0832_ (
    .A(\DmaAddr[14] ),
    .B(_0265_),
    .S0(_0266_),
    .Y(_0267_)
  );
  OA221X0P5H7L _0833_ (
    .A0(\DmaAddr[14] ),
    .A1(_0251_),
    .B0(_0267_),
    .B1(_0233_),
    .C0(_0166_),
    .Y(_0023_)
  );
  NOR2BX1H7R _0834_ (
    .AN(\DmaAddr[0] ),
    .B(\DmaAddr[1] ),
    .Z(_0268_)
  );
  NOR2BX1H7R _0835_ (
    .AN(\DmaAddr[1] ),
    .B(\DmaAddr[0] ),
    .Z(_0269_)
  );
  AOAI211X1P4H7L _0836_ (
    .A0(_0251_),
    .A1(_0268_),
    .B0(_0269_),
    .C0(_0258_),
    .Y(_0270_)
  );
  NAND2X0P5H7R _0837_ (
    .A(\DmaAddr[1] ),
    .B(_0255_),
    .Y(_0271_)
  );
  AOI21X0P5H7R _0838_ (
    .A0(_0270_),
    .A1(_0271_),
    .B0(reset),
    .Y(_0024_)
  );
  NAND2X0P5H7R _0839_ (
    .A(\DmaAddr[1] ),
    .B(\DmaAddr[0] ),
    .Y(_0272_)
  );
  NOR3X0P5H7R _0840_ (
    .A(\DmaAddr[2] ),
    .B(_0225_),
    .C(_0272_),
    .Y(_0273_)
  );
  AOAI211X1P4H7L _0841_ (
    .A0(\DmaAddr[2] ),
    .A1(_0272_),
    .B0(_0273_),
    .C0(_0258_),
    .Y(_0274_)
  );
  NAND2X0P5H7R _0842_ (
    .A(\DmaAddr[2] ),
    .B(_0255_),
    .Y(_0275_)
  );
  AOI21X0P5H7R _0843_ (
    .A0(_0274_),
    .A1(_0275_),
    .B0(reset),
    .Y(_0025_)
  );
  NAND3X0P5H7R _0844_ (
    .A(\DmaAddr[2] ),
    .B(\DmaAddr[1] ),
    .C(\DmaAddr[0] ),
    .Y(_0276_)
  );
  NOR3X0P5H7R _0845_ (
    .A(\DmaAddr[3] ),
    .B(_0224_),
    .C(_0276_),
    .Y(_0277_)
  );
  AOAI211X0P5H7R _0846_ (
    .A0(\DmaAddr[3] ),
    .A1(_0276_),
    .B0(_0277_),
    .C0(_0258_),
    .Y(_0278_)
  );
  NAND2X0P5H7R _0847_ (
    .A(\DmaAddr[3] ),
    .B(_0255_),
    .Y(_0279_)
  );
  AOI21X0P5H7R _0848_ (
    .A0(_0278_),
    .A1(_0279_),
    .B0(reset),
    .Y(_0026_)
  );
  NAND4X0P5H7R _0849_ (
    .A(\DmaAddr[3] ),
    .B(\DmaAddr[2] ),
    .C(\DmaAddr[1] ),
    .D(\DmaAddr[0] ),
    .Y(_0280_)
  );
  NOR3X0P5H7R _0850_ (
    .A(\DmaAddr[4] ),
    .B(_0224_),
    .C(_0280_),
    .Y(_0281_)
  );
  AOAI211X0P5H7R _0851_ (
    .A0(\DmaAddr[4] ),
    .A1(_0280_),
    .B0(_0281_),
    .C0(_0258_),
    .Y(_0282_)
  );
  NAND2X0P5H7R _0852_ (
    .A(\DmaAddr[4] ),
    .B(_0255_),
    .Y(_0283_)
  );
  AOI21X0P5H7R _0853_ (
    .A0(_0282_),
    .A1(_0283_),
    .B0(reset),
    .Y(_0027_)
  );
  NAND2X0P5H7R _0854_ (
    .A(\DmaAddr[4] ),
    .B(_0235_),
    .Y(_0284_)
  );
  NOR3X0P5H7R _0855_ (
    .A(\DmaAddr[5] ),
    .B(_0224_),
    .C(_0284_),
    .Y(_0285_)
  );
  AOAI211X0P5H7R _0856_ (
    .A0(\DmaAddr[5] ),
    .A1(_0284_),
    .B0(_0285_),
    .C0(_0258_),
    .Y(_0286_)
  );
  NAND2X0P5H7R _0857_ (
    .A(\DmaAddr[5] ),
    .B(_0255_),
    .Y(_0287_)
  );
  AOI21X0P5H7R _0858_ (
    .A0(_0286_),
    .A1(_0287_),
    .B0(reset),
    .Y(_0028_)
  );
  NAND3X0P5H7R _0859_ (
    .A(\DmaAddr[5] ),
    .B(\DmaAddr[4] ),
    .C(_0235_),
    .Y(_0288_)
  );
  NOR3X0P5H7R _0860_ (
    .A(\DmaAddr[6] ),
    .B(_0234_),
    .C(_0288_),
    .Y(_0289_)
  );
  AOAI211X1P4H7L _0861_ (
    .A0(\Dmc.SampleAddress_0_ ),
    .A1(_0233_),
    .B0(_0289_),
    .C0(_0240_),
    .Y(_0290_)
  );
  AOAI211X0P5H7R _0862_ (
    .A0(_0243_),
    .A1(_0288_),
    .B0(_0244_),
    .C0(\DmaAddr[6] ),
    .Y(_0291_)
  );
  AOI21X0P5H7R _0863_ (
    .A0(_0290_),
    .A1(_0291_),
    .B0(reset),
    .Y(_0029_)
  );
  OR2X1P4H7L _0864_ (
    .A(_0234_),
    .B(_0246_),
    .Y(_0292_)
  );
  OAI21X1P4H7L _0865_ (
    .A0(\Dmc.SampleAddress_1_ ),
    .A1(_0258_),
    .B0(_0292_),
    .Y(_0293_)
  );
  OAOI211X0P5H7R _0866_ (
    .A0(_0231_),
    .A1(_0236_),
    .B0(_0251_),
    .C0(\DmaAddr[7] ),
    .Y(_0294_)
  );
  AOI211X1P4H7L _0867_ (
    .A0(_0240_),
    .A1(_0293_),
    .B0(_0294_),
    .C0(reset),
    .Y(_0030_)
  );
  NOR3X0P5H7R _0868_ (
    .A(\DmaAddr[8] ),
    .B(_0234_),
    .C(_0246_),
    .Y(_0295_)
  );
  AOAI211X1P4H7L _0869_ (
    .A0(\Dmc.SampleAddress_2_ ),
    .A1(_0233_),
    .B0(_0295_),
    .C0(_0240_),
    .Y(_0296_)
  );
  AOAI211X0P5H7R _0870_ (
    .A0(_0243_),
    .A1(_0246_),
    .B0(_0244_),
    .C0(\DmaAddr[8] ),
    .Y(_0297_)
  );
  AOI21X0P5H7R _0871_ (
    .A0(_0296_),
    .A1(_0297_),
    .B0(reset),
    .Y(_0031_)
  );
  NAND3X0P5H7R _0872_ (
    .A(\DmaAddr[8] ),
    .B(\DmaAddr[7] ),
    .C(_0236_),
    .Y(_0298_)
  );
  NOR3X0P5H7R _0873_ (
    .A(\DmaAddr[9] ),
    .B(_0234_),
    .C(_0298_),
    .Y(_0299_)
  );
  AOAI211X1P4H7L _0874_ (
    .A0(\Dmc.SampleAddress_3_ ),
    .A1(_0233_),
    .B0(_0299_),
    .C0(_0240_),
    .Y(_0300_)
  );
  AOAI211X0P5H7R _0875_ (
    .A0(_0243_),
    .A1(_0298_),
    .B0(_0244_),
    .C0(\DmaAddr[9] ),
    .Y(_0301_)
  );
  AOI21X0P5H7R _0876_ (
    .A0(_0300_),
    .A1(_0301_),
    .B0(reset),
    .Y(_0032_)
  );
  NOR3BX0P5H7R _0877_ (
    .AN(\DOUT[4] ),
    .B(\Dmc.HasSampleBuffer ),
    .C(\Dmc.ActivationDelay_0_ ),
    .Y(DmaReq)
  );
  NAND3X1P4H7L _0878_ (
    .A(ce),
    .B(\ADDR[4] ),
    .C(MW),
    .Y(_0302_)
  );
  OR4X1P4H7R _0879_ (
    .A(_0222_),
    .B(\DOUT[4] ),
    .C(_0302_),
    .D(_0220_),
    .Y(_0303_)
  );
  OAI21X0P5H7R _0880_ (
    .A0(_0162_),
    .A1(\Dmc.ActivationDelay_1_ ),
    .B0(\Dmc.ActivationDelay_0_ ),
    .Y(_0304_)
  );
  AOI21X0P5H7R _0881_ (
    .A0(_0303_),
    .A1(_0304_),
    .B0(reset),
    .Y(_0033_)
  );
  NAND2X0P5H7R _0882_ (
    .A(ce),
    .B(\Dmc.ActivationDelay_0_ ),
    .Y(_0305_)
  );
  OAI21X0P5H7R _0883_ (
    .A0(odd_or_even),
    .A1(_0305_),
    .B0(\Dmc.ActivationDelay_1_ ),
    .Y(_0306_)
  );
  AOI21X0P5H7R _0884_ (
    .A0(_0303_),
    .A1(_0306_),
    .B0(reset),
    .Y(_0034_)
  );
  OR4X1P4H7L _0885_ (
    .A(\Dmc.Cycles_5_ ),
    .B(\Dmc.Cycles_4_ ),
    .C(\Dmc.Cycles_3_ ),
    .D(\Dmc.Cycles_2_ ),
    .Y(_0307_)
  );
  NAND3BBX0P5H7R _0886_ (
    .AN(\Dmc.Cycles_7_ ),
    .BN(\Dmc.Cycles_1_ ),
    .C(ce),
    .Y(_0308_)
  );
  NAND2BX0P5H7R _0887_ (
    .AN(\Dmc.Cycles_8_ ),
    .B(\Dmc.Cycles_0_ ),
    .Y(_0309_)
  );
  OR4X1P4H7L _0888_ (
    .A(\Dmc.Cycles_6_ ),
    .B(_0307_),
    .C(_0308_),
    .D(_0309_),
    .Y(_0310_)
  );
  XOR2X0P5H7R _0889_ (
    .A(\Dmc.BitsUsed_0_ ),
    .B(_0310_),
    .Y(_0311_)
  );
  NOR2X0P5H7R _0890_ (
    .A(reset),
    .B(_0311_),
    .Y(_0035_)
  );
  NOR2BX1P4H7L _0891_ (
    .AN(\Dmc.BitsUsed_0_ ),
    .B(_0310_),
    .Z(_0312_)
  );
  XNOR2X0P5H7R _0892_ (
    .A(\Dmc.BitsUsed_1_ ),
    .B(_0312_),
    .Y(_0313_)
  );
  NOR2X0P5H7R _0893_ (
    .A(reset),
    .B(_0313_),
    .Y(_0036_)
  );
  NAND2X0P5H7R _0894_ (
    .A(\Dmc.BitsUsed_1_ ),
    .B(_0312_),
    .Y(_0314_)
  );
  XOR2X1P4H7L _0895_ (
    .A(\Dmc.BitsUsed_2_ ),
    .B(_0314_),
    .Y(_0315_)
  );
  NOR2X0P5H7R _0896_ (
    .A(reset),
    .B(_0315_),
    .Y(_0037_)
  );
  NOR3X0P5H7R _0897_ (
    .A(\Dmc.BytesLeft_0_ ),
    .B(_0231_),
    .C(_0225_),
    .Y(_0316_)
  );
  AOA211X0P5H7L _0898_ (
    .A0(\Dmc.BytesLeft_0_ ),
    .A1(_0225_),
    .B0(_0316_),
    .C0(_0219_),
    .Y(_0038_)
  );
  OR2X8H7L _0899_ (
    .A(\Dmc.BytesLeft_7_ ),
    .B(_0229_),
    .Y(_0317_)
  );
  AOI2BB1X0P5H7R _0900_ (
    .A0N(_0226_),
    .A1N(_0317_),
    .B0(_0231_),
    .Y(_0318_)
  );
  OAI21X1P4H7L _0901_ (
    .A0(_0244_),
    .A1(_0318_),
    .B0(\Dmc.BytesLeft_10_ ),
    .Y(_0319_)
  );
  OR3X8H7L _0902_ (
    .A(\Dmc.BytesLeft_10_ ),
    .B(_0226_),
    .C(_0317_),
    .Y(_0320_)
  );
  NAND2X0P5H7R _0903_ (
    .A(\Dmc.SampleLen_6_ ),
    .B(_0234_),
    .Y(_0321_)
  );
  OAO211X4H7L _0904_ (
    .A0(_0231_),
    .A1(_0320_),
    .B0(_0321_),
    .C0(_0225_),
    .Y(_0322_)
  );
  AOI21X2H7L _0905_ (
    .A0(_0319_),
    .A1(_0322_),
    .B0(reset),
    .Y(_0039_)
  );
  AOI2BB1X0P7H7L _0906_ (
    .A0N(\Dmc.BytesLeft_11_ ),
    .A1N(_0320_),
    .B0(_0242_),
    .Y(_0323_)
  );
  NAND2X0P5H7R _0907_ (
    .A(\Dmc.SampleLen_7_ ),
    .B(_0251_),
    .Y(_0324_)
  );
  AOAI211X0P5H7R _0908_ (
    .A0(DmaAck),
    .A1(_0320_),
    .B0(_0244_),
    .C0(\Dmc.BytesLeft_11_ ),
    .Y(_0325_)
  );
  OAOI211X1H7L _0909_ (
    .A0(_0323_),
    .A1(_0324_),
    .B0(_0325_),
    .C0(reset),
    .Y(_0040_)
  );
  NOR3X0P5H7R _0910_ (
    .A(\Dmc.BytesLeft_1_ ),
    .B(\Dmc.BytesLeft_0_ ),
    .C(_0225_),
    .Y(_0326_)
  );
  AOAI211X1P4H7L _0911_ (
    .A0(\Dmc.BytesLeft_1_ ),
    .A1(\Dmc.BytesLeft_0_ ),
    .B0(_0326_),
    .C0(_0258_),
    .Y(_0327_)
  );
  NAND2X0P5H7R _0912_ (
    .A(\Dmc.BytesLeft_1_ ),
    .B(_0255_),
    .Y(_0328_)
  );
  AOI21X0P5H7R _0913_ (
    .A0(_0327_),
    .A1(_0328_),
    .B0(reset),
    .Y(_0041_)
  );
  OR3X1H7R _0914_ (
    .A(\Dmc.BytesLeft_2_ ),
    .B(\Dmc.BytesLeft_1_ ),
    .C(\Dmc.BytesLeft_0_ ),
    .Y(_0329_)
  );
  OAI21X0P5H7R _0915_ (
    .A0(\Dmc.BytesLeft_1_ ),
    .A1(\Dmc.BytesLeft_0_ ),
    .B0(\Dmc.BytesLeft_2_ ),
    .Y(_0330_)
  );
  OAI21X0P5H7R _0916_ (
    .A0(_0329_),
    .A1(_0225_),
    .B0(_0330_),
    .Y(_0331_)
  );
  AOI22X1H7L _0917_ (
    .A0(\Dmc.BytesLeft_2_ ),
    .A1(_0255_),
    .B0(_0331_),
    .B1(_0258_),
    .Y(_0332_)
  );
  NOR2X0P5H7R _0918_ (
    .A(reset),
    .B(_0332_),
    .Y(_0042_)
  );
  NOR3X0P5H7R _0919_ (
    .A(\Dmc.BytesLeft_3_ ),
    .B(_0329_),
    .C(_0225_),
    .Y(_0333_)
  );
  AOAI211X1P4H7L _0920_ (
    .A0(\Dmc.BytesLeft_3_ ),
    .A1(_0329_),
    .B0(_0333_),
    .C0(_0258_),
    .Y(_0334_)
  );
  NAND2X0P5H7R _0921_ (
    .A(\Dmc.BytesLeft_3_ ),
    .B(_0255_),
    .Y(_0335_)
  );
  AOI21X0P5H7R _0922_ (
    .A0(_0334_),
    .A1(_0335_),
    .B0(reset),
    .Y(_0043_)
  );
  AOAI211X0P5H7R _0923_ (
    .A0(DmaAck),
    .A1(_0228_),
    .B0(_0244_),
    .C0(\Dmc.BytesLeft_4_ ),
    .Y(_0336_)
  );
  OR2X1P4H7R _0924_ (
    .A(\Dmc.BytesLeft_4_ ),
    .B(_0228_),
    .Y(_0337_)
  );
  NOR2X0P5H7R _0925_ (
    .A(_0231_),
    .B(_0337_),
    .Y(_0338_)
  );
  AOAI211X1P4H7L _0926_ (
    .A0(\Dmc.SampleLen_0_ ),
    .A1(_0233_),
    .B0(_0338_),
    .C0(_0240_),
    .Y(_0339_)
  );
  AOI21X0P5H7R _0927_ (
    .A0(_0336_),
    .A1(_0339_),
    .B0(reset),
    .Y(_0044_)
  );
  NOR3X0P5H7R _0928_ (
    .A(\Dmc.BytesLeft_5_ ),
    .B(_0234_),
    .C(_0337_),
    .Y(_0340_)
  );
  AOAI211X1P4H7L _0929_ (
    .A0(\Dmc.SampleLen_1_ ),
    .A1(_0233_),
    .B0(_0340_),
    .C0(_0240_),
    .Y(_0341_)
  );
  AOAI211X0P5H7R _0930_ (
    .A0(DmaAck),
    .A1(_0337_),
    .B0(_0244_),
    .C0(\Dmc.BytesLeft_5_ ),
    .Y(_0342_)
  );
  AOI21X0P5H7R _0931_ (
    .A0(_0341_),
    .A1(_0342_),
    .B0(reset),
    .Y(_0045_)
  );
  NOR3X0P5H7R _0932_ (
    .A(\Dmc.BytesLeft_5_ ),
    .B(\Dmc.BytesLeft_4_ ),
    .C(_0228_),
    .Y(_0343_)
  );
  NAND3X0P5H7R _0933_ (
    .A(\Dmc.BytesLeft_6_ ),
    .B(_0343_),
    .C(_0251_),
    .Y(_0344_)
  );
  OAI21X0P5H7R _0934_ (
    .A0(\Dmc.BytesLeft_6_ ),
    .A1(_0343_),
    .B0(_0344_),
    .Y(_0345_)
  );
  OA22X0P5H7R _0935_ (
    .A0(\Dmc.BytesLeft_6_ ),
    .A1(_0227_),
    .B0(_0303_),
    .B1(DmaAck),
    .Y(_0346_)
  );
  OAI221X1P4H7L _0936_ (
    .A0(\Dmc.BytesLeft_6_ ),
    .A1(_0251_),
    .B0(_0346_),
    .B1(\Dmc.SampleLen_2_ ),
    .C0(_0165_),
    .Y(_0347_)
  );
  AOI21X0P5H7R _0937_ (
    .A0(DmaAck),
    .A1(_0345_),
    .B0(_0347_),
    .Y(_0046_)
  );
  AOI21X0P5H7R _0938_ (
    .A0(DmaAck),
    .A1(_0229_),
    .B0(_0224_),
    .Y(_0348_)
  );
  NOR2X0P5H7R _0939_ (
    .A(_0242_),
    .B(_0229_),
    .Y(_0349_)
  );
  NOR2X1P4H7L _0940_ (
    .A(\Dmc.SampleLen_3_ ),
    .B(_0243_),
    .Y(_0350_)
  );
  AOI21X0P5H7R _0941_ (
    .A0(\Dmc.BytesLeft_7_ ),
    .A1(_0349_),
    .B0(_0350_),
    .Y(_0351_)
  );
  OA221X0P5H7L _0942_ (
    .A0(\Dmc.BytesLeft_7_ ),
    .A1(_0348_),
    .B0(_0351_),
    .B1(_0225_),
    .C0(_0166_),
    .Y(_0047_)
  );
  NOR3X0P5H7R _0943_ (
    .A(\Dmc.BytesLeft_8_ ),
    .B(_0234_),
    .C(_0317_),
    .Y(_0352_)
  );
  AOAI211X1P4H7L _0944_ (
    .A0(\Dmc.SampleLen_4_ ),
    .A1(_0233_),
    .B0(_0352_),
    .C0(_0240_),
    .Y(_0353_)
  );
  AOAI211X0P5H7R _0945_ (
    .A0(_0243_),
    .A1(_0317_),
    .B0(_0244_),
    .C0(\Dmc.BytesLeft_8_ ),
    .Y(_0354_)
  );
  AOI21X0P5H7R _0946_ (
    .A0(_0353_),
    .A1(_0354_),
    .B0(reset),
    .Y(_0048_)
  );
  NOR3X1P4H7L _0947_ (
    .A(\Dmc.BytesLeft_8_ ),
    .B(\Dmc.BytesLeft_7_ ),
    .C(_0229_),
    .Y(_0355_)
  );
  NOR3BX1P4H7L _0948_ (
    .AN(_0355_),
    .B(\Dmc.BytesLeft_9_ ),
    .C(_0231_),
    .Y(_0356_)
  );
  AOAI211X1P4H7L _0949_ (
    .A0(\Dmc.SampleLen_5_ ),
    .A1(_0231_),
    .B0(_0356_),
    .C0(_0251_),
    .Y(_0357_)
  );
  OAI21X0P5H7R _0950_ (
    .A0(_0231_),
    .A1(_0355_),
    .B0(_0251_),
    .Y(_0358_)
  );
  NAND2X0P5H7R _0951_ (
    .A(\Dmc.BytesLeft_9_ ),
    .B(_0358_),
    .Y(_0359_)
  );
  AOI21X0P5H7R _0952_ (
    .A0(_0357_),
    .A1(_0359_),
    .B0(reset),
    .Y(_0049_)
  );
  NAND2X0P5H7R _0953_ (
    .A(_0162_),
    .B(\Dmc.Cycles_0_ ),
    .Y(_0360_)
  );
  NAND2BX0P5H7R _0954_ (
    .AN(\Dmc.Cycles_0_ ),
    .B(ce),
    .Y(_0361_)
  );
  NAND3X0P5H7R _0955_ (
    .A(_0219_),
    .B(_0360_),
    .C(_0361_),
    .Y(_0050_)
  );
  OR2X1P4H7L _0956_ (
    .A(\Dmc.Cycles_1_ ),
    .B(_0361_),
    .Y(_0362_)
  );
  NAND2X0P5H7R _0957_ (
    .A(\Dmc.Cycles_1_ ),
    .B(_0361_),
    .Y(_0363_)
  );
  NAND3X0P5H7R _0958_ (
    .A(_0219_),
    .B(_0362_),
    .C(_0363_),
    .Y(_0051_)
  );
  XOR2X0P5H7R _0959_ (
    .A(\Dmc.Cycles_2_ ),
    .B(_0362_),
    .Y(_0364_)
  );
  NAND2X0P5H7R _0960_ (
    .A(_0219_),
    .B(_0364_),
    .Y(_0052_)
  );
  OR4X1P4H7R _0961_ (
    .A(\Dmc.Cycles_3_ ),
    .B(\Dmc.Cycles_2_ ),
    .C(\Dmc.Cycles_1_ ),
    .D(_0361_),
    .Y(_0365_)
  );
  OAI31X0P5H7R _0962_ (
    .A0(\Dmc.Cycles_2_ ),
    .A1(\Dmc.Cycles_1_ ),
    .A2(_0361_),
    .B0(\Dmc.Cycles_3_ ),
    .Y(_0366_)
  );
  AOI21X0P5H7R _0963_ (
    .A0(_0365_),
    .A1(_0366_),
    .B0(reset),
    .Y(_0053_)
  );
  XOR2X0P5H7R _0964_ (
    .A(\Dmc.Cycles_4_ ),
    .B(_0365_),
    .Y(_0367_)
  );
  NAND2X0P5H7R _0965_ (
    .A(_0219_),
    .B(_0367_),
    .Y(_0054_)
  );
  OR3X1H7R _0966_ (
    .A(\Dmc.Cycles_5_ ),
    .B(\Dmc.Cycles_4_ ),
    .C(_0365_),
    .Y(_0368_)
  );
  OAI21X0P5H7R _0967_ (
    .A0(\Dmc.Cycles_4_ ),
    .A1(_0365_),
    .B0(\Dmc.Cycles_5_ ),
    .Y(_0369_)
  );
  NAND3X0P5H7R _0968_ (
    .A(_0219_),
    .B(_0368_),
    .C(_0369_),
    .Y(_0055_)
  );
  OR3X1H7R _0969_ (
    .A(\Dmc.Cycles_6_ ),
    .B(_0307_),
    .C(_0362_),
    .Y(_0370_)
  );
  OAI21X0P5H7R _0970_ (
    .A0(_0307_),
    .A1(_0362_),
    .B0(\Dmc.Cycles_6_ ),
    .Y(_0371_)
  );
  AOI21X0P5H7R _0971_ (
    .A0(_0370_),
    .A1(_0371_),
    .B0(reset),
    .Y(_0056_)
  );
  NOR3X0P5H7R _0972_ (
    .A(\Dmc.Cycles_6_ ),
    .B(_0307_),
    .C(_0362_),
    .Y(_0372_)
  );
  XNOR2X0P5H7R _0973_ (
    .A(\Dmc.Cycles_7_ ),
    .B(_0372_),
    .Y(_0373_)
  );
  NAND2X0P5H7R _0974_ (
    .A(_0219_),
    .B(_0373_),
    .Y(_0057_)
  );
  OR4X1P4H7R _0975_ (
    .A(\Dmc.Cycles_6_ ),
    .B(\Dmc.Cycles_0_ ),
    .C(_0307_),
    .D(_0308_),
    .Y(_0374_)
  );
  XOR2X0P5H7R _0976_ (
    .A(\Dmc.Cycles_8_ ),
    .B(_0374_),
    .Y(_0375_)
  );
  NAND2X0P5H7R _0977_ (
    .A(_0219_),
    .B(_0375_),
    .Y(_0058_)
  );
  NAND2X0P5H7R _0978_ (
    .A(\Dmc.BitsUsed_2_ ),
    .B(_0242_),
    .Y(_0376_)
  );
  OAI21X0P5H7R _0979_ (
    .A0(_0314_),
    .A1(_0376_),
    .B0(\Dmc.HasSampleBuffer ),
    .Y(_0377_)
  );
  OAOI211X0P5H7R _0980_ (
    .A0(_0162_),
    .A1(_0242_),
    .B0(_0377_),
    .C0(reset),
    .Y(_0059_)
  );
  NOR2X0P5H7R _0981_ (
    .A(\ADDR[0] ),
    .B(\ADDR[1] ),
    .Y(_0378_)
  );
  NAND2X0P5H7R _0982_ (
    .A(ce),
    .B(_0378_),
    .Y(_0379_)
  );
  NOR3X0P5H7R _0983_ (
    .A(\ADDR[2] ),
    .B(_0157_),
    .C(_0379_),
    .Y(_0380_)
  );
  NAND2X0P5H7R _0984_ (
    .A(\DIN[7] ),
    .B(_0380_),
    .Y(_0381_)
  );
  NAND2BX0P5H7R _0985_ (
    .AN(_0380_),
    .B(\Dmc.IrqEnable ),
    .Y(_0382_)
  );
  AOI21X0P5H7R _0986_ (
    .A0(_0381_),
    .A1(_0382_),
    .B0(reset),
    .Y(_0060_)
  );
  OR3X1H7R _0987_ (
    .A(_0242_),
    .B(_0227_),
    .C(_0229_),
    .Y(_0383_)
  );
  NOR2X0P5H7R _0988_ (
    .A(_0162_),
    .B(\Dmc.Loop ),
    .Y(_0384_)
  );
  NAND2X0P5H7R _0989_ (
    .A(\Dmc.IrqEnable ),
    .B(_0384_),
    .Y(_0385_)
  );
  NOR3X0P5H7R _0990_ (
    .A(\DIN[7] ),
    .B(\ADDR[0] ),
    .C(\ADDR[2] ),
    .Y(_0386_)
  );
  AOI21X0P5H7R _0991_ (
    .A0(\ADDR[0] ),
    .A1(\ADDR[2] ),
    .B0(_0386_),
    .Y(_0387_)
  );
  OAI31X0P5H7R _0992_ (
    .A0(\ADDR[1] ),
    .A1(_0302_),
    .A2(_0387_),
    .B0(\DOUT[7] ),
    .Y(_0388_)
  );
  OAOI211X0P5H7R _0993_ (
    .A0(_0383_),
    .A1(_0385_),
    .B0(_0388_),
    .C0(reset),
    .Y(_0061_)
  );
  NAND3X0P5H7R _0994_ (
    .A(ce),
    .B(_0222_),
    .C(_0221_),
    .Y(_0389_)
  );
  OAI211X0P7H7L _0995_ (
    .A0(\DOUT[4] ),
    .A1(_0221_),
    .B0(_0383_),
    .C0(_0389_),
    .Y(_0390_)
  );
  OAI21X0P5H7R _0996_ (
    .A0(ce),
    .A1(\DOUT[4] ),
    .B0(_0166_),
    .Y(_0391_)
  );
  OAOI211X0P5H7R _0997_ (
    .A0(_0383_),
    .A1(_0384_),
    .B0(_0390_),
    .C0(_0391_),
    .Y(_0062_)
  );
  NAND2X0P5H7R _0998_ (
    .A(\DIN[6] ),
    .B(_0380_),
    .Y(_0392_)
  );
  NAND2BX0P5H7R _0999_ (
    .AN(_0380_),
    .B(\Dmc.Loop ),
    .Y(_0393_)
  );
  AOI21X0P5H7R _1000_ (
    .A0(_0392_),
    .A1(_0393_),
    .B0(reset),
    .Y(_0063_)
  );
  NAND2BX0P5H7R _1001_ (
    .AN(\ADDR[0] ),
    .B(\ADDR[1] ),
    .Y(_0394_)
  );
  NOR3X1P4H7L _1002_ (
    .A(\ADDR[2] ),
    .B(_0302_),
    .C(_0394_),
    .Y(_0395_)
  );
  BUFX0P5H7R _1003_ (
    .A(_0395_),
    .Y(_0396_)
  );
  NAND2X0P5H7R _1004_ (
    .A(\DIN[0] ),
    .B(_0396_),
    .Y(_0397_)
  );
  NAND2BX0P5H7R _1005_ (
    .AN(_0396_),
    .B(\Dmc.SampleAddress_0_ ),
    .Y(_0398_)
  );
  AOI21X0P5H7R _1006_ (
    .A0(_0397_),
    .A1(_0398_),
    .B0(reset),
    .Y(_0064_)
  );
  NAND2X0P5H7R _1007_ (
    .A(\DIN[1] ),
    .B(_0396_),
    .Y(_0399_)
  );
  NAND2BX0P5H7R _1008_ (
    .AN(_0396_),
    .B(\Dmc.SampleAddress_1_ ),
    .Y(_0400_)
  );
  AOI21X0P5H7R _1009_ (
    .A0(_0399_),
    .A1(_0400_),
    .B0(reset),
    .Y(_0065_)
  );
  NAND2X0P5H7R _1010_ (
    .A(\DIN[2] ),
    .B(_0396_),
    .Y(_0401_)
  );
  NAND2BX0P5H7R _1011_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_2_ ),
    .Y(_0402_)
  );
  AOI21X0P5H7R _1012_ (
    .A0(_0401_),
    .A1(_0402_),
    .B0(reset),
    .Y(_0066_)
  );
  NAND2X0P5H7R _1013_ (
    .A(\DIN[3] ),
    .B(_0396_),
    .Y(_0403_)
  );
  NAND2BX0P5H7R _1014_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_3_ ),
    .Y(_0404_)
  );
  AOI21X0P5H7R _1015_ (
    .A0(_0403_),
    .A1(_0404_),
    .B0(reset),
    .Y(_0067_)
  );
  NAND2X0P5H7R _1016_ (
    .A(\DIN[4] ),
    .B(_0396_),
    .Y(_0405_)
  );
  NAND2BX0P5H7R _1017_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_4_ ),
    .Y(_0406_)
  );
  AOI21X0P5H7R _1018_ (
    .A0(_0405_),
    .A1(_0406_),
    .B0(reset),
    .Y(_0068_)
  );
  NAND2X0P5H7R _1019_ (
    .A(\DIN[5] ),
    .B(_0396_),
    .Y(_0407_)
  );
  NAND2BX0P5H7R _1020_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_5_ ),
    .Y(_0408_)
  );
  AOI21X0P5H7R _1021_ (
    .A0(_0407_),
    .A1(_0408_),
    .B0(reset),
    .Y(_0069_)
  );
  NAND2X0P5H7R _1022_ (
    .A(\DIN[6] ),
    .B(_0396_),
    .Y(_0409_)
  );
  NAND2BX0P5H7R _1023_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_6_ ),
    .Y(_0410_)
  );
  AOI21X0P5H7R _1024_ (
    .A0(_0409_),
    .A1(_0410_),
    .B0(reset),
    .Y(_0070_)
  );
  NAND2X0P5H7R _1025_ (
    .A(\DIN[7] ),
    .B(_0396_),
    .Y(_0411_)
  );
  NAND2BX0P5H7R _1026_ (
    .AN(_0395_),
    .B(\Dmc.SampleAddress_7_ ),
    .Y(_0412_)
  );
  AOI21X0P5H7R _1027_ (
    .A0(_0411_),
    .A1(_0412_),
    .B0(reset),
    .Y(_0071_)
  );
  NOR3X0P5H7R _1028_ (
    .A(\ADDR[2] ),
    .B(_0158_),
    .C(_0302_),
    .Y(_0413_)
  );
  NAND2X0P5H7R _1029_ (
    .A(\DIN[0] ),
    .B(_0413_),
    .Y(_0414_)
  );
  OR3X1H7R _1030_ (
    .A(\ADDR[2] ),
    .B(_0158_),
    .C(_0302_),
    .Y(_0415_)
  );
  BUFX1P4H7L _1031_ (
    .A(_0415_),
    .Y(_0416_)
  );
  NAND2X0P5H7R _1032_ (
    .A(\Dmc.SampleLen_0_ ),
    .B(_0416_),
    .Y(_0417_)
  );
  AOI21X0P5H7R _1033_ (
    .A0(_0414_),
    .A1(_0417_),
    .B0(reset),
    .Y(_0072_)
  );
  NAND2X0P5H7R _1034_ (
    .A(\DIN[1] ),
    .B(_0413_),
    .Y(_0418_)
  );
  NAND2X0P5H7R _1035_ (
    .A(\Dmc.SampleLen_1_ ),
    .B(_0416_),
    .Y(_0419_)
  );
  AOI21X0P5H7R _1036_ (
    .A0(_0418_),
    .A1(_0419_),
    .B0(reset),
    .Y(_0073_)
  );
  NAND2X0P5H7R _1037_ (
    .A(\DIN[2] ),
    .B(_0413_),
    .Y(_0420_)
  );
  NAND2X0P5H7R _1038_ (
    .A(\Dmc.SampleLen_2_ ),
    .B(_0416_),
    .Y(_0421_)
  );
  AOI21X0P5H7R _1039_ (
    .A0(_0420_),
    .A1(_0421_),
    .B0(reset),
    .Y(_0074_)
  );
  NAND2X0P5H7R _1040_ (
    .A(\DIN[3] ),
    .B(_0413_),
    .Y(_0422_)
  );
  NAND2X0P5H7R _1041_ (
    .A(\Dmc.SampleLen_3_ ),
    .B(_0416_),
    .Y(_0423_)
  );
  AOI21X0P5H7R _1042_ (
    .A0(_0422_),
    .A1(_0423_),
    .B0(reset),
    .Y(_0075_)
  );
  NAND2X0P5H7R _1043_ (
    .A(\Dmc.SampleLen_4_ ),
    .B(_0416_),
    .Y(_0424_)
  );
  OAOI211X0P5H7R _1044_ (
    .A0(_0222_),
    .A1(_0416_),
    .B0(_0424_),
    .C0(reset),
    .Y(_0076_)
  );
  NAND2X0P5H7R _1045_ (
    .A(\DIN[5] ),
    .B(_0413_),
    .Y(_0425_)
  );
  NAND2X0P5H7R _1046_ (
    .A(\Dmc.SampleLen_5_ ),
    .B(_0416_),
    .Y(_0426_)
  );
  AOI21X0P5H7R _1047_ (
    .A0(_0425_),
    .A1(_0426_),
    .B0(reset),
    .Y(_0077_)
  );
  NAND2X0P5H7R _1048_ (
    .A(\Dmc.SampleLen_6_ ),
    .B(_0416_),
    .Y(_0427_)
  );
  NAND2X0P5H7R _1049_ (
    .A(\DIN[6] ),
    .B(_0413_),
    .Y(_0428_)
  );
  AOI21X0P5H7R _1050_ (
    .A0(_0427_),
    .A1(_0428_),
    .B0(reset),
    .Y(_0078_)
  );
  NAND2X0P5H7R _1051_ (
    .A(\Dmc.SampleLen_7_ ),
    .B(_0416_),
    .Y(_0429_)
  );
  OAOI211X0P5H7R _1052_ (
    .A0(_0156_),
    .A1(_0416_),
    .B0(_0429_),
    .C0(reset),
    .Y(_0079_)
  );
  NAND3X0P5H7R _1053_ (
    .A(ce),
    .B(\ADDR[4] ),
    .C(MR),
    .Y(_0430_)
  );
  OAI31X0P5H7R _1054_ (
    .A0(\ADDR[3] ),
    .A1(_0220_),
    .A2(_0430_),
    .B0(FrameInterrupt),
    .Y(_0431_)
  );
  AOAI211X0P5H7R _1055_ (
    .A0(_0131_),
    .A1(_0153_),
    .B0(_0151_),
    .C0(_0149_),
    .Y(_0432_)
  );
  AND3X1P4H7L _1056_ (
    .A(_0145_),
    .B(_0142_),
    .C(_0432_),
    .Y(_0433_)
  );
  OAI21X0P5H7R _1057_ (
    .A0(IrqCtr_1_),
    .A1(_0433_),
    .B0(ce),
    .Y(_0434_)
  );
  OAOI211X0P5H7R _1058_ (
    .A0(_0218_),
    .A1(_0431_),
    .B0(_0434_),
    .C0(reset),
    .Y(_0080_)
  );
  NAND2X0P5H7R _1059_ (
    .A(FrameSeqMode),
    .B(_0217_),
    .Y(_0435_)
  );
  OAOI211X0P5H7R _1060_ (
    .A0(_0156_),
    .A1(_0217_),
    .B0(_0435_),
    .C0(reset),
    .Y(_0081_)
  );
  NOR2BX1P4H7L _1061_ (
    .AN(FrameInterrupt),
    .B(DisableFrameInterrupt),
    .Z(\DOUT[6] )
  );
  OR2X0P5H7L _1062_ (
    .A(\DOUT[7] ),
    .B(\DOUT[6] ),
    .Y(IRQ)
  );
  NOR2BX1P4H7L _1063_ (
    .AN(IrqCtr_0_),
    .B(ce),
    .Z(_0436_)
  );
  AOA211X0P5H7L _1064_ (
    .A0(ce),
    .A1(_0433_),
    .B0(_0436_),
    .C0(_0166_),
    .Y(_0082_)
  );
  NOR2X0P5H7R _1065_ (
    .A(IrqCtr_0_),
    .B(_0433_),
    .Y(_0437_)
  );
  NOR2X0P5H7R _1066_ (
    .A(ce),
    .B(IrqCtr_1_),
    .Y(_0438_)
  );
  AOI211X0P5H7R _1067_ (
    .A0(ce),
    .A1(_0437_),
    .B0(_0438_),
    .C0(reset),
    .Y(_0083_)
  );
  NOR3X1P4H7L _1068_ (
    .A(\ADDR[3] ),
    .B(_0302_),
    .C(_0220_),
    .Y(_0439_)
  );
  NAND2BX0P5H7R _1069_ (
    .AN(_0439_),
    .B(\Noi.Enabled ),
    .Y(_0440_)
  );
  NAND2X0P5H7R _1070_ (
    .A(\DIN[3] ),
    .B(_0439_),
    .Y(_0441_)
  );
  AOI21X0P5H7R _1071_ (
    .A0(_0440_),
    .A1(_0441_),
    .B0(reset),
    .Y(_0084_)
  );
  NAND3BX0P5H7R _1072_ (
    .AN(\ADDR[4] ),
    .B(\ADDR[2] ),
    .C(MW),
    .Y(_0442_)
  );
  NOR3BX0P5H7R _1073_ (
    .AN(\ADDR[3] ),
    .B(_0379_),
    .C(_0442_),
    .Y(_0443_)
  );
  MUXI2X0P5H7R _1074_ (
    .A(\Noi.EnvLoop ),
    .B(\DIN[5] ),
    .S0(_0443_),
    .Y(_0444_)
  );
  NOR2X0P5H7R _1075_ (
    .A(reset),
    .B(_0444_),
    .Y(_0085_)
  );
  NOR3X0P7H7L _1076_ (
    .A(\Noi.LenCtr_2_ ),
    .B(\Noi.LenCtr_1_ ),
    .C(\Noi.LenCtr_0_ ),
    .Y(_0445_)
  );
  NOR3X0P5H7R _1077_ (
    .A(\Noi.LenCtr_5_ ),
    .B(\Noi.LenCtr_4_ ),
    .C(\Noi.LenCtr_3_ ),
    .Y(_0446_)
  );
  NAND3BX2H7L _1078_ (
    .AN(\Noi.LenCtr_6_ ),
    .B(_0445_),
    .C(_0446_),
    .Y(_0447_)
  );
  OR2X0P5H7L _1079_ (
    .A(\Noi.LenCtr_7_ ),
    .B(_0447_),
    .Y(\DOUT[3] )
  );
  NOR2BX1P4H7L _1080_ (
    .AN(ClkL),
    .B(\Noi.EnvLoop ),
    .Z(_0448_)
  );
  OAI21X3H7L _1081_ (
    .A0(\Noi.LenCtr_7_ ),
    .A1(_0447_),
    .B0(_0448_),
    .Y(_0449_)
  );
  NAND3X0P5H7R _1082_ (
    .A(\ADDR[0] ),
    .B(\ADDR[1] ),
    .C(\ADDR[3] ),
    .Y(_0450_)
  );
  NOR2X0P5H7R _1083_ (
    .A(_0442_),
    .B(_0450_),
    .Y(_0451_)
  );
  INVX0P5H7R _1084_ (
    .A(_0451_),
    .Y(_0452_)
  );
  AOI31X1P4H7L _1085_ (
    .A0(\Noi.Enabled ),
    .A1(_0449_),
    .A2(_0452_),
    .B0(_0161_),
    .Y(_0453_)
  );
  BUFX3H7L _1086_ (
    .A(_0453_),
    .Y(_0454_)
  );
  NAND2BX0P7H7L _1087_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_0_ ),
    .Y(_0455_)
  );
  OA21X1P4H7L _1088_ (
    .A0(\Noi.LenCtr_7_ ),
    .A1(_0447_),
    .B0(_0448_),
    .Y(_0456_)
  );
  NAND4BX0P5H7R _1089_ (
    .AN(\Noi.LenCtr_0_ ),
    .B(\Noi.Enabled ),
    .C(_0456_),
    .D(ce),
    .Y(_0457_)
  );
  AOI21X0P5H7R _1090_ (
    .A0(_0455_),
    .A1(_0457_),
    .B0(reset),
    .Y(_0086_)
  );
  NAND2BX0P7H7L _1091_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_1_ ),
    .Y(_0458_)
  );
  NOR2BX1P4H7L _1092_ (
    .AN(\DIN[6] ),
    .B(\DIN[3] ),
    .Z(_0459_)
  );
  NOR3X0P5H7R _1093_ (
    .A(\DIN[5] ),
    .B(\DIN[6] ),
    .C(\DIN[4] ),
    .Y(_0460_)
  );
  AOAI211X0P5H7R _1094_ (
    .A0(\DIN[5] ),
    .A1(_0459_),
    .B0(_0460_),
    .C0(_0156_),
    .Y(_0461_)
  );
  OAI2BB1X0P5H7R _1095_ (
    .A0N(\DIN[3] ),
    .A1N(\DIN[4] ),
    .B0(_0461_),
    .Y(_0462_)
  );
  XNOR2X0P5H7R _1096_ (
    .A(\Noi.LenCtr_1_ ),
    .B(\Noi.LenCtr_0_ ),
    .Y(_0463_)
  );
  MUX2X0P5H7R _1097_ (
    .A(_0462_),
    .B(_0463_),
    .S0(_0456_),
    .Y(_0464_)
  );
  NAND3X1P4H7L _1098_ (
    .A(\Noi.Enabled ),
    .B(_0454_),
    .C(_0464_),
    .Y(_0465_)
  );
  AOI21X0P5H7R _1099_ (
    .A0(_0458_),
    .A1(_0465_),
    .B0(reset),
    .Y(_0087_)
  );
  NAND2BX0P7H7L _1100_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_2_ ),
    .Y(_0466_)
  );
  NOR2X0P5H7R _1101_ (
    .A(\DIN[5] ),
    .B(\DIN[3] ),
    .Y(_0467_)
  );
  NOR3BX1P4H7R _1102_ (
    .AN(\DIN[3] ),
    .B(\DIN[6] ),
    .C(\DIN[4] ),
    .Y(_0468_)
  );
  AOI21X0P5H7R _1103_ (
    .A0(\DIN[4] ),
    .A1(_0467_),
    .B0(_0468_),
    .Y(_0469_)
  );
  NAND4BX0P5H7R _1104_ (
    .AN(\DIN[6] ),
    .B(_0222_),
    .C(_0467_),
    .D(\DIN[7] ),
    .Y(_0470_)
  );
  NOR3BX0P5H7R _1105_ (
    .AN(\DIN[6] ),
    .B(\DIN[4] ),
    .C(\DIN[7] ),
    .Y(_0471_)
  );
  OAI21X0P5H7R _1106_ (
    .A0(\DIN[3] ),
    .A1(_0471_),
    .B0(\DIN[5] ),
    .Y(_0472_)
  );
  OAI211X1P4H7L _1107_ (
    .A0(\DIN[7] ),
    .A1(_0469_),
    .B0(_0470_),
    .C0(_0472_),
    .Y(_0473_)
  );
  NAND2BX0P5H7R _1108_ (
    .AN(_0473_),
    .B(_0449_),
    .Y(_0474_)
  );
  OR3X1H7R _1109_ (
    .A(\Noi.LenCtr_2_ ),
    .B(\Noi.LenCtr_1_ ),
    .C(\Noi.LenCtr_0_ ),
    .Y(_0475_)
  );
  OAI21X0P5H7R _1110_ (
    .A0(\Noi.LenCtr_1_ ),
    .A1(\Noi.LenCtr_0_ ),
    .B0(\Noi.LenCtr_2_ ),
    .Y(_0476_)
  );
  NAND3X0P5H7R _1111_ (
    .A(_0475_),
    .B(_0448_),
    .C(_0476_),
    .Y(_0477_)
  );
  NAND4X0P5H7R _1112_ (
    .A(\Noi.Enabled ),
    .B(_0453_),
    .C(_0474_),
    .D(_0477_),
    .Y(_0478_)
  );
  AOI21X0P5H7R _1113_ (
    .A0(_0466_),
    .A1(_0478_),
    .B0(reset),
    .Y(_0088_)
  );
  NAND2BX0P7H7L _1114_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_3_ ),
    .Y(_0479_)
  );
  AOI22X0P5H7R _1115_ (
    .A0(\DIN[5] ),
    .A1(\DIN[3] ),
    .B0(\DIN[4] ),
    .B1(_0156_),
    .Y(_0480_)
  );
  NAND3X0P5H7R _1116_ (
    .A(\DIN[6] ),
    .B(_0222_),
    .C(_0467_),
    .Y(_0481_)
  );
  NAND2BX0P5H7R _1117_ (
    .AN(\DIN[6] ),
    .B(\DIN[3] ),
    .Y(_0482_)
  );
  NAND2BX0P5H7R _1118_ (
    .AN(\DIN[3] ),
    .B(\DIN[5] ),
    .Y(_0483_)
  );
  OAI2BB1X0P5H7R _1119_ (
    .A0N(_0482_),
    .A1N(_0483_),
    .B0(\DIN[7] ),
    .Y(_0484_)
  );
  OAI211X1P4H7L _1120_ (
    .A0(\DIN[6] ),
    .A1(_0480_),
    .B0(_0481_),
    .C0(_0484_),
    .Y(_0485_)
  );
  XNOR2X0P5H7R _1121_ (
    .A(\Noi.LenCtr_3_ ),
    .B(_0445_),
    .Y(_0486_)
  );
  MUXI2X0P5H7R _1122_ (
    .A(_0485_),
    .B(_0486_),
    .S0(_0456_),
    .Y(_0487_)
  );
  NAND3X0P5H7R _1123_ (
    .A(\Noi.Enabled ),
    .B(_0454_),
    .C(_0487_),
    .Y(_0488_)
  );
  AOI21X0P5H7R _1124_ (
    .A0(_0479_),
    .A1(_0488_),
    .B0(reset),
    .Y(_0089_)
  );
  NAND2BX0P7H7L _1125_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_4_ ),
    .Y(_0489_)
  );
  OAI21X0P5H7R _1126_ (
    .A0(\Noi.LenCtr_3_ ),
    .A1(_0475_),
    .B0(\Noi.LenCtr_4_ ),
    .Y(_0490_)
  );
  NOR3X0P5H7R _1127_ (
    .A(\Noi.LenCtr_4_ ),
    .B(\Noi.LenCtr_3_ ),
    .C(_0475_),
    .Y(_0491_)
  );
  NOR3BX0P5H7R _1128_ (
    .AN(_0490_),
    .B(_0449_),
    .C(_0491_),
    .Y(_0492_)
  );
  NAND2X0P5H7R _1129_ (
    .A(\DIN[7] ),
    .B(\DIN[4] ),
    .Y(_0493_)
  );
  OAI2BB1X0P5H7R _1130_ (
    .A0N(\DIN[3] ),
    .A1N(_0222_),
    .B0(_0493_),
    .Y(_0494_)
  );
  NOR2X0P5H7R _1131_ (
    .A(\DIN[5] ),
    .B(\DIN[6] ),
    .Y(_0495_)
  );
  OAI21X0P5H7R _1132_ (
    .A0(\DIN[3] ),
    .A1(_0222_),
    .B0(_0156_),
    .Y(_0496_)
  );
  AO211X1P4H7L _1133_ (
    .A0(\DIN[5] ),
    .A1(_0222_),
    .B0(\DIN[3] ),
    .C0(_0156_),
    .Y(_0497_)
  );
  AOI22X0P5H7R _1134_ (
    .A0(_0494_),
    .A1(_0495_),
    .B0(_0496_),
    .B1(_0497_),
    .Y(_0498_)
  );
  NAND2X0P5H7R _1135_ (
    .A(_0449_),
    .B(_0498_),
    .Y(_0499_)
  );
  NAND4BX0P5H7R _1136_ (
    .AN(_0492_),
    .B(_0454_),
    .C(\Noi.Enabled ),
    .D(_0499_),
    .Y(_0500_)
  );
  AOI21X0P5H7R _1137_ (
    .A0(_0489_),
    .A1(_0500_),
    .B0(reset),
    .Y(_0090_)
  );
  NAND2BX0P5H7R _1138_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_5_ ),
    .Y(_0501_)
  );
  NOR2X0P5H7R _1139_ (
    .A(\DIN[7] ),
    .B(\DIN[5] ),
    .Y(_0502_)
  );
  OAOI211X0P5H7R _1140_ (
    .A0(\DIN[6] ),
    .A1(\DIN[4] ),
    .B0(_0493_),
    .C0(_0483_),
    .Y(_0503_)
  );
  OAOI211X0P5H7R _1141_ (
    .A0(_0459_),
    .A1(_0468_),
    .B0(_0502_),
    .C0(_0503_),
    .Y(_0504_)
  );
  NAND2X0P5H7R _1142_ (
    .A(_0449_),
    .B(_0504_),
    .Y(_0505_)
  );
  NOR3X0P5H7R _1143_ (
    .A(\Noi.LenCtr_4_ ),
    .B(\Noi.LenCtr_3_ ),
    .C(_0475_),
    .Y(_0506_)
  );
  XNOR2X0P5H7R _1144_ (
    .A(\Noi.LenCtr_5_ ),
    .B(_0506_),
    .Y(_0507_)
  );
  NAND2X0P5H7R _1145_ (
    .A(_0456_),
    .B(_0507_),
    .Y(_0508_)
  );
  NAND4X0P5H7R _1146_ (
    .A(\Noi.Enabled ),
    .B(_0453_),
    .C(_0505_),
    .D(_0508_),
    .Y(_0509_)
  );
  AOI21X0P5H7R _1147_ (
    .A0(_0501_),
    .A1(_0509_),
    .B0(reset),
    .Y(_0091_)
  );
  NAND2BX0P5H7R _1148_ (
    .AN(_0454_),
    .B(\Noi.LenCtr_6_ ),
    .Y(_0510_)
  );
  MUXI2X0P5H7R _1149_ (
    .A(_0459_),
    .B(_0468_),
    .S0(_0156_),
    .Y(_0511_)
  );
  OAI32X1P4H7L _1150_ (
    .A0(\DIN[6] ),
    .A1(_0222_),
    .A2(_0483_),
    .B0(_0511_),
    .B1(\DIN[5] ),
    .Y(_0512_)
  );
  NAND2BX0P5H7R _1151_ (
    .AN(_0512_),
    .B(_0449_),
    .Y(_0513_)
  );
  OAI2BB1X0P5H7R _1152_ (
    .A0N(_0445_),
    .A1N(_0446_),
    .B0(\Noi.LenCtr_6_ ),
    .Y(_0514_)
  );
  NAND3X0P5H7R _1153_ (
    .A(_0447_),
    .B(_0448_),
    .C(_0514_),
    .Y(_0515_)
  );
  NAND4X0P5H7R _1154_ (
    .A(\Noi.Enabled ),
    .B(_0453_),
    .C(_0513_),
    .D(_0515_),
    .Y(_0516_)
  );
  AOI21X0P5H7R _1155_ (
    .A0(_0510_),
    .A1(_0516_),
    .B0(reset),
    .Y(_0092_)
  );
  AOI2BB1X0P5H7R _1156_ (
    .A0N(\DIN[7] ),
    .A1N(_0482_),
    .B0(_0459_),
    .Y(_0517_)
  );
  NOR3X0P5H7R _1157_ (
    .A(\DIN[5] ),
    .B(\DIN[4] ),
    .C(_0517_),
    .Y(_0518_)
  );
  NOR2X0P5H7R _1158_ (
    .A(_0162_),
    .B(_0452_),
    .Y(_0519_)
  );
  NAND4X0P5H7R _1159_ (
    .A(\Noi.Enabled ),
    .B(_0449_),
    .C(_0518_),
    .D(_0519_),
    .Y(_0520_)
  );
  NAND3X0P5H7R _1160_ (
    .A(\Noi.Enabled ),
    .B(_0447_),
    .C(_0448_),
    .Y(_0521_)
  );
  OAI2BB1X0P5H7R _1161_ (
    .A0N(_0453_),
    .A1N(_0521_),
    .B0(\Noi.LenCtr_7_ ),
    .Y(_0522_)
  );
  AOI21X0P5H7R _1162_ (
    .A0(_0520_),
    .A1(_0522_),
    .B0(reset),
    .Y(_0093_)
  );
  NAND2BX0P5H7R _1163_ (
    .AN(_0439_),
    .B(\Sq1.Enabled ),
    .Y(_0523_)
  );
  NAND2X0P5H7R _1164_ (
    .A(\DIN[0] ),
    .B(_0439_),
    .Y(_0524_)
  );
  AOI21X0P5H7R _1165_ (
    .A0(_0523_),
    .A1(_0524_),
    .B0(reset),
    .Y(_0094_)
  );
  NAND3BBX0P5H7R _1166_ (
    .AN(\ADDR[4] ),
    .BN(\ADDR[2] ),
    .C(MW),
    .Y(_0525_)
  );
  NOR3X0P5H7R _1167_ (
    .A(\ADDR[3] ),
    .B(_0379_),
    .C(_0525_),
    .Y(_0526_)
  );
  MUXI2X0P5H7R _1168_ (
    .A(\Sq1.EnvLoop ),
    .B(\DIN[5] ),
    .S0(_0526_),
    .Y(_0527_)
  );
  NOR2X0P5H7R _1169_ (
    .A(reset),
    .B(_0527_),
    .Y(_0095_)
  );
  OR4X3H7L _1170_ (
    .A(\Sq1.LenCtr_3_ ),
    .B(\Sq1.LenCtr_2_ ),
    .C(\Sq1.LenCtr_1_ ),
    .D(\Sq1.LenCtr_0_ ),
    .Y(_0528_)
  );
  OR4X3H7L _1171_ (
    .A(\Sq1.LenCtr_6_ ),
    .B(\Sq1.LenCtr_5_ ),
    .C(\Sq1.LenCtr_4_ ),
    .D(_0528_),
    .Y(_0529_)
  );
  OR2X0P5H7L _1172_ (
    .A(\Sq1.LenCtr_7_ ),
    .B(_0529_),
    .Y(\DOUT[0] )
  );
  NOR2BX1P4H7L _1173_ (
    .AN(ClkL),
    .B(\Sq1.EnvLoop ),
    .Z(_0530_)
  );
  OAI21X4H7L _1174_ (
    .A0(\Sq1.LenCtr_7_ ),
    .A1(_0529_),
    .B0(_0530_),
    .Y(_0531_)
  );
  NOR3BX0P5H7R _1175_ (
    .AN(MW),
    .B(\ADDR[2] ),
    .C(\ADDR[4] ),
    .Y(_0532_)
  );
  NAND2X0P5H7R _1176_ (
    .A(_0216_),
    .B(_0532_),
    .Y(_0533_)
  );
  AO31X4H7L _1177_ (
    .A0(\Sq1.Enabled ),
    .A1(_0531_),
    .A2(_0533_),
    .B0(_0161_),
    .Y(_0534_)
  );
  NAND2X0P5H7R _1178_ (
    .A(ce),
    .B(\Sq1.Enabled ),
    .Y(_0535_)
  );
  NOR3X0P5H7R _1179_ (
    .A(\Sq1.LenCtr_0_ ),
    .B(_0531_),
    .C(_0535_),
    .Y(_0536_)
  );
  AOA211X0P5H7L _1180_ (
    .A0(\Sq1.LenCtr_0_ ),
    .A1(_0534_),
    .B0(_0536_),
    .C0(_0166_),
    .Y(_0096_)
  );
  BUFX5H7L _1181_ (
    .A(_0534_),
    .Y(_0537_)
  );
  XOR2X0P5H7R _1182_ (
    .A(\Sq1.LenCtr_1_ ),
    .B(\Sq1.LenCtr_0_ ),
    .Y(_0538_)
  );
  NOR2X0P5H7R _1183_ (
    .A(_0531_),
    .B(_0538_),
    .Y(_0539_)
  );
  AOAI211X0P5H7R _1184_ (
    .A0(_0462_),
    .A1(_0531_),
    .B0(_0539_),
    .C0(\Sq1.Enabled ),
    .Y(_0540_)
  );
  NAND2X1P4H7L _1185_ (
    .A(\Sq1.LenCtr_1_ ),
    .B(_0537_),
    .Y(_0541_)
  );
  OAOI211X0P5H7R _1186_ (
    .A0(_0537_),
    .A1(_0540_),
    .B0(_0541_),
    .C0(reset),
    .Y(_0097_)
  );
  OA21X0P7H7L _1187_ (
    .A0(\Sq1.LenCtr_7_ ),
    .A1(_0529_),
    .B0(_0530_),
    .Y(_0542_)
  );
  OR3X1H7R _1188_ (
    .A(\Sq1.LenCtr_2_ ),
    .B(\Sq1.LenCtr_1_ ),
    .C(\Sq1.LenCtr_0_ ),
    .Y(_0543_)
  );
  OAI21X0P5H7R _1189_ (
    .A0(\Sq1.LenCtr_1_ ),
    .A1(\Sq1.LenCtr_0_ ),
    .B0(\Sq1.LenCtr_2_ ),
    .Y(_0544_)
  );
  NAND3X0P5H7R _1190_ (
    .A(_0543_),
    .B(_0542_),
    .C(_0544_),
    .Y(_0545_)
  );
  OAI211X0P7H7L _1191_ (
    .A0(_0473_),
    .A1(_0542_),
    .B0(_0545_),
    .C0(\Sq1.Enabled ),
    .Y(_0546_)
  );
  NAND2X0P7H7L _1192_ (
    .A(\Sq1.LenCtr_2_ ),
    .B(_0537_),
    .Y(_0547_)
  );
  OAOI211X0P5H7R _1193_ (
    .A0(_0537_),
    .A1(_0546_),
    .B0(_0547_),
    .C0(reset),
    .Y(_0098_)
  );
  NAND2X0P5H7R _1194_ (
    .A(_0485_),
    .B(_0531_),
    .Y(_0548_)
  );
  OAI31X0P5H7R _1195_ (
    .A0(\Sq1.LenCtr_2_ ),
    .A1(\Sq1.LenCtr_1_ ),
    .A2(\Sq1.LenCtr_0_ ),
    .B0(\Sq1.LenCtr_3_ ),
    .Y(_0549_)
  );
  NAND3X0P5H7R _1196_ (
    .A(_0528_),
    .B(_0530_),
    .C(_0549_),
    .Y(_0550_)
  );
  NAND3X0P5H7R _1197_ (
    .A(\Sq1.Enabled ),
    .B(_0548_),
    .C(_0550_),
    .Y(_0551_)
  );
  NAND2X1P4H7L _1198_ (
    .A(\Sq1.LenCtr_3_ ),
    .B(_0537_),
    .Y(_0552_)
  );
  OAOI211X0P5H7R _1199_ (
    .A0(_0537_),
    .A1(_0551_),
    .B0(_0552_),
    .C0(reset),
    .Y(_0099_)
  );
  XOR2X0P5H7R _1200_ (
    .A(\Sq1.LenCtr_4_ ),
    .B(_0528_),
    .Y(_0553_)
  );
  NOR2X0P5H7R _1201_ (
    .A(_0531_),
    .B(_0553_),
    .Y(_0554_)
  );
  NOR3X1P4H7L _1202_ (
    .A(_0498_),
    .B(_0542_),
    .C(_0533_),
    .Y(_0555_)
  );
  OAI211X1P4H7L _1203_ (
    .A0(_0554_),
    .A1(_0555_),
    .B0(ce),
    .C0(\Sq1.Enabled ),
    .Y(_0556_)
  );
  NAND2X0P5H7R _1204_ (
    .A(\Sq1.LenCtr_4_ ),
    .B(_0534_),
    .Y(_0557_)
  );
  AOI21X0P5H7R _1205_ (
    .A0(_0556_),
    .A1(_0557_),
    .B0(reset),
    .Y(_0100_)
  );
  OR3X1H7R _1206_ (
    .A(\Sq1.LenCtr_5_ ),
    .B(\Sq1.LenCtr_4_ ),
    .C(_0528_),
    .Y(_0558_)
  );
  OAI21X0P5H7R _1207_ (
    .A0(\Sq1.LenCtr_4_ ),
    .A1(_0528_),
    .B0(\Sq1.LenCtr_5_ ),
    .Y(_0559_)
  );
  NAND3X0P5H7R _1208_ (
    .A(_0530_),
    .B(_0558_),
    .C(_0559_),
    .Y(_0560_)
  );
  NAND2X0P5H7R _1209_ (
    .A(\Sq1.Enabled ),
    .B(_0560_),
    .Y(_0561_)
  );
  AOI211X0P5H7R _1210_ (
    .A0(_0504_),
    .A1(_0531_),
    .B0(_0534_),
    .C0(_0561_),
    .Y(_0562_)
  );
  AOA211X0P5H7L _1211_ (
    .A0(\Sq1.LenCtr_5_ ),
    .A1(_0534_),
    .B0(_0562_),
    .C0(_0166_),
    .Y(_0101_)
  );
  OAI31X0P5H7R _1212_ (
    .A0(\Sq1.LenCtr_5_ ),
    .A1(\Sq1.LenCtr_4_ ),
    .A2(_0528_),
    .B0(\Sq1.LenCtr_6_ ),
    .Y(_0563_)
  );
  NAND3X0P5H7R _1213_ (
    .A(_0529_),
    .B(_0530_),
    .C(_0563_),
    .Y(_0564_)
  );
  OAI211X0P7H7R _1214_ (
    .A0(_0512_),
    .A1(_0542_),
    .B0(_0564_),
    .C0(\Sq1.Enabled ),
    .Y(_0565_)
  );
  NAND2X1P4H7L _1215_ (
    .A(\Sq1.LenCtr_6_ ),
    .B(_0537_),
    .Y(_0566_)
  );
  OAOI211X0P5H7R _1216_ (
    .A0(_0537_),
    .A1(_0565_),
    .B0(_0566_),
    .C0(reset),
    .Y(_0102_)
  );
  AND3X0P5H7R _1217_ (
    .A(\Sq1.LenCtr_7_ ),
    .B(_0529_),
    .C(_0530_),
    .Y(_0567_)
  );
  AOAI211X0P5H7R _1218_ (
    .A0(_0518_),
    .A1(_0531_),
    .B0(_0567_),
    .C0(\Sq1.Enabled ),
    .Y(_0568_)
  );
  NAND2X1P4H7L _1219_ (
    .A(\Sq1.LenCtr_7_ ),
    .B(_0537_),
    .Y(_0569_)
  );
  OAOI211X0P5H7R _1220_ (
    .A0(_0537_),
    .A1(_0568_),
    .B0(_0569_),
    .C0(reset),
    .Y(_0103_)
  );
  NAND2BX0P5H7R _1221_ (
    .AN(_0439_),
    .B(\Sq2.Enabled ),
    .Y(_0570_)
  );
  NAND2X0P5H7R _1222_ (
    .A(\DIN[1] ),
    .B(_0439_),
    .Y(_0571_)
  );
  AOI21X0P5H7R _1223_ (
    .A0(_0570_),
    .A1(_0571_),
    .B0(reset),
    .Y(_0104_)
  );
  NOR3X0P5H7R _1224_ (
    .A(\ADDR[3] ),
    .B(_0379_),
    .C(_0442_),
    .Y(_0572_)
  );
  MUXI2X0P5H7R _1225_ (
    .A(\Sq2.EnvLoop ),
    .B(\DIN[5] ),
    .S0(_0572_),
    .Y(_0573_)
  );
  NOR2X0P5H7R _1226_ (
    .A(reset),
    .B(_0573_),
    .Y(_0105_)
  );
  OR4X1P4H7L _1227_ (
    .A(\Sq2.LenCtr_3_ ),
    .B(\Sq2.LenCtr_2_ ),
    .C(\Sq2.LenCtr_1_ ),
    .D(\Sq2.LenCtr_0_ ),
    .Y(_0574_)
  );
  OR4X3H7L _1228_ (
    .A(\Sq2.LenCtr_6_ ),
    .B(\Sq2.LenCtr_5_ ),
    .C(\Sq2.LenCtr_4_ ),
    .D(_0574_),
    .Y(_0575_)
  );
  OR2X0P5H7L _1229_ (
    .A(\Sq2.LenCtr_7_ ),
    .B(_0575_),
    .Y(\DOUT[1] )
  );
  NOR2BX1P4H7L _1230_ (
    .AN(ClkL),
    .B(\Sq2.EnvLoop ),
    .Z(_0576_)
  );
  OAI21X4H7L _1231_ (
    .A0(\Sq2.LenCtr_7_ ),
    .A1(_0575_),
    .B0(_0576_),
    .Y(_0577_)
  );
  OR3X1H7R _1232_ (
    .A(\ADDR[3] ),
    .B(_0158_),
    .C(_0442_),
    .Y(_0578_)
  );
  AO31X3H7L _1233_ (
    .A0(\Sq2.Enabled ),
    .A1(_0577_),
    .A2(_0578_),
    .B0(_0161_),
    .Y(_0579_)
  );
  NAND2X0P5H7R _1234_ (
    .A(\Sq2.LenCtr_0_ ),
    .B(_0579_),
    .Y(_0580_)
  );
  OA21X1P4H7L _1235_ (
    .A0(\Sq2.LenCtr_7_ ),
    .A1(_0575_),
    .B0(_0576_),
    .Y(_0581_)
  );
  NAND4BX0P5H7R _1236_ (
    .AN(\Sq2.LenCtr_0_ ),
    .B(\Sq2.Enabled ),
    .C(_0581_),
    .D(ce),
    .Y(_0582_)
  );
  AOI21X0P5H7R _1237_ (
    .A0(_0580_),
    .A1(_0582_),
    .B0(reset),
    .Y(_0106_)
  );
  BUFX5H7L _1238_ (
    .A(_0579_),
    .Y(_0583_)
  );
  XOR2X0P5H7R _1239_ (
    .A(\Sq2.LenCtr_1_ ),
    .B(\Sq2.LenCtr_0_ ),
    .Y(_0584_)
  );
  NOR2X0P5H7R _1240_ (
    .A(_0577_),
    .B(_0584_),
    .Y(_0585_)
  );
  AOAI211X0P5H7R _1241_ (
    .A0(_0462_),
    .A1(_0577_),
    .B0(_0585_),
    .C0(\Sq2.Enabled ),
    .Y(_0586_)
  );
  NAND2X1P4H7L _1242_ (
    .A(\Sq2.LenCtr_1_ ),
    .B(_0583_),
    .Y(_0587_)
  );
  OAOI211X0P5H7R _1243_ (
    .A0(_0583_),
    .A1(_0586_),
    .B0(_0587_),
    .C0(reset),
    .Y(_0107_)
  );
  OR3X1H7R _1244_ (
    .A(\Sq2.LenCtr_2_ ),
    .B(\Sq2.LenCtr_1_ ),
    .C(\Sq2.LenCtr_0_ ),
    .Y(_0588_)
  );
  OAI21X0P5H7R _1245_ (
    .A0(\Sq2.LenCtr_1_ ),
    .A1(\Sq2.LenCtr_0_ ),
    .B0(\Sq2.LenCtr_2_ ),
    .Y(_0589_)
  );
  NAND3X0P5H7R _1246_ (
    .A(_0588_),
    .B(_0581_),
    .C(_0589_),
    .Y(_0590_)
  );
  OAI211X0P7H7R _1247_ (
    .A0(_0473_),
    .A1(_0581_),
    .B0(_0590_),
    .C0(\Sq2.Enabled ),
    .Y(_0591_)
  );
  NAND2X1P4H7L _1248_ (
    .A(\Sq2.LenCtr_2_ ),
    .B(_0583_),
    .Y(_0592_)
  );
  OAOI211X1H7L _1249_ (
    .A0(_0583_),
    .A1(_0591_),
    .B0(_0592_),
    .C0(reset),
    .Y(_0108_)
  );
  NAND2X0P5H7R _1250_ (
    .A(_0485_),
    .B(_0577_),
    .Y(_0593_)
  );
  OAI31X0P5H7R _1251_ (
    .A0(\Sq2.LenCtr_2_ ),
    .A1(\Sq2.LenCtr_1_ ),
    .A2(\Sq2.LenCtr_0_ ),
    .B0(\Sq2.LenCtr_3_ ),
    .Y(_0594_)
  );
  NAND3X0P5H7R _1252_ (
    .A(_0574_),
    .B(_0576_),
    .C(_0594_),
    .Y(_0595_)
  );
  NAND3X0P5H7R _1253_ (
    .A(\Sq2.Enabled ),
    .B(_0593_),
    .C(_0595_),
    .Y(_0596_)
  );
  NAND2X1P4H7L _1254_ (
    .A(\Sq2.LenCtr_3_ ),
    .B(_0583_),
    .Y(_0597_)
  );
  OAOI211X0P5H7R _1255_ (
    .A0(_0583_),
    .A1(_0596_),
    .B0(_0597_),
    .C0(reset),
    .Y(_0109_)
  );
  NOR2X0P5H7R _1256_ (
    .A(\Sq2.LenCtr_4_ ),
    .B(_0574_),
    .Y(_0598_)
  );
  AND2X1H7R _1257_ (
    .A(\Sq2.LenCtr_4_ ),
    .B(_0574_),
    .Y(_0599_)
  );
  AOI2BB1X0P5H7R _1258_ (
    .A0N(_0598_),
    .A1N(_0599_),
    .B0(_0577_),
    .Y(_0600_)
  );
  NOR3X1P4H7L _1259_ (
    .A(_0498_),
    .B(_0581_),
    .C(_0578_),
    .Y(_0601_)
  );
  OAI211X1P4H7L _1260_ (
    .A0(_0600_),
    .A1(_0601_),
    .B0(ce),
    .C0(\Sq2.Enabled ),
    .Y(_0602_)
  );
  NAND2X0P5H7R _1261_ (
    .A(\Sq2.LenCtr_4_ ),
    .B(_0579_),
    .Y(_0603_)
  );
  AOI21X0P5H7R _1262_ (
    .A0(_0602_),
    .A1(_0603_),
    .B0(reset),
    .Y(_0110_)
  );
  XNOR2X0P5H7R _1263_ (
    .A(\Sq2.LenCtr_5_ ),
    .B(_0598_),
    .Y(_0604_)
  );
  OAI2BB1X0P5H7R _1264_ (
    .A0N(_0576_),
    .A1N(_0604_),
    .B0(\Sq2.Enabled ),
    .Y(_0605_)
  );
  AOI211X0P5H7R _1265_ (
    .A0(_0504_),
    .A1(_0577_),
    .B0(_0579_),
    .C0(_0605_),
    .Y(_0606_)
  );
  AOA211X0P5H7L _1266_ (
    .A0(\Sq2.LenCtr_5_ ),
    .A1(_0579_),
    .B0(_0606_),
    .C0(_0166_),
    .Y(_0111_)
  );
  OAI31X0P5H7R _1267_ (
    .A0(\Sq2.LenCtr_5_ ),
    .A1(\Sq2.LenCtr_4_ ),
    .A2(_0574_),
    .B0(\Sq2.LenCtr_6_ ),
    .Y(_0607_)
  );
  NAND3X0P5H7R _1268_ (
    .A(_0575_),
    .B(_0576_),
    .C(_0607_),
    .Y(_0608_)
  );
  OAI211X0P7H7R _1269_ (
    .A0(_0512_),
    .A1(_0581_),
    .B0(_0608_),
    .C0(\Sq2.Enabled ),
    .Y(_0609_)
  );
  NAND2X1P4H7L _1270_ (
    .A(\Sq2.LenCtr_6_ ),
    .B(_0583_),
    .Y(_0610_)
  );
  OAOI211X0P5H7R _1271_ (
    .A0(_0583_),
    .A1(_0609_),
    .B0(_0610_),
    .C0(reset),
    .Y(_0112_)
  );
  AND3X0P5H7R _1272_ (
    .A(\Sq2.LenCtr_7_ ),
    .B(_0575_),
    .C(_0576_),
    .Y(_0611_)
  );
  AOAI211X0P5H7R _1273_ (
    .A0(_0518_),
    .A1(_0577_),
    .B0(_0611_),
    .C0(\Sq2.Enabled ),
    .Y(_0612_)
  );
  NAND2X1P4H7L _1274_ (
    .A(\Sq2.LenCtr_7_ ),
    .B(_0583_),
    .Y(_0613_)
  );
  OAOI211X0P5H7R _1275_ (
    .A0(_0583_),
    .A1(_0612_),
    .B0(_0613_),
    .C0(reset),
    .Y(_0113_)
  );
  NAND2BX0P5H7R _1276_ (
    .AN(_0439_),
    .B(\Tri.Enabled ),
    .Y(_0614_)
  );
  NAND2X0P5H7R _1277_ (
    .A(\DIN[2] ),
    .B(_0439_),
    .Y(_0615_)
  );
  AOI21X0P5H7R _1278_ (
    .A0(_0614_),
    .A1(_0615_),
    .B0(reset),
    .Y(_0114_)
  );
  OR3X1P4H7L _1279_ (
    .A(\Tri.LenCtr_2_ ),
    .B(\Tri.LenCtr_1_ ),
    .C(\Tri.LenCtr_0_ ),
    .Y(_0616_)
  );
  OR4X3H7L _1280_ (
    .A(\Tri.LenCtr_5_ ),
    .B(\Tri.LenCtr_4_ ),
    .C(\Tri.LenCtr_3_ ),
    .D(_0616_),
    .Y(_0617_)
  );
  OR3X1H7R _1281_ (
    .A(\Tri.LenCtr_7_ ),
    .B(\Tri.LenCtr_6_ ),
    .C(_0617_),
    .Y(\DOUT[2] )
  );
  NAND4X0P5H7R _1282_ (
    .A(ce),
    .B(\ADDR[3] ),
    .C(_0378_),
    .D(_0532_),
    .Y(_0618_)
  );
  NAND2X0P5H7R _1283_ (
    .A(\Tri.LenCtrHalt ),
    .B(_0618_),
    .Y(_0619_)
  );
  OAOI211X0P5H7R _1284_ (
    .A0(_0156_),
    .A1(_0618_),
    .B0(_0619_),
    .C0(reset),
    .Y(_0115_)
  );
  NOR2BX1P4H7L _1285_ (
    .AN(ClkL),
    .B(\Tri.LenCtrHalt ),
    .Z(_0620_)
  );
  OAI31X4H7L _1286_ (
    .A0(\Tri.LenCtr_7_ ),
    .A1(\Tri.LenCtr_6_ ),
    .A2(_0617_),
    .B0(_0620_),
    .Y(_0621_)
  );
  NAND2BX1H7L _1287_ (
    .AN(_0450_),
    .B(_0532_),
    .Y(_0622_)
  );
  AOI31X4H7L _1288_ (
    .A0(\Tri.Enabled ),
    .A1(_0621_),
    .A2(_0622_),
    .B0(_0161_),
    .Y(_0623_)
  );
  NAND2X0P5H7R _1289_ (
    .A(ce),
    .B(\Tri.Enabled ),
    .Y(_0624_)
  );
  NOR3X0P5H7R _1290_ (
    .A(\Tri.LenCtr_0_ ),
    .B(_0621_),
    .C(_0624_),
    .Y(_0625_)
  );
  AOI2XB1X1H7L _1291_ (
    .A0(\Tri.LenCtr_0_ ),
    .A1N(_0623_),
    .B0(_0625_),
    .Y(_0626_)
  );
  NOR2X0P5H7R _1292_ (
    .A(reset),
    .B(_0626_),
    .Y(_0116_)
  );
  NOR3X0P5H7R _1293_ (
    .A(_0162_),
    .B(\Tri.LenCtr_1_ ),
    .C(\Tri.LenCtr_0_ ),
    .Y(_0627_)
  );
  OA31X1P4H7L _1294_ (
    .A0(\Tri.LenCtr_7_ ),
    .A1(\Tri.LenCtr_6_ ),
    .A2(_0617_),
    .B0(_0620_),
    .Y(_0628_)
  );
  AOAI211X0P5H7R _1295_ (
    .A0(\Tri.LenCtr_1_ ),
    .A1(\Tri.LenCtr_0_ ),
    .B0(_0627_),
    .C0(_0628_),
    .Y(_0629_)
  );
  NOR2X0P5H7R _1296_ (
    .A(_0450_),
    .B(_0525_),
    .Y(_0630_)
  );
  NAND4X1H7R _1297_ (
    .A(ce),
    .B(_0462_),
    .C(_0621_),
    .D(_0630_),
    .Y(_0631_)
  );
  OAI2BB1X1P4H7L _1298_ (
    .A0N(_0629_),
    .A1N(_0631_),
    .B0(\Tri.Enabled ),
    .Y(_0632_)
  );
  NAND2BX0P5H7R _1299_ (
    .AN(_0623_),
    .B(\Tri.LenCtr_1_ ),
    .Y(_0633_)
  );
  AOI21X0P7H7L _1300_ (
    .A0(_0632_),
    .A1(_0633_),
    .B0(reset),
    .Y(_0117_)
  );
  INVX0P5H7R _1301_ (
    .A(\Tri.LenCtr_2_ ),
    .Y(_0634_)
  );
  OAI21X0P5H7R _1302_ (
    .A0(\Tri.LenCtr_1_ ),
    .A1(\Tri.LenCtr_0_ ),
    .B0(\Tri.LenCtr_2_ ),
    .Y(_0635_)
  );
  NAND3X0P5H7R _1303_ (
    .A(_0616_),
    .B(_0620_),
    .C(_0635_),
    .Y(_0636_)
  );
  OAI211X1P4H7L _1304_ (
    .A0(_0473_),
    .A1(_0628_),
    .B0(_0636_),
    .C0(\Tri.Enabled ),
    .Y(_0637_)
  );
  MUX2X1P4H7L _1305_ (
    .A(_0634_),
    .B(_0637_),
    .S0(_0623_),
    .Y(_0638_)
  );
  NOR2X0P7H7L _1306_ (
    .A(reset),
    .B(_0638_),
    .Y(_0118_)
  );
  NAND2BX1H7L _1307_ (
    .AN(_0623_),
    .B(\Tri.LenCtr_3_ ),
    .Y(_0639_)
  );
  NAND2X0P5H7R _1308_ (
    .A(_0485_),
    .B(_0621_),
    .Y(_0640_)
  );
  NOR2X0P5H7R _1309_ (
    .A(\Tri.LenCtr_3_ ),
    .B(_0616_),
    .Y(_0641_)
  );
  NAND2X0P5H7R _1310_ (
    .A(\Tri.LenCtr_3_ ),
    .B(_0616_),
    .Y(_0642_)
  );
  NAND3BX0P5H7R _1311_ (
    .AN(_0641_),
    .B(_0642_),
    .C(_0628_),
    .Y(_0643_)
  );
  NAND4X0P5H7R _1312_ (
    .A(\Tri.Enabled ),
    .B(_0623_),
    .C(_0640_),
    .D(_0643_),
    .Y(_0644_)
  );
  AOI21X0P7H7L _1313_ (
    .A0(_0639_),
    .A1(_0644_),
    .B0(reset),
    .Y(_0119_)
  );
  XOR2X0P5H7R _1314_ (
    .A(\Tri.LenCtr_4_ ),
    .B(_0641_),
    .Y(_0645_)
  );
  NOR3X0P5H7R _1315_ (
    .A(_0498_),
    .B(_0628_),
    .C(_0622_),
    .Y(_0646_)
  );
  AOI21X1P4H7L _1316_ (
    .A0(_0628_),
    .A1(_0645_),
    .B0(_0646_),
    .Y(_0647_)
  );
  NAND2BX0P5H7R _1317_ (
    .AN(_0623_),
    .B(\Tri.LenCtr_4_ ),
    .Y(_0648_)
  );
  OAOI211X0P5H7L _1318_ (
    .A0(_0624_),
    .A1(_0647_),
    .B0(_0648_),
    .C0(reset),
    .Y(_0120_)
  );
  NOR3X0P5H7R _1319_ (
    .A(\Tri.LenCtr_4_ ),
    .B(\Tri.LenCtr_3_ ),
    .C(_0616_),
    .Y(_0649_)
  );
  NAND2X0P5H7R _1320_ (
    .A(_0620_),
    .B(_0649_),
    .Y(_0650_)
  );
  OAI211X0P7H7R _1321_ (
    .A0(_0620_),
    .A1(_0622_),
    .B0(_0650_),
    .C0(\Tri.Enabled ),
    .Y(_0651_)
  );
  OAI2BB1X0P5H7R _1322_ (
    .A0N(ce),
    .A1N(_0651_),
    .B0(\Tri.LenCtr_5_ ),
    .Y(_0652_)
  );
  NOR2X0P5H7R _1323_ (
    .A(_0617_),
    .B(_0621_),
    .Y(_0653_)
  );
  NOR3X0P5H7R _1324_ (
    .A(_0504_),
    .B(_0628_),
    .C(_0622_),
    .Y(_0654_)
  );
  OAI211X1P4H7L _1325_ (
    .A0(_0653_),
    .A1(_0654_),
    .B0(ce),
    .C0(\Tri.Enabled ),
    .Y(_0655_)
  );
  AOI21X0P5H7R _1326_ (
    .A0(_0652_),
    .A1(_0655_),
    .B0(reset),
    .Y(_0121_)
  );
  NOR3X0P5H7R _1327_ (
    .A(\Tri.LenCtr_6_ ),
    .B(_0617_),
    .C(_0621_),
    .Y(_0656_)
  );
  AOI31X0P5H7R _1328_ (
    .A0(_0512_),
    .A1(_0621_),
    .A2(_0630_),
    .B0(_0656_),
    .Y(_0657_)
  );
  NAND3X0P5H7R _1329_ (
    .A(\Tri.Enabled ),
    .B(_0617_),
    .C(_0620_),
    .Y(_0658_)
  );
  OAI2BB1X1P4H7L _1330_ (
    .A0N(_0623_),
    .A1N(_0658_),
    .B0(\Tri.LenCtr_6_ ),
    .Y(_0659_)
  );
  OAOI211X0P5H7R _1331_ (
    .A0(_0624_),
    .A1(_0657_),
    .B0(_0659_),
    .C0(reset),
    .Y(_0122_)
  );
  OAI211X0P7H7R _1332_ (
    .A0(\Tri.LenCtr_6_ ),
    .A1(_0617_),
    .B0(_0620_),
    .C0(\Tri.Enabled ),
    .Y(_0660_)
  );
  NAND2X0P5H7R _1333_ (
    .A(\Tri.LenCtr_7_ ),
    .B(_0166_),
    .Y(_0661_)
  );
  NOR3X0P5H7R _1334_ (
    .A(reset),
    .B(_0622_),
    .C(_0624_),
    .Y(_0662_)
  );
  NAND3X0P5H7R _1335_ (
    .A(_0518_),
    .B(_0621_),
    .C(_0662_),
    .Y(_0663_)
  );
  AOAI211X0P5H7R _1336_ (
    .A0(_0623_),
    .A1(_0660_),
    .B0(_0661_),
    .C0(_0663_),
    .Y(_0123_)
  );
  NOR2BX1H7L _1337_ (
    .AN(odd_or_even),
    .B(_0217_),
    .Z(_0664_)
  );
  AOA211X0P7H7L _1338_ (
    .A0(_0162_),
    .A1(Wrote4017),
    .B0(_0664_),
    .C0(_0166_),
    .Y(_0124_)
  );
  XNOR2X0P5H7R _1339_ (
    .A(odd_or_even),
    .B(ce),
    .Y(_0665_)
  );
  NOR2X0P5H7R _1340_ (
    .A(reset),
    .B(_0665_),
    .Y(_0125_)
  );
  TIEHIH7R _1341_ (
    .Z(_0666_)
  );
  TIELOH7R _1342_ (
    .Z(_0667_)
  );
  DFFQX1H7R ClkL_reg_p (
    .CK(clk),
    .D(_0000_),
    .Q(ClkL)
  );
  DFFQX1H7R Cycles_0__reg_p (
    .CK(clk),
    .D(_0001_),
    .Q(Cycles_0_)
  );
  DFFQX1H7R Cycles_10__reg_p (
    .CK(clk),
    .D(_0002_),
    .Q(Cycles_10_)
  );
  DFFQX1H7R Cycles_11__reg_p (
    .CK(clk),
    .D(_0003_),
    .Q(Cycles_11_)
  );
  DFFQX1H7R Cycles_12__reg_p (
    .CK(clk),
    .D(_0004_),
    .Q(Cycles_12_)
  );
  DFFQX1H7R Cycles_13__reg_p (
    .CK(clk),
    .D(_0005_),
    .Q(Cycles_13_)
  );
  DFFQX1H7R Cycles_14__reg_p (
    .CK(clk),
    .D(_0006_),
    .Q(Cycles_14_)
  );
  DFFQX1H7R Cycles_15__reg_p (
    .CK(clk),
    .D(_0007_),
    .Q(Cycles_15_)
  );
  DFFQX1H7R Cycles_1__reg_p (
    .CK(clk),
    .D(_0008_),
    .Q(Cycles_1_)
  );
  DFFQX1H7R Cycles_2__reg_p (
    .CK(clk),
    .D(_0009_),
    .Q(Cycles_2_)
  );
  DFFQX1H7R Cycles_3__reg_p (
    .CK(clk),
    .D(_0010_),
    .Q(Cycles_3_)
  );
  DFFQX1H7R Cycles_4__reg_p (
    .CK(clk),
    .D(_0011_),
    .Q(Cycles_4_)
  );
  DFFQX1H7R Cycles_5__reg_p (
    .CK(clk),
    .D(_0012_),
    .Q(Cycles_5_)
  );
  DFFQX1H7R Cycles_6__reg_p (
    .CK(clk),
    .D(_0013_),
    .Q(Cycles_6_)
  );
  DFFQX1H7R Cycles_7__reg_p (
    .CK(clk),
    .D(_0014_),
    .Q(Cycles_7_)
  );
  DFFQX1H7R Cycles_8__reg_p (
    .CK(clk),
    .D(_0015_),
    .Q(Cycles_8_)
  );
  DFFQX1H7R Cycles_9__reg_p (
    .CK(clk),
    .D(_0016_),
    .Q(Cycles_9_)
  );
  DFFQX1H7R DisableFrameInterrupt_reg_p (
    .CK(clk),
    .D(_0017_),
    .Q(DisableFrameInterrupt)
  );
  DFFQX1H7R \DmaAddr[0]_reg_p  (
    .CK(clk),
    .D(_0018_),
    .Q(\DmaAddr[0] )
  );
  DFFQX1H7R \DmaAddr[10]_reg_p  (
    .CK(clk),
    .D(_0019_),
    .Q(\DmaAddr[10] )
  );
  DFFQX1H7R \DmaAddr[11]_reg_p  (
    .CK(clk),
    .D(_0020_),
    .Q(\DmaAddr[11] )
  );
  DFFQX1H7R \DmaAddr[12]_reg_p  (
    .CK(clk),
    .D(_0021_),
    .Q(\DmaAddr[12] )
  );
  DFFQX1H7R \DmaAddr[13]_reg_p  (
    .CK(clk),
    .D(_0022_),
    .Q(\DmaAddr[13] )
  );
  DFFQX1H7R \DmaAddr[14]_reg_p  (
    .CK(clk),
    .D(_0023_),
    .Q(\DmaAddr[14] )
  );
  DFFQX1H7R \DmaAddr[1]_reg_p  (
    .CK(clk),
    .D(_0024_),
    .Q(\DmaAddr[1] )
  );
  DFFQX1H7R \DmaAddr[2]_reg_p  (
    .CK(clk),
    .D(_0025_),
    .Q(\DmaAddr[2] )
  );
  DFFQX1H7R \DmaAddr[3]_reg_p  (
    .CK(clk),
    .D(_0026_),
    .Q(\DmaAddr[3] )
  );
  DFFQX1H7R \DmaAddr[4]_reg_p  (
    .CK(clk),
    .D(_0027_),
    .Q(\DmaAddr[4] )
  );
  DFFQX1H7R \DmaAddr[5]_reg_p  (
    .CK(clk),
    .D(_0028_),
    .Q(\DmaAddr[5] )
  );
  DFFQX1H7R \DmaAddr[6]_reg_p  (
    .CK(clk),
    .D(_0029_),
    .Q(\DmaAddr[6] )
  );
  DFFQX1H7R \DmaAddr[7]_reg_p  (
    .CK(clk),
    .D(_0030_),
    .Q(\DmaAddr[7] )
  );
  DFFQX1H7R \DmaAddr[8]_reg_p  (
    .CK(clk),
    .D(_0031_),
    .Q(\DmaAddr[8] )
  );
  DFFQX1H7R \DmaAddr[9]_reg_p  (
    .CK(clk),
    .D(_0032_),
    .Q(\DmaAddr[9] )
  );
  DFFQX1H7R \Dmc.ActivationDelay_0__reg_p  (
    .CK(clk),
    .D(_0033_),
    .Q(\Dmc.ActivationDelay_0_ )
  );
  DFFQX1H7R \Dmc.ActivationDelay_1__reg_p  (
    .CK(clk),
    .D(_0034_),
    .Q(\Dmc.ActivationDelay_1_ )
  );
  DFFQX1H7R \Dmc.BitsUsed_0__reg_p  (
    .CK(clk),
    .D(_0035_),
    .Q(\Dmc.BitsUsed_0_ )
  );
  DFFQX1H7R \Dmc.BitsUsed_1__reg_p  (
    .CK(clk),
    .D(_0036_),
    .Q(\Dmc.BitsUsed_1_ )
  );
  DFFQX1H7R \Dmc.BitsUsed_2__reg_p  (
    .CK(clk),
    .D(_0037_),
    .Q(\Dmc.BitsUsed_2_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_0__reg_p  (
    .CK(clk),
    .D(_0038_),
    .Q(\Dmc.BytesLeft_0_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_10__reg_p  (
    .CK(clk),
    .D(_0039_),
    .Q(\Dmc.BytesLeft_10_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_11__reg_p  (
    .CK(clk),
    .D(_0040_),
    .Q(\Dmc.BytesLeft_11_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_1__reg_p  (
    .CK(clk),
    .D(_0041_),
    .Q(\Dmc.BytesLeft_1_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_2__reg_p  (
    .CK(clk),
    .D(_0042_),
    .Q(\Dmc.BytesLeft_2_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_3__reg_p  (
    .CK(clk),
    .D(_0043_),
    .Q(\Dmc.BytesLeft_3_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_4__reg_p  (
    .CK(clk),
    .D(_0044_),
    .Q(\Dmc.BytesLeft_4_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_5__reg_p  (
    .CK(clk),
    .D(_0045_),
    .Q(\Dmc.BytesLeft_5_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_6__reg_p  (
    .CK(clk),
    .D(_0046_),
    .Q(\Dmc.BytesLeft_6_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_7__reg_p  (
    .CK(clk),
    .D(_0047_),
    .Q(\Dmc.BytesLeft_7_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_8__reg_p  (
    .CK(clk),
    .D(_0048_),
    .Q(\Dmc.BytesLeft_8_ )
  );
  DFFQX1H7R \Dmc.BytesLeft_9__reg_p  (
    .CK(clk),
    .D(_0049_),
    .Q(\Dmc.BytesLeft_9_ )
  );
  DFFQX1H7R \Dmc.Cycles_0__reg_p  (
    .CK(clk),
    .D(_0050_),
    .Q(\Dmc.Cycles_0_ )
  );
  DFFQX1H7R \Dmc.Cycles_1__reg_p  (
    .CK(clk),
    .D(_0051_),
    .Q(\Dmc.Cycles_1_ )
  );
  DFFQX1H7R \Dmc.Cycles_2__reg_p  (
    .CK(clk),
    .D(_0052_),
    .Q(\Dmc.Cycles_2_ )
  );
  DFFQX1H7R \Dmc.Cycles_3__reg_p  (
    .CK(clk),
    .D(_0053_),
    .Q(\Dmc.Cycles_3_ )
  );
  DFFQX1H7R \Dmc.Cycles_4__reg_p  (
    .CK(clk),
    .D(_0054_),
    .Q(\Dmc.Cycles_4_ )
  );
  DFFQX1H7R \Dmc.Cycles_5__reg_p  (
    .CK(clk),
    .D(_0055_),
    .Q(\Dmc.Cycles_5_ )
  );
  DFFQX1H7R \Dmc.Cycles_6__reg_p  (
    .CK(clk),
    .D(_0056_),
    .Q(\Dmc.Cycles_6_ )
  );
  DFFQX1H7R \Dmc.Cycles_7__reg_p  (
    .CK(clk),
    .D(_0057_),
    .Q(\Dmc.Cycles_7_ )
  );
  DFFQX1H7R \Dmc.Cycles_8__reg_p  (
    .CK(clk),
    .D(_0058_),
    .Q(\Dmc.Cycles_8_ )
  );
  DFFQX1H7R \Dmc.HasSampleBuffer_reg_p  (
    .CK(clk),
    .D(_0059_),
    .Q(\Dmc.HasSampleBuffer )
  );
  DFFQX1H7R \Dmc.IrqEnable_reg_p  (
    .CK(clk),
    .D(_0060_),
    .Q(\Dmc.IrqEnable )
  );
  DFFQX1H7R \Dmc.Irq_reg_p  (
    .CK(clk),
    .D(_0061_),
    .Q(\DOUT[7] )
  );
  DFFQX1H7R \Dmc.IsDmcActive_reg_p  (
    .CK(clk),
    .D(_0062_),
    .Q(\DOUT[4] )
  );
  DFFQX1H7R \Dmc.Loop_reg_p  (
    .CK(clk),
    .D(_0063_),
    .Q(\Dmc.Loop )
  );
  DFFQX1H7R \Dmc.SampleAddress_0__reg_p  (
    .CK(clk),
    .D(_0064_),
    .Q(\Dmc.SampleAddress_0_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_1__reg_p  (
    .CK(clk),
    .D(_0065_),
    .Q(\Dmc.SampleAddress_1_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_2__reg_p  (
    .CK(clk),
    .D(_0066_),
    .Q(\Dmc.SampleAddress_2_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_3__reg_p  (
    .CK(clk),
    .D(_0067_),
    .Q(\Dmc.SampleAddress_3_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_4__reg_p  (
    .CK(clk),
    .D(_0068_),
    .Q(\Dmc.SampleAddress_4_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_5__reg_p  (
    .CK(clk),
    .D(_0069_),
    .Q(\Dmc.SampleAddress_5_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_6__reg_p  (
    .CK(clk),
    .D(_0070_),
    .Q(\Dmc.SampleAddress_6_ )
  );
  DFFQX1H7R \Dmc.SampleAddress_7__reg_p  (
    .CK(clk),
    .D(_0071_),
    .Q(\Dmc.SampleAddress_7_ )
  );
  DFFQX1H7R \Dmc.SampleLen_0__reg_p  (
    .CK(clk),
    .D(_0072_),
    .Q(\Dmc.SampleLen_0_ )
  );
  DFFQX1H7R \Dmc.SampleLen_1__reg_p  (
    .CK(clk),
    .D(_0073_),
    .Q(\Dmc.SampleLen_1_ )
  );
  DFFQX1H7R \Dmc.SampleLen_2__reg_p  (
    .CK(clk),
    .D(_0074_),
    .Q(\Dmc.SampleLen_2_ )
  );
  DFFQX1H7R \Dmc.SampleLen_3__reg_p  (
    .CK(clk),
    .D(_0075_),
    .Q(\Dmc.SampleLen_3_ )
  );
  DFFQX1H7R \Dmc.SampleLen_4__reg_p  (
    .CK(clk),
    .D(_0076_),
    .Q(\Dmc.SampleLen_4_ )
  );
  DFFQX1H7R \Dmc.SampleLen_5__reg_p  (
    .CK(clk),
    .D(_0077_),
    .Q(\Dmc.SampleLen_5_ )
  );
  DFFQX1H7R \Dmc.SampleLen_6__reg_p  (
    .CK(clk),
    .D(_0078_),
    .Q(\Dmc.SampleLen_6_ )
  );
  DFFQX1H7R \Dmc.SampleLen_7__reg_p  (
    .CK(clk),
    .D(_0079_),
    .Q(\Dmc.SampleLen_7_ )
  );
  DFFQX1H7R FrameInterrupt_reg_p (
    .CK(clk),
    .D(_0080_),
    .Q(FrameInterrupt)
  );
  DFFQX1H7R FrameSeqMode_reg_p (
    .CK(clk),
    .D(_0081_),
    .Q(FrameSeqMode)
  );
  DFFQX1H7R IrqCtr_0__reg_p (
    .CK(clk),
    .D(_0082_),
    .Q(IrqCtr_0_)
  );
  DFFQX1H7R IrqCtr_1__reg_p (
    .CK(clk),
    .D(_0083_),
    .Q(IrqCtr_1_)
  );
  DFFQX1H7R \Noi.Enabled_reg_p  (
    .CK(clk),
    .D(_0084_),
    .Q(\Noi.Enabled )
  );
  DFFQX1H7R \Noi.EnvLoop_reg_p  (
    .CK(clk),
    .D(_0085_),
    .Q(\Noi.EnvLoop )
  );
  DFFQX1H7R \Noi.LenCtr_0__reg_p  (
    .CK(clk),
    .D(_0086_),
    .Q(\Noi.LenCtr_0_ )
  );
  DFFQX1H7R \Noi.LenCtr_1__reg_p  (
    .CK(clk),
    .D(_0087_),
    .Q(\Noi.LenCtr_1_ )
  );
  DFFQX1H7R \Noi.LenCtr_2__reg_p  (
    .CK(clk),
    .D(_0088_),
    .Q(\Noi.LenCtr_2_ )
  );
  DFFQX1H7R \Noi.LenCtr_3__reg_p  (
    .CK(clk),
    .D(_0089_),
    .Q(\Noi.LenCtr_3_ )
  );
  DFFQX1H7R \Noi.LenCtr_4__reg_p  (
    .CK(clk),
    .D(_0090_),
    .Q(\Noi.LenCtr_4_ )
  );
  DFFQX1H7R \Noi.LenCtr_5__reg_p  (
    .CK(clk),
    .D(_0091_),
    .Q(\Noi.LenCtr_5_ )
  );
  DFFQX1H7R \Noi.LenCtr_6__reg_p  (
    .CK(clk),
    .D(_0092_),
    .Q(\Noi.LenCtr_6_ )
  );
  DFFQX1H7R \Noi.LenCtr_7__reg_p  (
    .CK(clk),
    .D(_0093_),
    .Q(\Noi.LenCtr_7_ )
  );
  DFFQX1H7R \Sq1.Enabled_reg_p  (
    .CK(clk),
    .D(_0094_),
    .Q(\Sq1.Enabled )
  );
  DFFQX1H7R \Sq1.EnvLoop_reg_p  (
    .CK(clk),
    .D(_0095_),
    .Q(\Sq1.EnvLoop )
  );
  DFFQX1H7R \Sq1.LenCtr_0__reg_p  (
    .CK(clk),
    .D(_0096_),
    .Q(\Sq1.LenCtr_0_ )
  );
  DFFQX1H7R \Sq1.LenCtr_1__reg_p  (
    .CK(clk),
    .D(_0097_),
    .Q(\Sq1.LenCtr_1_ )
  );
  DFFQX1H7R \Sq1.LenCtr_2__reg_p  (
    .CK(clk),
    .D(_0098_),
    .Q(\Sq1.LenCtr_2_ )
  );
  DFFQX1H7R \Sq1.LenCtr_3__reg_p  (
    .CK(clk),
    .D(_0099_),
    .Q(\Sq1.LenCtr_3_ )
  );
  DFFQX1H7R \Sq1.LenCtr_4__reg_p  (
    .CK(clk),
    .D(_0100_),
    .Q(\Sq1.LenCtr_4_ )
  );
  DFFQX1H7R \Sq1.LenCtr_5__reg_p  (
    .CK(clk),
    .D(_0101_),
    .Q(\Sq1.LenCtr_5_ )
  );
  DFFQX1H7R \Sq1.LenCtr_6__reg_p  (
    .CK(clk),
    .D(_0102_),
    .Q(\Sq1.LenCtr_6_ )
  );
  DFFQX1H7R \Sq1.LenCtr_7__reg_p  (
    .CK(clk),
    .D(_0103_),
    .Q(\Sq1.LenCtr_7_ )
  );
  DFFQX1H7R \Sq2.Enabled_reg_p  (
    .CK(clk),
    .D(_0104_),
    .Q(\Sq2.Enabled )
  );
  DFFQX1H7R \Sq2.EnvLoop_reg_p  (
    .CK(clk),
    .D(_0105_),
    .Q(\Sq2.EnvLoop )
  );
  DFFQX1H7R \Sq2.LenCtr_0__reg_p  (
    .CK(clk),
    .D(_0106_),
    .Q(\Sq2.LenCtr_0_ )
  );
  DFFQX1H7R \Sq2.LenCtr_1__reg_p  (
    .CK(clk),
    .D(_0107_),
    .Q(\Sq2.LenCtr_1_ )
  );
  DFFQX1H7R \Sq2.LenCtr_2__reg_p  (
    .CK(clk),
    .D(_0108_),
    .Q(\Sq2.LenCtr_2_ )
  );
  DFFQX1H7R \Sq2.LenCtr_3__reg_p  (
    .CK(clk),
    .D(_0109_),
    .Q(\Sq2.LenCtr_3_ )
  );
  DFFQX1H7R \Sq2.LenCtr_4__reg_p  (
    .CK(clk),
    .D(_0110_),
    .Q(\Sq2.LenCtr_4_ )
  );
  DFFQX1H7R \Sq2.LenCtr_5__reg_p  (
    .CK(clk),
    .D(_0111_),
    .Q(\Sq2.LenCtr_5_ )
  );
  DFFQX1H7R \Sq2.LenCtr_6__reg_p  (
    .CK(clk),
    .D(_0112_),
    .Q(\Sq2.LenCtr_6_ )
  );
  DFFQX1H7R \Sq2.LenCtr_7__reg_p  (
    .CK(clk),
    .D(_0113_),
    .Q(\Sq2.LenCtr_7_ )
  );
  DFFQX1H7R \Tri.Enabled_reg_p  (
    .CK(clk),
    .D(_0114_),
    .Q(\Tri.Enabled )
  );
  DFFQX1H7R \Tri.LenCtrHalt_reg_p  (
    .CK(clk),
    .D(_0115_),
    .Q(\Tri.LenCtrHalt )
  );
  DFFQX1H7R \Tri.LenCtr_0__reg_p  (
    .CK(clk),
    .D(_0116_),
    .Q(\Tri.LenCtr_0_ )
  );
  DFFQX1H7R \Tri.LenCtr_1__reg_p  (
    .CK(clk),
    .D(_0117_),
    .Q(\Tri.LenCtr_1_ )
  );
  DFFQX1H7R \Tri.LenCtr_2__reg_p  (
    .CK(clk),
    .D(_0118_),
    .Q(\Tri.LenCtr_2_ )
  );
  DFFQX1H7R \Tri.LenCtr_3__reg_p  (
    .CK(clk),
    .D(_0119_),
    .Q(\Tri.LenCtr_3_ )
  );
  DFFQX1H7R \Tri.LenCtr_4__reg_p  (
    .CK(clk),
    .D(_0120_),
    .Q(\Tri.LenCtr_4_ )
  );
  DFFQX1H7R \Tri.LenCtr_5__reg_p  (
    .CK(clk),
    .D(_0121_),
    .Q(\Tri.LenCtr_5_ )
  );
  DFFQX1H7R \Tri.LenCtr_6__reg_p  (
    .CK(clk),
    .D(_0122_),
    .Q(\Tri.LenCtr_6_ )
  );
  DFFQX1H7R \Tri.LenCtr_7__reg_p  (
    .CK(clk),
    .D(_0123_),
    .Q(\Tri.LenCtr_7_ )
  );
  DFFQX1H7R Wrote4017_reg_p (
    .CK(clk),
    .D(_0124_),
    .Q(Wrote4017)
  );
  DFFQX1H7R odd_or_even_reg_p (
    .CK(clk),
    .D(_0125_),
    .Q(odd_or_even)
  );
  assign \Sample[15]  = _0667_;
  assign \Sample[14]  = _0667_;
  assign \Sample[13]  = _0667_;
  assign \Sample[12]  = _0667_;
  assign \Sample[11]  = _0667_;
  assign \Sample[10]  = _0667_;
  assign \Sample[9]  = _0667_;
  assign \Sample[8]  = _0667_;
  assign \Sample[7]  = _0667_;
  assign \Sample[6]  = _0667_;
  assign \Sample[5]  = _0667_;
  assign \Sample[4]  = _0667_;
  assign \Sample[3]  = _0667_;
  assign \Sample[2]  = _0667_;
  assign \Sample[1]  = _0667_;
  assign \Sample[0]  = _0667_;
  assign \DOUT[5]  = _0667_;
  assign \DmaAddr[15]  = _0666_;
endmodule
