/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module ascon(clk, reset_n, cs, we, \address[0] , \address[1] , \address[2] , \address[3] , \address[4] , \address[5] , \address[6] , \address[7] , \write_data[0] , \write_data[1] , \write_data[2] , \write_data[3] , \write_data[4] , \write_data[5] , \write_data[6] , \write_data[7] , \write_data[8] 
, \write_data[9] , \write_data[10] , \write_data[11] , \write_data[12] , \write_data[13] , \write_data[14] , \write_data[15] , \write_data[16] , \write_data[17] , \write_data[18] , \write_data[19] , \write_data[20] , \write_data[21] , \write_data[22] , \write_data[23] , \write_data[24] , \write_data[25] , \write_data[26] , \write_data[27] , \write_data[28] , \write_data[29] 
, \write_data[30] , \write_data[31] , \read_data[0] , \read_data[1] , \read_data[2] , \read_data[3] , \read_data[4] , \read_data[5] , \read_data[6] , \read_data[7] , \read_data[8] , \read_data[9] , \read_data[10] , \read_data[11] , \read_data[12] , \read_data[13] , \read_data[14] , \read_data[15] , \read_data[16] , \read_data[17] , \read_data[18] 
, \read_data[19] , \read_data[20] , \read_data[21] , \read_data[22] , \read_data[23] , \read_data[24] , \read_data[25] , \read_data[26] , \read_data[27] , \read_data[28] , \read_data[29] , \read_data[30] , \read_data[31] );
  input clk;
  wire clk;
  input reset_n;
  wire reset_n;
  input cs;
  wire cs;
  input we;
  wire we;
  input \address[0] ;
  wire \address[0] ;
  input \address[1] ;
  wire \address[1] ;
  input \address[2] ;
  wire \address[2] ;
  input \address[3] ;
  wire \address[3] ;
  input \address[4] ;
  wire \address[4] ;
  input \address[5] ;
  wire \address[5] ;
  input \address[6] ;
  wire \address[6] ;
  input \address[7] ;
  wire \address[7] ;
  input \write_data[0] ;
  wire \write_data[0] ;
  input \write_data[1] ;
  wire \write_data[1] ;
  input \write_data[2] ;
  wire \write_data[2] ;
  input \write_data[3] ;
  wire \write_data[3] ;
  input \write_data[4] ;
  wire \write_data[4] ;
  input \write_data[5] ;
  wire \write_data[5] ;
  input \write_data[6] ;
  wire \write_data[6] ;
  input \write_data[7] ;
  wire \write_data[7] ;
  input \write_data[8] ;
  wire \write_data[8] ;
  input \write_data[9] ;
  wire \write_data[9] ;
  input \write_data[10] ;
  wire \write_data[10] ;
  input \write_data[11] ;
  wire \write_data[11] ;
  input \write_data[12] ;
  wire \write_data[12] ;
  input \write_data[13] ;
  wire \write_data[13] ;
  input \write_data[14] ;
  wire \write_data[14] ;
  input \write_data[15] ;
  wire \write_data[15] ;
  input \write_data[16] ;
  wire \write_data[16] ;
  input \write_data[17] ;
  wire \write_data[17] ;
  input \write_data[18] ;
  wire \write_data[18] ;
  input \write_data[19] ;
  wire \write_data[19] ;
  input \write_data[20] ;
  wire \write_data[20] ;
  input \write_data[21] ;
  wire \write_data[21] ;
  input \write_data[22] ;
  wire \write_data[22] ;
  input \write_data[23] ;
  wire \write_data[23] ;
  input \write_data[24] ;
  wire \write_data[24] ;
  input \write_data[25] ;
  wire \write_data[25] ;
  input \write_data[26] ;
  wire \write_data[26] ;
  input \write_data[27] ;
  wire \write_data[27] ;
  input \write_data[28] ;
  wire \write_data[28] ;
  input \write_data[29] ;
  wire \write_data[29] ;
  input \write_data[30] ;
  wire \write_data[30] ;
  input \write_data[31] ;
  wire \write_data[31] ;
  output \read_data[0] ;
  wire \read_data[0] ;
  output \read_data[1] ;
  wire \read_data[1] ;
  output \read_data[2] ;
  wire \read_data[2] ;
  output \read_data[3] ;
  wire \read_data[3] ;
  output \read_data[4] ;
  wire \read_data[4] ;
  output \read_data[5] ;
  wire \read_data[5] ;
  output \read_data[6] ;
  wire \read_data[6] ;
  output \read_data[7] ;
  wire \read_data[7] ;
  output \read_data[8] ;
  wire \read_data[8] ;
  output \read_data[9] ;
  wire \read_data[9] ;
  output \read_data[10] ;
  wire \read_data[10] ;
  output \read_data[11] ;
  wire \read_data[11] ;
  output \read_data[12] ;
  wire \read_data[12] ;
  output \read_data[13] ;
  wire \read_data[13] ;
  output \read_data[14] ;
  wire \read_data[14] ;
  output \read_data[15] ;
  wire \read_data[15] ;
  output \read_data[16] ;
  wire \read_data[16] ;
  output \read_data[17] ;
  wire \read_data[17] ;
  output \read_data[18] ;
  wire \read_data[18] ;
  output \read_data[19] ;
  wire \read_data[19] ;
  output \read_data[20] ;
  wire \read_data[20] ;
  output \read_data[21] ;
  wire \read_data[21] ;
  output \read_data[22] ;
  wire \read_data[22] ;
  output \read_data[23] ;
  wire \read_data[23] ;
  output \read_data[24] ;
  wire \read_data[24] ;
  output \read_data[25] ;
  wire \read_data[25] ;
  output \read_data[26] ;
  wire \read_data[26] ;
  output \read_data[27] ;
  wire \read_data[27] ;
  output \read_data[28] ;
  wire \read_data[28] ;
  output \read_data[29] ;
  wire \read_data[29] ;
  output \read_data[30] ;
  wire \read_data[30] ;
  output \read_data[31] ;
  wire \read_data[31] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire \core.ascon_core_ctrl_reg_0_ ;
  wire \core.ascon_core_ctrl_reg_1_ ;
  wire \core.ascon_core_ctrl_reg_2_ ;
  wire \core.next ;
  wire \core.ready ;
  wire next_new;
  AND2X1H7L _24_ (
    .A(\core.ascon_core_ctrl_reg_0_ ),
    .B(\core.ascon_core_ctrl_reg_2_ ),
    .Y(_00_)
  );
  NOR2X0P5H7R _25_ (
    .A(\core.ascon_core_ctrl_reg_1_ ),
    .B(\core.ascon_core_ctrl_reg_2_ ),
    .Y(_06_)
  );
  NAND3BX0P5H7R _26_ (
    .AN(\core.ascon_core_ctrl_reg_0_ ),
    .B(\core.next ),
    .C(_06_),
    .Y(_07_)
  );
  NAND2X0P5H7R _27_ (
    .A(\core.ascon_core_ctrl_reg_1_ ),
    .B(\core.ascon_core_ctrl_reg_2_ ),
    .Y(_08_)
  );
  NAND2X0P5H7R _28_ (
    .A(_07_),
    .B(_08_),
    .Y(_01_)
  );
  OAI21X0P5H7R _29_ (
    .A0(\core.ascon_core_ctrl_reg_1_ ),
    .A1(\core.ascon_core_ctrl_reg_2_ ),
    .B0(\core.ascon_core_ctrl_reg_0_ ),
    .Y(_09_)
  );
  NAND2X0P5H7R _30_ (
    .A(_08_),
    .B(_09_),
    .Y(_02_)
  );
  OR3X1H7R _31_ (
    .A(\core.ascon_core_ctrl_reg_0_ ),
    .B(\core.ascon_core_ctrl_reg_1_ ),
    .C(\core.ascon_core_ctrl_reg_2_ ),
    .Y(_10_)
  );
  AOI31X0P5H7R _32_ (
    .A0(_08_),
    .A1(_09_),
    .A2(_10_),
    .B0(\core.ready ),
    .Y(_11_)
  );
  NOR2BX1H7L _33_ (
    .AN(_07_),
    .B(_11_),
    .Z(_03_)
  );
  NOR2BX3H7L _34_ (
    .AN(cs),
    .B(\address[2] ),
    .Z(_12_)
  );
  OR4X3H7L _35_ (
    .A(\address[4] ),
    .B(\address[5] ),
    .C(\address[6] ),
    .D(\address[7] ),
    .Y(_13_)
  );
  NOR3BX1P4H7L _36_ (
    .AN(_12_),
    .B(\address[1] ),
    .C(_13_),
    .Y(_14_)
  );
  NAND2X0P5H7R _37_ (
    .A(\address[3] ),
    .B(\write_data[0] ),
    .Y(_15_)
  );
  NAND3BX0P5H7R _38_ (
    .AN(\address[0] ),
    .B(\core.ready ),
    .C(we),
    .Y(_16_)
  );
  NOR3BX0P7H7L _39_ (
    .AN(_14_),
    .B(_15_),
    .C(_16_),
    .Y(next_new)
  );
  NOR2X3H7L _40_ (
    .A(\address[3] ),
    .B(we),
    .Y(_17_)
  );
  NAND4BBX6H7L _41_ (
    .AN(\address[1] ),
    .BN(_13_),
    .C(_12_),
    .D(_17_),
    .Y(_18_)
  );
  BUFX8H7L _42_ (
    .A(_18_),
    .Y(_19_)
  );
  INVX1P4H7L _43_ (
    .A(_19_),
    .Y(\read_data[30] )
  );
  NAND3BX2H7L _44_ (
    .AN(_13_),
    .B(_12_),
    .C(_17_),
    .Y(_20_)
  );
  BUFX5H7L _45_ (
    .A(_20_),
    .Y(_21_)
  );
  AOI21X1P4H7L _46_ (
    .A0(\address[1] ),
    .A1(\address[0] ),
    .B0(_21_),
    .Y(\read_data[21] )
  );
  NOR2X1P4H7L _47_ (
    .A(\address[0] ),
    .B(_19_),
    .Y(\read_data[20] )
  );
  NOR3BX1P4H7L _48_ (
    .AN(\address[1] ),
    .B(\address[0] ),
    .C(_21_),
    .Y(\read_data[19] )
  );
  XNOR2X0P5H7R _49_ (
    .A(\address[1] ),
    .B(\address[0] ),
    .Y(_22_)
  );
  NOR2X1P4H7L _50_ (
    .A(_21_),
    .B(_22_),
    .Y(\read_data[18] )
  );
  NOR2X1P4H7L _51_ (
    .A(\address[0] ),
    .B(_21_),
    .Y(\read_data[17] )
  );
  INVX1P4H7L _52_ (
    .A(_19_),
    .Y(\read_data[16] )
  );
  NOR2X1P4H7L _53_ (
    .A(\address[0] ),
    .B(_19_),
    .Y(\read_data[14] )
  );
  AOI21X1P4H7L _54_ (
    .A0(\address[1] ),
    .A1(\address[0] ),
    .B0(_21_),
    .Y(\read_data[13] )
  );
  NOR3BX1P4H7L _55_ (
    .AN(\address[1] ),
    .B(\address[0] ),
    .C(_21_),
    .Y(\read_data[12] )
  );
  AOI21X1P4H7L _56_ (
    .A0(\address[1] ),
    .A1(\address[0] ),
    .B0(_21_),
    .Y(\read_data[29] )
  );
  NOR2X1P4H7L _57_ (
    .A(\address[0] ),
    .B(_19_),
    .Y(\read_data[9] )
  );
  NOR2X1P4H7L _58_ (
    .A(\address[0] ),
    .B(_21_),
    .Y(\read_data[8] )
  );
  NOR2X1P4H7L _59_ (
    .A(\address[0] ),
    .B(_19_),
    .Y(\read_data[6] )
  );
  AOI21X1P4H7L _60_ (
    .A0(\address[1] ),
    .A1(\address[0] ),
    .B0(_21_),
    .Y(\read_data[5] )
  );
  NOR3BX1P4H7L _61_ (
    .AN(\address[1] ),
    .B(\address[0] ),
    .C(_21_),
    .Y(\read_data[4] )
  );
  NOR2X0P5H7R _62_ (
    .A(\address[0] ),
    .B(_18_),
    .Y(\read_data[3] )
  );
  NOR2X0P5H7R _63_ (
    .A(\address[0] ),
    .B(_18_),
    .Y(\read_data[2] )
  );
  NOR3BX0P5H7R _64_ (
    .AN(\address[1] ),
    .B(\address[0] ),
    .C(_20_),
    .Y(\read_data[28] )
  );
  NOR2X0P5H7R _65_ (
    .A(\address[0] ),
    .B(_18_),
    .Y(\read_data[1] )
  );
  NAND3X0P5H7R _66_ (
    .A(\address[3] ),
    .B(\address[0] ),
    .C(\core.ready ),
    .Y(_04_)
  );
  OAOI211X0P5H7R _67_ (
    .A0(\address[3] ),
    .A1(\address[0] ),
    .B0(_04_),
    .C0(we),
    .Y(_05_)
  );
  AND2X1H7L _68_ (
    .A(_14_),
    .B(_05_),
    .Y(\read_data[0] )
  );
  NOR2BX2H7L _69_ (
    .AN(\address[0] ),
    .B(_19_),
    .Z(\read_data[27] )
  );
  NOR2BX2H7L _70_ (
    .AN(\address[0] ),
    .B(_19_),
    .Z(\read_data[26] )
  );
  NOR2BX2H7L _71_ (
    .AN(\address[0] ),
    .B(_19_),
    .Z(\read_data[25] )
  );
  NOR2X0P5H7R _72_ (
    .A(\address[0] ),
    .B(_18_),
    .Y(\read_data[24] )
  );
  INVX1P4H7L _73_ (
    .A(_19_),
    .Y(\read_data[22] )
  );
  TIELOH7R _74_ (
    .Z(_23_)
  );
  DFFRQX2H7R \core.ascon_core_ctrl_reg_0__reg_p  (
    .CK(clk),
    .D(_00_),
    .Q(\core.ascon_core_ctrl_reg_0_ ),
    .RN(reset_n)
  );
  DFFRQX2H7R \core.ascon_core_ctrl_reg_1__reg_p  (
    .CK(clk),
    .D(_01_),
    .Q(\core.ascon_core_ctrl_reg_1_ ),
    .RN(reset_n)
  );
  DFFRQX2H7R \core.ascon_core_ctrl_reg_2__reg_p  (
    .CK(clk),
    .D(_02_),
    .Q(\core.ascon_core_ctrl_reg_2_ ),
    .RN(reset_n)
  );
  DFFRQX2H7R \core.next_reg_p  (
    .CK(clk),
    .D(next_new),
    .Q(\core.next ),
    .RN(reset_n)
  );
  DFFRQX2H7R \core.ready_reg_p  (
    .CK(clk),
    .D(_03_),
    .Q(\core.ready ),
    .RN(reset_n)
  );
  assign \read_data[31]  = _23_;
  assign \read_data[23]  = _23_;
  assign \read_data[15]  = _23_;
  assign \read_data[11]  = _23_;
  assign \read_data[10]  = _23_;
  assign \read_data[7]  = _23_;
endmodule
