/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module s44(\addr[0] , \addr[1] , \addr[2] , \addr[3] , \addr[4] , \addr[5] , \addr[6] , out, config_clk, config_en, \config_in[0] , \config_in[1] , \config_in[2] , \config_in[3] , \config_in[4] , \config_in[5] , \config_in[6] , \config_in[7] , \config_out[0] , \config_out[1] , \config_out[2] 
, \config_out[3] , \config_out[4] , \config_out[5] , \config_out[6] , \config_out[7] );
  input \addr[0] ;
  wire \addr[0] ;
  input \addr[1] ;
  wire \addr[1] ;
  input \addr[2] ;
  wire \addr[2] ;
  input \addr[3] ;
  wire \addr[3] ;
  input \addr[4] ;
  wire \addr[4] ;
  input \addr[5] ;
  wire \addr[5] ;
  input \addr[6] ;
  wire \addr[6] ;
  output out;
  wire out;
  input config_clk;
  wire config_clk;
  input config_en;
  wire config_en;
  input \config_in[0] ;
  wire \config_in[0] ;
  input \config_in[1] ;
  wire \config_in[1] ;
  input \config_in[2] ;
  wire \config_in[2] ;
  input \config_in[3] ;
  wire \config_in[3] ;
  input \config_in[4] ;
  wire \config_in[4] ;
  input \config_in[5] ;
  wire \config_in[5] ;
  input \config_in[6] ;
  wire \config_in[6] ;
  input \config_in[7] ;
  wire \config_in[7] ;
  output \config_out[0] ;
  wire \config_out[0] ;
  output \config_out[1] ;
  wire \config_out[1] ;
  output \config_out[2] ;
  wire \config_out[2] ;
  output \config_out[3] ;
  wire \config_out[3] ;
  output \config_out[4] ;
  wire \config_out[4] ;
  output \config_out[5] ;
  wire \config_out[5] ;
  output \config_out[6] ;
  wire \config_out[6] ;
  output \config_out[7] ;
  wire \config_out[7] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire \first_lut.config_out_0_ ;
  wire \first_lut.config_out_1_ ;
  wire \first_lut.config_out_2_ ;
  wire \first_lut.config_out_3_ ;
  wire \first_lut.config_out_4_ ;
  wire \first_lut.config_out_5_ ;
  wire \first_lut.config_out_6_ ;
  wire \first_lut.config_out_7_ ;
  wire \first_lut.mem_0_ ;
  wire \first_lut.mem_1_ ;
  wire \first_lut.mem_2_ ;
  wire \first_lut.mem_3_ ;
  wire \first_lut.mem_4_ ;
  wire \first_lut.mem_5_ ;
  wire \first_lut.mem_6_ ;
  wire \first_lut.mem_7_ ;
  wire \second_lut.mem_0_ ;
  wire \second_lut.mem_1_ ;
  wire \second_lut.mem_2_ ;
  wire \second_lut.mem_3_ ;
  wire \second_lut.mem_4_ ;
  wire \second_lut.mem_5_ ;
  wire \second_lut.mem_6_ ;
  wire \second_lut.mem_7_ ;
  MUX2X0P5H7R _41_ (
    .A(\config_out[0] ),
    .B(\second_lut.mem_0_ ),
    .S0(config_en),
    .Y(_00_)
  );
  MUX2X0P5H7R _42_ (
    .A(\config_out[1] ),
    .B(\second_lut.mem_1_ ),
    .S0(config_en),
    .Y(_01_)
  );
  MUX2X0P5H7R _43_ (
    .A(\config_out[2] ),
    .B(\second_lut.mem_2_ ),
    .S0(config_en),
    .Y(_02_)
  );
  MUX2X0P5H7R _44_ (
    .A(\config_out[3] ),
    .B(\second_lut.mem_3_ ),
    .S0(config_en),
    .Y(_03_)
  );
  MUX2X0P5H7R _45_ (
    .A(\config_out[4] ),
    .B(\second_lut.mem_4_ ),
    .S0(config_en),
    .Y(_04_)
  );
  MUX2X0P5H7R _46_ (
    .A(\config_out[5] ),
    .B(\second_lut.mem_5_ ),
    .S0(config_en),
    .Y(_05_)
  );
  MUX2X0P5H7R _47_ (
    .A(\config_out[6] ),
    .B(\second_lut.mem_6_ ),
    .S0(config_en),
    .Y(_06_)
  );
  MUX2X0P5H7R _48_ (
    .A(\config_out[7] ),
    .B(\second_lut.mem_7_ ),
    .S0(config_en),
    .Y(_07_)
  );
  MUX2X0P5H7R _49_ (
    .A(\first_lut.config_out_0_ ),
    .B(\first_lut.mem_0_ ),
    .S0(config_en),
    .Y(_08_)
  );
  MUX2X0P5H7R _50_ (
    .A(\first_lut.config_out_1_ ),
    .B(\first_lut.mem_1_ ),
    .S0(config_en),
    .Y(_09_)
  );
  MUX2X0P5H7R _51_ (
    .A(\first_lut.config_out_2_ ),
    .B(\first_lut.mem_2_ ),
    .S0(config_en),
    .Y(_10_)
  );
  MUX2X0P5H7R _52_ (
    .A(\first_lut.config_out_3_ ),
    .B(\first_lut.mem_3_ ),
    .S0(config_en),
    .Y(_11_)
  );
  MUX2X0P5H7R _53_ (
    .A(\first_lut.config_out_4_ ),
    .B(\first_lut.mem_4_ ),
    .S0(config_en),
    .Y(_12_)
  );
  MUX2X0P5H7R _54_ (
    .A(\first_lut.config_out_5_ ),
    .B(\first_lut.mem_5_ ),
    .S0(config_en),
    .Y(_13_)
  );
  MUX2X0P5H7R _55_ (
    .A(\first_lut.config_out_6_ ),
    .B(\first_lut.mem_6_ ),
    .S0(config_en),
    .Y(_14_)
  );
  MUX2X0P5H7R _56_ (
    .A(\first_lut.config_out_7_ ),
    .B(\first_lut.mem_7_ ),
    .S0(config_en),
    .Y(_15_)
  );
  MUX2X0P5H7R _57_ (
    .A(\first_lut.mem_0_ ),
    .B(\config_in[0] ),
    .S0(config_en),
    .Y(_16_)
  );
  MUX2X0P5H7R _58_ (
    .A(\first_lut.mem_1_ ),
    .B(\config_in[1] ),
    .S0(config_en),
    .Y(_17_)
  );
  MUX2X0P5H7R _59_ (
    .A(\first_lut.mem_2_ ),
    .B(\config_in[2] ),
    .S0(config_en),
    .Y(_18_)
  );
  MUX2X0P5H7R _60_ (
    .A(\first_lut.mem_3_ ),
    .B(\config_in[3] ),
    .S0(config_en),
    .Y(_19_)
  );
  MUX2X0P5H7R _61_ (
    .A(\first_lut.mem_4_ ),
    .B(\config_in[4] ),
    .S0(config_en),
    .Y(_20_)
  );
  MUX2X0P5H7R _62_ (
    .A(\first_lut.mem_5_ ),
    .B(\config_in[5] ),
    .S0(config_en),
    .Y(_21_)
  );
  MUX2X0P5H7R _63_ (
    .A(\first_lut.mem_6_ ),
    .B(\config_in[6] ),
    .S0(config_en),
    .Y(_22_)
  );
  MUX2X0P5H7R _64_ (
    .A(\first_lut.mem_7_ ),
    .B(\config_in[7] ),
    .S0(config_en),
    .Y(_23_)
  );
  MUX4X1P4H7R _65_ (
    .A(\second_lut.mem_0_ ),
    .B(\second_lut.mem_1_ ),
    .C(\second_lut.mem_2_ ),
    .D(\second_lut.mem_3_ ),
    .S0(\addr[0] ),
    .S1(\addr[1] ),
    .Y(_32_)
  );
  MUX4X1P4H7R _66_ (
    .A(\second_lut.mem_4_ ),
    .B(\second_lut.mem_5_ ),
    .C(\second_lut.mem_6_ ),
    .D(\second_lut.mem_7_ ),
    .S0(\addr[0] ),
    .S1(\addr[1] ),
    .Y(_33_)
  );
  MUX4X1P4H7R _67_ (
    .A(\config_out[0] ),
    .B(\config_out[1] ),
    .C(\config_out[2] ),
    .D(\config_out[3] ),
    .S0(\addr[0] ),
    .S1(\addr[1] ),
    .Y(_34_)
  );
  MUX4X1P4H7R _68_ (
    .A(\config_out[4] ),
    .B(\config_out[5] ),
    .C(\config_out[6] ),
    .D(\config_out[7] ),
    .S0(\addr[0] ),
    .S1(\addr[1] ),
    .Y(_35_)
  );
  MUX4X1P4H7L _69_ (
    .A(\first_lut.mem_0_ ),
    .B(\first_lut.mem_1_ ),
    .C(\first_lut.mem_2_ ),
    .D(\first_lut.mem_3_ ),
    .S0(\addr[3] ),
    .S1(\addr[4] ),
    .Y(_36_)
  );
  MUX4X1P4H7L _70_ (
    .A(\first_lut.config_out_0_ ),
    .B(\first_lut.config_out_1_ ),
    .C(\first_lut.config_out_2_ ),
    .D(\first_lut.config_out_3_ ),
    .S0(\addr[3] ),
    .S1(\addr[4] ),
    .Y(_37_)
  );
  MUX4X3H7L _71_ (
    .A(\first_lut.mem_4_ ),
    .B(\first_lut.mem_5_ ),
    .C(\first_lut.mem_6_ ),
    .D(\first_lut.mem_7_ ),
    .S0(\addr[3] ),
    .S1(\addr[4] ),
    .Y(_38_)
  );
  MUX4X3H7L _72_ (
    .A(\first_lut.config_out_4_ ),
    .B(\first_lut.config_out_5_ ),
    .C(\first_lut.config_out_6_ ),
    .D(\first_lut.config_out_7_ ),
    .S0(\addr[3] ),
    .S1(\addr[4] ),
    .Y(_39_)
  );
  MUX4X3H7L _73_ (
    .A(_36_),
    .B(_37_),
    .C(_38_),
    .D(_39_),
    .S0(\addr[6] ),
    .S1(\addr[5] ),
    .Y(_40_)
  );
  MUX4X0P7H7L _74_ (
    .A(_32_),
    .B(_33_),
    .C(_34_),
    .D(_35_),
    .S0(\addr[2] ),
    .S1(_40_),
    .Y(out)
  );
  MUX2X0P5H7R _75_ (
    .A(\second_lut.mem_0_ ),
    .B(\first_lut.config_out_0_ ),
    .S0(config_en),
    .Y(_24_)
  );
  MUX2X0P5H7R _76_ (
    .A(\second_lut.mem_1_ ),
    .B(\first_lut.config_out_1_ ),
    .S0(config_en),
    .Y(_25_)
  );
  MUX2X0P5H7R _77_ (
    .A(\second_lut.mem_2_ ),
    .B(\first_lut.config_out_2_ ),
    .S0(config_en),
    .Y(_26_)
  );
  MUX2X0P5H7R _78_ (
    .A(\second_lut.mem_3_ ),
    .B(\first_lut.config_out_3_ ),
    .S0(config_en),
    .Y(_27_)
  );
  MUX2X0P5H7R _79_ (
    .A(\second_lut.mem_4_ ),
    .B(\first_lut.config_out_4_ ),
    .S0(config_en),
    .Y(_28_)
  );
  MUX2X0P5H7R _80_ (
    .A(\second_lut.mem_5_ ),
    .B(\first_lut.config_out_5_ ),
    .S0(config_en),
    .Y(_29_)
  );
  MUX2X0P5H7R _81_ (
    .A(\second_lut.mem_6_ ),
    .B(\first_lut.config_out_6_ ),
    .S0(config_en),
    .Y(_30_)
  );
  MUX2X0P5H7R _82_ (
    .A(\second_lut.mem_7_ ),
    .B(\first_lut.config_out_7_ ),
    .S0(config_en),
    .Y(_31_)
  );
  DFFQX1H7R \config_out[0]_reg_p  (
    .CK(config_clk),
    .D(_00_),
    .Q(\config_out[0] )
  );
  DFFQX1H7R \config_out[1]_reg_p  (
    .CK(config_clk),
    .D(_01_),
    .Q(\config_out[1] )
  );
  DFFQX1H7R \config_out[2]_reg_p  (
    .CK(config_clk),
    .D(_02_),
    .Q(\config_out[2] )
  );
  DFFQX1H7R \config_out[3]_reg_p  (
    .CK(config_clk),
    .D(_03_),
    .Q(\config_out[3] )
  );
  DFFQX1H7R \config_out[4]_reg_p  (
    .CK(config_clk),
    .D(_04_),
    .Q(\config_out[4] )
  );
  DFFQX1H7R \config_out[5]_reg_p  (
    .CK(config_clk),
    .D(_05_),
    .Q(\config_out[5] )
  );
  DFFQX1H7R \config_out[6]_reg_p  (
    .CK(config_clk),
    .D(_06_),
    .Q(\config_out[6] )
  );
  DFFQX1H7R \config_out[7]_reg_p  (
    .CK(config_clk),
    .D(_07_),
    .Q(\config_out[7] )
  );
  DFFQX1H7R \first_lut.config_out_0__reg_p  (
    .CK(config_clk),
    .D(_08_),
    .Q(\first_lut.config_out_0_ )
  );
  DFFQX1H7R \first_lut.config_out_1__reg_p  (
    .CK(config_clk),
    .D(_09_),
    .Q(\first_lut.config_out_1_ )
  );
  DFFQX1H7R \first_lut.config_out_2__reg_p  (
    .CK(config_clk),
    .D(_10_),
    .Q(\first_lut.config_out_2_ )
  );
  DFFQX1H7R \first_lut.config_out_3__reg_p  (
    .CK(config_clk),
    .D(_11_),
    .Q(\first_lut.config_out_3_ )
  );
  DFFQX1H7R \first_lut.config_out_4__reg_p  (
    .CK(config_clk),
    .D(_12_),
    .Q(\first_lut.config_out_4_ )
  );
  DFFQX1H7R \first_lut.config_out_5__reg_p  (
    .CK(config_clk),
    .D(_13_),
    .Q(\first_lut.config_out_5_ )
  );
  DFFQX1H7R \first_lut.config_out_6__reg_p  (
    .CK(config_clk),
    .D(_14_),
    .Q(\first_lut.config_out_6_ )
  );
  DFFQX1H7R \first_lut.config_out_7__reg_p  (
    .CK(config_clk),
    .D(_15_),
    .Q(\first_lut.config_out_7_ )
  );
  DFFQX1H7R \first_lut.mem_0__reg_p  (
    .CK(config_clk),
    .D(_16_),
    .Q(\first_lut.mem_0_ )
  );
  DFFQX1H7R \first_lut.mem_1__reg_p  (
    .CK(config_clk),
    .D(_17_),
    .Q(\first_lut.mem_1_ )
  );
  DFFQX1H7R \first_lut.mem_2__reg_p  (
    .CK(config_clk),
    .D(_18_),
    .Q(\first_lut.mem_2_ )
  );
  DFFQX1H7R \first_lut.mem_3__reg_p  (
    .CK(config_clk),
    .D(_19_),
    .Q(\first_lut.mem_3_ )
  );
  DFFQX1H7R \first_lut.mem_4__reg_p  (
    .CK(config_clk),
    .D(_20_),
    .Q(\first_lut.mem_4_ )
  );
  DFFQX1H7R \first_lut.mem_5__reg_p  (
    .CK(config_clk),
    .D(_21_),
    .Q(\first_lut.mem_5_ )
  );
  DFFQX1H7R \first_lut.mem_6__reg_p  (
    .CK(config_clk),
    .D(_22_),
    .Q(\first_lut.mem_6_ )
  );
  DFFQX1H7R \first_lut.mem_7__reg_p  (
    .CK(config_clk),
    .D(_23_),
    .Q(\first_lut.mem_7_ )
  );
  DFFQX1H7R \second_lut.mem_0__reg_p  (
    .CK(config_clk),
    .D(_24_),
    .Q(\second_lut.mem_0_ )
  );
  DFFQX1H7R \second_lut.mem_1__reg_p  (
    .CK(config_clk),
    .D(_25_),
    .Q(\second_lut.mem_1_ )
  );
  DFFQX1H7R \second_lut.mem_2__reg_p  (
    .CK(config_clk),
    .D(_26_),
    .Q(\second_lut.mem_2_ )
  );
  DFFQX1H7R \second_lut.mem_3__reg_p  (
    .CK(config_clk),
    .D(_27_),
    .Q(\second_lut.mem_3_ )
  );
  DFFQX1H7R \second_lut.mem_4__reg_p  (
    .CK(config_clk),
    .D(_28_),
    .Q(\second_lut.mem_4_ )
  );
  DFFQX1H7R \second_lut.mem_5__reg_p  (
    .CK(config_clk),
    .D(_29_),
    .Q(\second_lut.mem_5_ )
  );
  DFFQX1H7R \second_lut.mem_6__reg_p  (
    .CK(config_clk),
    .D(_30_),
    .Q(\second_lut.mem_6_ )
  );
  DFFQX1H7R \second_lut.mem_7__reg_p  (
    .CK(config_clk),
    .D(_31_),
    .Q(\second_lut.mem_7_ )
  );
endmodule
