/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module r8051(clk, rst, cpu_en, cpu_restart, rom_en, \rom_addr[0] , \rom_addr[1] , \rom_addr[2] , \rom_addr[3] , \rom_addr[4] , \rom_addr[5] , \rom_addr[6] , \rom_addr[7] , \rom_addr[8] , \rom_addr[9] , \rom_addr[10] , \rom_addr[11] , \rom_addr[12] , \rom_addr[13] , \rom_addr[14] , \rom_addr[15] 
, \rom_byte[0] , \rom_byte[1] , \rom_byte[2] , \rom_byte[3] , \rom_byte[4] , \rom_byte[5] , \rom_byte[6] , \rom_byte[7] , rom_vld, ram_rd_en_data, ram_rd_en_sfr, ram_rd_en_xdata, \ram_rd_addr[0] , \ram_rd_addr[1] , \ram_rd_addr[2] , \ram_rd_addr[3] , \ram_rd_addr[4] , \ram_rd_addr[5] , \ram_rd_addr[6] , \ram_rd_addr[7] , \ram_rd_addr[8] 
, \ram_rd_addr[9] , \ram_rd_addr[10] , \ram_rd_addr[11] , \ram_rd_addr[12] , \ram_rd_addr[13] , \ram_rd_addr[14] , \ram_rd_addr[15] , \ram_rd_byte[0] , \ram_rd_byte[1] , \ram_rd_byte[2] , \ram_rd_byte[3] , \ram_rd_byte[4] , \ram_rd_byte[5] , \ram_rd_byte[6] , \ram_rd_byte[7] , ram_rd_vld, ram_wr_en_data, ram_wr_en_sfr, ram_wr_en_xdata, \ram_wr_addr[0] , \ram_wr_addr[1] 
, \ram_wr_addr[2] , \ram_wr_addr[3] , \ram_wr_addr[4] , \ram_wr_addr[5] , \ram_wr_addr[6] , \ram_wr_addr[7] , \ram_wr_addr[8] , \ram_wr_addr[9] , \ram_wr_addr[10] , \ram_wr_addr[11] , \ram_wr_addr[12] , \ram_wr_addr[13] , \ram_wr_addr[14] , \ram_wr_addr[15] , \ram_wr_byte[0] , \ram_wr_byte[1] , \ram_wr_byte[2] , \ram_wr_byte[3] , \ram_wr_byte[4] , \ram_wr_byte[5] , \ram_wr_byte[6] 
, \ram_wr_byte[7] );
  input clk;
  wire clk;
  input rst;
  wire rst;
  input cpu_en;
  wire cpu_en;
  input cpu_restart;
  wire cpu_restart;
  output rom_en;
  wire rom_en;
  output \rom_addr[0] ;
  wire \rom_addr[0] ;
  output \rom_addr[1] ;
  wire \rom_addr[1] ;
  output \rom_addr[2] ;
  wire \rom_addr[2] ;
  output \rom_addr[3] ;
  wire \rom_addr[3] ;
  output \rom_addr[4] ;
  wire \rom_addr[4] ;
  output \rom_addr[5] ;
  wire \rom_addr[5] ;
  output \rom_addr[6] ;
  wire \rom_addr[6] ;
  output \rom_addr[7] ;
  wire \rom_addr[7] ;
  output \rom_addr[8] ;
  wire \rom_addr[8] ;
  output \rom_addr[9] ;
  wire \rom_addr[9] ;
  output \rom_addr[10] ;
  wire \rom_addr[10] ;
  output \rom_addr[11] ;
  wire \rom_addr[11] ;
  output \rom_addr[12] ;
  wire \rom_addr[12] ;
  output \rom_addr[13] ;
  wire \rom_addr[13] ;
  output \rom_addr[14] ;
  wire \rom_addr[14] ;
  output \rom_addr[15] ;
  wire \rom_addr[15] ;
  input \rom_byte[0] ;
  wire \rom_byte[0] ;
  input \rom_byte[1] ;
  wire \rom_byte[1] ;
  input \rom_byte[2] ;
  wire \rom_byte[2] ;
  input \rom_byte[3] ;
  wire \rom_byte[3] ;
  input \rom_byte[4] ;
  wire \rom_byte[4] ;
  input \rom_byte[5] ;
  wire \rom_byte[5] ;
  input \rom_byte[6] ;
  wire \rom_byte[6] ;
  input \rom_byte[7] ;
  wire \rom_byte[7] ;
  input rom_vld;
  wire rom_vld;
  output ram_rd_en_data;
  wire ram_rd_en_data;
  output ram_rd_en_sfr;
  wire ram_rd_en_sfr;
  output ram_rd_en_xdata;
  wire ram_rd_en_xdata;
  output \ram_rd_addr[0] ;
  wire \ram_rd_addr[0] ;
  output \ram_rd_addr[1] ;
  wire \ram_rd_addr[1] ;
  output \ram_rd_addr[2] ;
  wire \ram_rd_addr[2] ;
  output \ram_rd_addr[3] ;
  wire \ram_rd_addr[3] ;
  output \ram_rd_addr[4] ;
  wire \ram_rd_addr[4] ;
  output \ram_rd_addr[5] ;
  wire \ram_rd_addr[5] ;
  output \ram_rd_addr[6] ;
  wire \ram_rd_addr[6] ;
  output \ram_rd_addr[7] ;
  wire \ram_rd_addr[7] ;
  output \ram_rd_addr[8] ;
  wire \ram_rd_addr[8] ;
  output \ram_rd_addr[9] ;
  wire \ram_rd_addr[9] ;
  output \ram_rd_addr[10] ;
  wire \ram_rd_addr[10] ;
  output \ram_rd_addr[11] ;
  wire \ram_rd_addr[11] ;
  output \ram_rd_addr[12] ;
  wire \ram_rd_addr[12] ;
  output \ram_rd_addr[13] ;
  wire \ram_rd_addr[13] ;
  output \ram_rd_addr[14] ;
  wire \ram_rd_addr[14] ;
  output \ram_rd_addr[15] ;
  wire \ram_rd_addr[15] ;
  input \ram_rd_byte[0] ;
  wire \ram_rd_byte[0] ;
  input \ram_rd_byte[1] ;
  wire \ram_rd_byte[1] ;
  input \ram_rd_byte[2] ;
  wire \ram_rd_byte[2] ;
  input \ram_rd_byte[3] ;
  wire \ram_rd_byte[3] ;
  input \ram_rd_byte[4] ;
  wire \ram_rd_byte[4] ;
  input \ram_rd_byte[5] ;
  wire \ram_rd_byte[5] ;
  input \ram_rd_byte[6] ;
  wire \ram_rd_byte[6] ;
  input \ram_rd_byte[7] ;
  wire \ram_rd_byte[7] ;
  input ram_rd_vld;
  wire ram_rd_vld;
  output ram_wr_en_data;
  wire ram_wr_en_data;
  output ram_wr_en_sfr;
  wire ram_wr_en_sfr;
  output ram_wr_en_xdata;
  wire ram_wr_en_xdata;
  output \ram_wr_addr[0] ;
  wire \ram_wr_addr[0] ;
  output \ram_wr_addr[1] ;
  wire \ram_wr_addr[1] ;
  output \ram_wr_addr[2] ;
  wire \ram_wr_addr[2] ;
  output \ram_wr_addr[3] ;
  wire \ram_wr_addr[3] ;
  output \ram_wr_addr[4] ;
  wire \ram_wr_addr[4] ;
  output \ram_wr_addr[5] ;
  wire \ram_wr_addr[5] ;
  output \ram_wr_addr[6] ;
  wire \ram_wr_addr[6] ;
  output \ram_wr_addr[7] ;
  wire \ram_wr_addr[7] ;
  output \ram_wr_addr[8] ;
  wire \ram_wr_addr[8] ;
  output \ram_wr_addr[9] ;
  wire \ram_wr_addr[9] ;
  output \ram_wr_addr[10] ;
  wire \ram_wr_addr[10] ;
  output \ram_wr_addr[11] ;
  wire \ram_wr_addr[11] ;
  output \ram_wr_addr[12] ;
  wire \ram_wr_addr[12] ;
  output \ram_wr_addr[13] ;
  wire \ram_wr_addr[13] ;
  output \ram_wr_addr[14] ;
  wire \ram_wr_addr[14] ;
  output \ram_wr_addr[15] ;
  wire \ram_wr_addr[15] ;
  output \ram_wr_byte[0] ;
  wire \ram_wr_byte[0] ;
  output \ram_wr_byte[1] ;
  wire \ram_wr_byte[1] ;
  output \ram_wr_byte[2] ;
  wire \ram_wr_byte[2] ;
  output \ram_wr_byte[3] ;
  wire \ram_wr_byte[3] ;
  output \ram_wr_byte[4] ;
  wire \ram_wr_byte[4] ;
  output \ram_wr_byte[5] ;
  wire \ram_wr_byte[5] ;
  output \ram_wr_byte[6] ;
  wire \ram_wr_byte[6] ;
  output \ram_wr_byte[7] ;
  wire \ram_wr_byte[7] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  NOR2BX0P5H7L _33_ (
    .AN(\rom_addr[9] ),
    .B(cpu_restart),
    .Z(_31_)
  );
  NOR2BX0P5H7L _34_ (
    .AN(\rom_addr[8] ),
    .B(cpu_restart),
    .Z(_30_)
  );
  NOR2BX0P5H7L _35_ (
    .AN(\rom_addr[7] ),
    .B(cpu_restart),
    .Z(_29_)
  );
  NOR2BX0P5H7L _36_ (
    .AN(\rom_addr[6] ),
    .B(cpu_restart),
    .Z(_28_)
  );
  NOR2BX0P5H7L _37_ (
    .AN(\rom_addr[5] ),
    .B(cpu_restart),
    .Z(_27_)
  );
  NOR2BX0P5H7L _38_ (
    .AN(\rom_addr[4] ),
    .B(cpu_restart),
    .Z(_26_)
  );
  NOR2BX0P5H7L _39_ (
    .AN(\rom_addr[3] ),
    .B(cpu_restart),
    .Z(_25_)
  );
  NOR2BX0P5H7L _40_ (
    .AN(\rom_addr[2] ),
    .B(cpu_restart),
    .Z(_24_)
  );
  NOR2BX0P5H7L _41_ (
    .AN(\rom_addr[1] ),
    .B(cpu_restart),
    .Z(_23_)
  );
  NOR2BX0P5H7L _42_ (
    .AN(\rom_addr[15] ),
    .B(cpu_restart),
    .Z(_22_)
  );
  NOR2BX0P5H7L _43_ (
    .AN(\rom_addr[14] ),
    .B(cpu_restart),
    .Z(_21_)
  );
  NOR2BX0P5H7L _44_ (
    .AN(\rom_addr[13] ),
    .B(cpu_restart),
    .Z(_20_)
  );
  NOR2BX0P5H7L _45_ (
    .AN(\rom_addr[12] ),
    .B(cpu_restart),
    .Z(_19_)
  );
  NOR2BX0P5H7L _46_ (
    .AN(\rom_addr[11] ),
    .B(cpu_restart),
    .Z(_18_)
  );
  NOR2BX0P5H7L _47_ (
    .AN(\rom_addr[10] ),
    .B(cpu_restart),
    .Z(_17_)
  );
  NOR2BX0P5H7L _48_ (
    .AN(\rom_addr[0] ),
    .B(cpu_restart),
    .Z(_16_)
  );
  INVX0P5H7R _49_ (
    .A(rst),
    .Y(_00_)
  );
  INVX0P5H7R _50_ (
    .A(rst),
    .Y(_01_)
  );
  INVX0P5H7R _51_ (
    .A(rst),
    .Y(_02_)
  );
  INVX0P5H7R _52_ (
    .A(rst),
    .Y(_03_)
  );
  INVX0P5H7R _53_ (
    .A(rst),
    .Y(_04_)
  );
  INVX0P5H7R _54_ (
    .A(rst),
    .Y(_05_)
  );
  INVX0P5H7R _55_ (
    .A(rst),
    .Y(_06_)
  );
  INVX0P5H7R _56_ (
    .A(rst),
    .Y(_07_)
  );
  INVX0P5H7R _57_ (
    .A(rst),
    .Y(_08_)
  );
  INVX0P5H7R _58_ (
    .A(rst),
    .Y(_09_)
  );
  INVX0P5H7R _59_ (
    .A(rst),
    .Y(_10_)
  );
  INVX0P5H7R _60_ (
    .A(rst),
    .Y(_11_)
  );
  INVX0P5H7R _61_ (
    .A(rst),
    .Y(_12_)
  );
  INVX0P5H7R _62_ (
    .A(rst),
    .Y(_13_)
  );
  INVX0P5H7R _63_ (
    .A(rst),
    .Y(_14_)
  );
  INVX0P5H7R _64_ (
    .A(rst),
    .Y(_15_)
  );
  TIELOH7R _65_ (
    .Z(_32_)
  );
  DFFRQX2H7R \rom_addr[0]_reg_p  (
    .CK(clk),
    .D(_16_),
    .Q(\rom_addr[0] ),
    .RN(_00_)
  );
  DFFRQX2H7R \rom_addr[10]_reg_p  (
    .CK(clk),
    .D(_17_),
    .Q(\rom_addr[10] ),
    .RN(_01_)
  );
  DFFRQX2H7R \rom_addr[11]_reg_p  (
    .CK(clk),
    .D(_18_),
    .Q(\rom_addr[11] ),
    .RN(_02_)
  );
  DFFRQX2H7R \rom_addr[12]_reg_p  (
    .CK(clk),
    .D(_19_),
    .Q(\rom_addr[12] ),
    .RN(_03_)
  );
  DFFRQX2H7R \rom_addr[13]_reg_p  (
    .CK(clk),
    .D(_20_),
    .Q(\rom_addr[13] ),
    .RN(_04_)
  );
  DFFRQX2H7R \rom_addr[14]_reg_p  (
    .CK(clk),
    .D(_21_),
    .Q(\rom_addr[14] ),
    .RN(_05_)
  );
  DFFRQX2H7R \rom_addr[15]_reg_p  (
    .CK(clk),
    .D(_22_),
    .Q(\rom_addr[15] ),
    .RN(_06_)
  );
  DFFRQX2H7R \rom_addr[1]_reg_p  (
    .CK(clk),
    .D(_23_),
    .Q(\rom_addr[1] ),
    .RN(_07_)
  );
  DFFRQX2H7R \rom_addr[2]_reg_p  (
    .CK(clk),
    .D(_24_),
    .Q(\rom_addr[2] ),
    .RN(_08_)
  );
  DFFRQX2H7R \rom_addr[3]_reg_p  (
    .CK(clk),
    .D(_25_),
    .Q(\rom_addr[3] ),
    .RN(_09_)
  );
  DFFRQX2H7R \rom_addr[4]_reg_p  (
    .CK(clk),
    .D(_26_),
    .Q(\rom_addr[4] ),
    .RN(_10_)
  );
  DFFRQX2H7R \rom_addr[5]_reg_p  (
    .CK(clk),
    .D(_27_),
    .Q(\rom_addr[5] ),
    .RN(_11_)
  );
  DFFRQX2H7R \rom_addr[6]_reg_p  (
    .CK(clk),
    .D(_28_),
    .Q(\rom_addr[6] ),
    .RN(_12_)
  );
  DFFRQX2H7R \rom_addr[7]_reg_p  (
    .CK(clk),
    .D(_29_),
    .Q(\rom_addr[7] ),
    .RN(_13_)
  );
  DFFRQX2H7R \rom_addr[8]_reg_p  (
    .CK(clk),
    .D(_30_),
    .Q(\rom_addr[8] ),
    .RN(_14_)
  );
  DFFRQX2H7R \rom_addr[9]_reg_p  (
    .CK(clk),
    .D(_31_),
    .Q(\rom_addr[9] ),
    .RN(_15_)
  );
  assign \ram_wr_byte[1]  = _32_;
  assign \ram_wr_byte[0]  = _32_;
  assign \ram_wr_addr[15]  = _32_;
  assign \ram_wr_addr[14]  = _32_;
  assign \ram_wr_addr[13]  = _32_;
  assign \ram_wr_addr[12]  = _32_;
  assign \ram_wr_addr[11]  = _32_;
  assign \ram_wr_addr[10]  = _32_;
  assign \ram_wr_addr[9]  = _32_;
  assign \ram_wr_addr[8]  = _32_;
  assign \ram_wr_addr[7]  = _32_;
  assign \ram_wr_addr[6]  = _32_;
  assign \ram_wr_addr[5]  = _32_;
  assign \ram_wr_addr[4]  = _32_;
  assign \ram_wr_addr[3]  = _32_;
  assign \ram_wr_addr[2]  = _32_;
  assign \ram_wr_addr[1]  = _32_;
  assign \ram_wr_addr[0]  = _32_;
  assign \ram_rd_addr[15]  = _32_;
  assign \ram_rd_addr[14]  = _32_;
  assign \ram_rd_addr[13]  = _32_;
  assign \ram_rd_addr[12]  = _32_;
  assign \ram_rd_addr[11]  = _32_;
  assign \ram_rd_addr[10]  = _32_;
  assign \ram_rd_addr[9]  = _32_;
  assign \ram_rd_addr[8]  = _32_;
  assign \ram_rd_addr[7]  = _32_;
  assign \ram_rd_addr[6]  = _32_;
  assign \ram_rd_addr[5]  = _32_;
  assign \ram_rd_addr[4]  = _32_;
  assign \ram_rd_addr[3]  = _32_;
  assign \ram_rd_addr[2]  = _32_;
  assign \ram_rd_addr[1]  = _32_;
  assign \ram_rd_addr[0]  = _32_;
  assign \ram_wr_byte[3]  = _32_;
  assign \ram_wr_byte[4]  = _32_;
  assign ram_rd_en_data = _32_;
  assign ram_rd_en_sfr = _32_;
  assign ram_rd_en_xdata = _32_;
  assign \ram_wr_byte[6]  = _32_;
  assign \ram_wr_byte[7]  = _32_;
  assign ram_wr_en_data = _32_;
  assign ram_wr_en_sfr = _32_;
  assign ram_wr_en_xdata = _32_;
  assign \ram_wr_byte[5]  = _32_;
  assign \ram_wr_byte[2]  = _32_;
  assign rom_en = _32_;
endmodule
