/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module Sync_FIFO(clk, rd_en, wr_en, rst, \buf_in[0] , \buf_in[1] , \buf_in[2] , \buf_in[3] , \buf_in[4] , \buf_in[5] , \buf_in[6] , \buf_in[7] , \buf_out[0] , \buf_out[1] , \buf_out[2] , \buf_out[3] , \buf_out[4] , \buf_out[5] , \buf_out[6] , \buf_out[7] , buf_empty
, buf_full, \fifo_counter[0] , \fifo_counter[1] , \fifo_counter[2] , \fifo_counter[3] );
  input clk;
  wire clk;
  input rd_en;
  wire rd_en;
  input wr_en;
  wire wr_en;
  input rst;
  wire rst;
  input \buf_in[0] ;
  wire \buf_in[0] ;
  input \buf_in[1] ;
  wire \buf_in[1] ;
  input \buf_in[2] ;
  wire \buf_in[2] ;
  input \buf_in[3] ;
  wire \buf_in[3] ;
  input \buf_in[4] ;
  wire \buf_in[4] ;
  input \buf_in[5] ;
  wire \buf_in[5] ;
  input \buf_in[6] ;
  wire \buf_in[6] ;
  input \buf_in[7] ;
  wire \buf_in[7] ;
  output \buf_out[0] ;
  wire \buf_out[0] ;
  output \buf_out[1] ;
  wire \buf_out[1] ;
  output \buf_out[2] ;
  wire \buf_out[2] ;
  output \buf_out[3] ;
  wire \buf_out[3] ;
  output \buf_out[4] ;
  wire \buf_out[4] ;
  output \buf_out[5] ;
  wire \buf_out[5] ;
  output \buf_out[6] ;
  wire \buf_out[6] ;
  output \buf_out[7] ;
  wire \buf_out[7] ;
  output buf_empty;
  wire buf_empty;
  output buf_full;
  wire buf_full;
  output \fifo_counter[0] ;
  wire \fifo_counter[0] ;
  output \fifo_counter[1] ;
  wire \fifo_counter[1] ;
  output \fifo_counter[2] ;
  wire \fifo_counter[2] ;
  output \fifo_counter[3] ;
  wire \fifo_counter[3] ;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire \buf_mem[0]_0_ ;
  wire \buf_mem[0]_1_ ;
  wire \buf_mem[0]_2_ ;
  wire \buf_mem[0]_3_ ;
  wire \buf_mem[0]_4_ ;
  wire \buf_mem[0]_5_ ;
  wire \buf_mem[0]_6_ ;
  wire \buf_mem[0]_7_ ;
  wire \buf_mem[1]_0_ ;
  wire \buf_mem[1]_1_ ;
  wire \buf_mem[1]_2_ ;
  wire \buf_mem[1]_3_ ;
  wire \buf_mem[1]_4_ ;
  wire \buf_mem[1]_5_ ;
  wire \buf_mem[1]_6_ ;
  wire \buf_mem[1]_7_ ;
  wire \buf_mem[2]_0_ ;
  wire \buf_mem[2]_1_ ;
  wire \buf_mem[2]_2_ ;
  wire \buf_mem[2]_3_ ;
  wire \buf_mem[2]_4_ ;
  wire \buf_mem[2]_5_ ;
  wire \buf_mem[2]_6_ ;
  wire \buf_mem[2]_7_ ;
  wire \buf_mem[3]_0_ ;
  wire \buf_mem[3]_1_ ;
  wire \buf_mem[3]_2_ ;
  wire \buf_mem[3]_3_ ;
  wire \buf_mem[3]_4_ ;
  wire \buf_mem[3]_5_ ;
  wire \buf_mem[3]_6_ ;
  wire \buf_mem[3]_7_ ;
  wire \buf_mem[4]_0_ ;
  wire \buf_mem[4]_1_ ;
  wire \buf_mem[4]_2_ ;
  wire \buf_mem[4]_3_ ;
  wire \buf_mem[4]_4_ ;
  wire \buf_mem[4]_5_ ;
  wire \buf_mem[4]_6_ ;
  wire \buf_mem[4]_7_ ;
  wire \buf_mem[5]_0_ ;
  wire \buf_mem[5]_1_ ;
  wire \buf_mem[5]_2_ ;
  wire \buf_mem[5]_3_ ;
  wire \buf_mem[5]_4_ ;
  wire \buf_mem[5]_5_ ;
  wire \buf_mem[5]_6_ ;
  wire \buf_mem[5]_7_ ;
  wire \buf_mem[6]_0_ ;
  wire \buf_mem[6]_1_ ;
  wire \buf_mem[6]_2_ ;
  wire \buf_mem[6]_3_ ;
  wire \buf_mem[6]_4_ ;
  wire \buf_mem[6]_5_ ;
  wire \buf_mem[6]_6_ ;
  wire \buf_mem[6]_7_ ;
  wire \buf_mem[7]_0_ ;
  wire \buf_mem[7]_1_ ;
  wire \buf_mem[7]_2_ ;
  wire \buf_mem[7]_3_ ;
  wire \buf_mem[7]_4_ ;
  wire \buf_mem[7]_5_ ;
  wire \buf_mem[7]_6_ ;
  wire \buf_mem[7]_7_ ;
  wire rd_ptr_0_;
  wire rd_ptr_1_;
  wire rd_ptr_2_;
  wire wr_ptr_0_;
  wire wr_ptr_1_;
  wire wr_ptr_2_;
  INVX2P5H7L _171_ (
    .A(wr_ptr_1_),
    .Y(_100_)
  );
  NAND2BX8H7L _172_ (
    .AN(\fifo_counter[1] ),
    .B(\fifo_counter[3] ),
    .Y(_101_)
  );
  OR2X8H7L _173_ (
    .A(\fifo_counter[2] ),
    .B(\fifo_counter[0] ),
    .Y(_102_)
  );
  OAI211X6H7L _174_ (
    .A0(_101_),
    .A1(_102_),
    .B0(wr_ptr_0_),
    .C0(wr_en),
    .Y(_103_)
  );
  NOR3X1P4H7L _175_ (
    .A(wr_ptr_2_),
    .B(_100_),
    .C(_103_),
    .Y(_104_)
  );
  BUFX5H7L _176_ (
    .A(_104_),
    .Y(_105_)
  );
  OAI21X0P5H7R _177_ (
    .A0(_100_),
    .A1(_103_),
    .B0(wr_ptr_2_),
    .Y(_106_)
  );
  NAND2BX0P5H7R _178_ (
    .AN(_105_),
    .B(_106_),
    .Y(_099_)
  );
  XNOR2X0P5H7R _179_ (
    .A(wr_ptr_1_),
    .B(_103_),
    .Y(_098_)
  );
  INVX1P4H7L _180_ (
    .A(wr_ptr_0_),
    .Y(_107_)
  );
  OAI211X6H7L _181_ (
    .A0(_101_),
    .A1(_102_),
    .B0(_107_),
    .C0(wr_en),
    .Y(_108_)
  );
  OAI21X0P5H7R _182_ (
    .A0(_101_),
    .A1(_102_),
    .B0(wr_en),
    .Y(_109_)
  );
  NAND2X0P5H7R _183_ (
    .A(wr_ptr_0_),
    .B(_109_),
    .Y(_110_)
  );
  NAND2X0P5H7R _184_ (
    .A(_108_),
    .B(_110_),
    .Y(_097_)
  );
  OR4X3H7L _185_ (
    .A(\fifo_counter[3] ),
    .B(\fifo_counter[2] ),
    .C(\fifo_counter[1] ),
    .D(\fifo_counter[0] ),
    .Y(_111_)
  );
  AND2X8H7L _186_ (
    .A(rd_en),
    .B(_111_),
    .Y(_112_)
  );
  NAND3X1P4H7L _187_ (
    .A(rd_ptr_1_),
    .B(rd_ptr_0_),
    .C(_112_),
    .Y(_113_)
  );
  XNOR2X0P5H7R _188_ (
    .A(rd_ptr_2_),
    .B(_113_),
    .Y(_096_)
  );
  BUFX20H7L _189_ (
    .A(_112_),
    .Y(_114_)
  );
  NAND2X6H7L _190_ (
    .A(rd_ptr_0_),
    .B(_114_),
    .Y(_115_)
  );
  XNOR2X4H7L _191_ (
    .A(rd_ptr_1_),
    .B(_115_),
    .Y(_095_)
  );
  XOR2X3H7L _192_ (
    .A(rd_ptr_0_),
    .B(_114_),
    .Y(_094_)
  );
  INVX0P5H7R _193_ (
    .A(\fifo_counter[3] ),
    .Y(_116_)
  );
  INVX0P5H7R _194_ (
    .A(\fifo_counter[1] ),
    .Y(_117_)
  );
  NAND3BX2H7L _195_ (
    .AN(rd_en),
    .B(wr_en),
    .C(\fifo_counter[0] ),
    .Y(_118_)
  );
  OR2X1P4H7L _196_ (
    .A(_117_),
    .B(_118_),
    .Y(_119_)
  );
  NAND2X0P5H7R _197_ (
    .A(\fifo_counter[3] ),
    .B(\fifo_counter[2] ),
    .Y(_120_)
  );
  NOR2X0P5H7R _198_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NAND2BX0P5H7R _199_ (
    .AN(\fifo_counter[0] ),
    .B(rd_en),
    .Y(_122_)
  );
  OAOI211X0P5H7R _200_ (
    .A0(\fifo_counter[1] ),
    .A1(_122_),
    .B0(\fifo_counter[3] ),
    .C0(\fifo_counter[2] ),
    .Y(_123_)
  );
  AOI211X0P5H7R _201_ (
    .A0(_116_),
    .A1(_119_),
    .B0(_121_),
    .C0(_123_),
    .Y(_093_)
  );
  OAOI211X0P5H7R _202_ (
    .A0(_101_),
    .A1(_122_),
    .B0(_119_),
    .C0(\fifo_counter[2] ),
    .Y(_124_)
  );
  NOR2BX1P4H7L _203_ (
    .AN(rd_en),
    .B(\fifo_counter[0] ),
    .Z(_125_)
  );
  NAND2BX0P5H7R _204_ (
    .AN(wr_en),
    .B(_125_),
    .Y(_126_)
  );
  OAI211X0P7H7L _205_ (
    .A0(\fifo_counter[1] ),
    .A1(_126_),
    .B0(_119_),
    .C0(\fifo_counter[2] ),
    .Y(_127_)
  );
  NAND2BX0P7H7L _206_ (
    .AN(_124_),
    .B(_127_),
    .Y(_092_)
  );
  NAND2X0P5H7R _207_ (
    .A(\fifo_counter[2] ),
    .B(wr_en),
    .Y(_128_)
  );
  OAI211X1P4H7L _208_ (
    .A0(\fifo_counter[3] ),
    .A1(\fifo_counter[2] ),
    .B0(rd_en),
    .C0(_128_),
    .Y(_129_)
  );
  OAI211X1H7L _209_ (
    .A0(\fifo_counter[0] ),
    .A1(_129_),
    .B0(_118_),
    .C0(_117_),
    .Y(_130_)
  );
  AOA211X0P7H7L _210_ (
    .A0(_118_),
    .A1(_126_),
    .B0(_117_),
    .C0(_130_),
    .Y(_091_)
  );
  NOR2BX1P4H7L _211_ (
    .AN(\fifo_counter[0] ),
    .B(rd_en),
    .Z(_131_)
  );
  AOI21X0P5H7R _212_ (
    .A0(_111_),
    .A1(_125_),
    .B0(_131_),
    .Y(_132_)
  );
  XOR2X0P5H7R _213_ (
    .A(_109_),
    .B(_132_),
    .Y(_090_)
  );
  MUX4X1P4H7R _214_ (
    .A(\buf_mem[0]_7_ ),
    .B(\buf_mem[1]_7_ ),
    .C(\buf_mem[2]_7_ ),
    .D(\buf_mem[3]_7_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_133_)
  );
  MUX4X1P4H7R _215_ (
    .A(\buf_mem[4]_7_ ),
    .B(\buf_mem[5]_7_ ),
    .C(\buf_mem[6]_7_ ),
    .D(\buf_mem[7]_7_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_134_)
  );
  MUX2X1P4H7L _216_ (
    .A(_133_),
    .B(_134_),
    .S0(rd_ptr_2_),
    .Y(_135_)
  );
  MUX2X0P5H7L _217_ (
    .A(\buf_out[7] ),
    .B(_135_),
    .S0(_114_),
    .Y(_089_)
  );
  MUX4X1P4H7R _218_ (
    .A(\buf_mem[0]_6_ ),
    .B(\buf_mem[1]_6_ ),
    .C(\buf_mem[2]_6_ ),
    .D(\buf_mem[3]_6_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_136_)
  );
  MUX4X1P4H7R _219_ (
    .A(\buf_mem[4]_6_ ),
    .B(\buf_mem[5]_6_ ),
    .C(\buf_mem[6]_6_ ),
    .D(\buf_mem[7]_6_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_137_)
  );
  MUX2X1P4H7L _220_ (
    .A(_136_),
    .B(_137_),
    .S0(rd_ptr_2_),
    .Y(_138_)
  );
  MUX2X0P5H7R _221_ (
    .A(\buf_out[6] ),
    .B(_138_),
    .S0(_114_),
    .Y(_088_)
  );
  MUX4X1P4H7R _222_ (
    .A(\buf_mem[0]_5_ ),
    .B(\buf_mem[1]_5_ ),
    .C(\buf_mem[2]_5_ ),
    .D(\buf_mem[3]_5_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_139_)
  );
  MUX4X1P4H7R _223_ (
    .A(\buf_mem[4]_5_ ),
    .B(\buf_mem[5]_5_ ),
    .C(\buf_mem[6]_5_ ),
    .D(\buf_mem[7]_5_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_140_)
  );
  MUX2X1P4H7L _224_ (
    .A(_139_),
    .B(_140_),
    .S0(rd_ptr_2_),
    .Y(_141_)
  );
  MUX2X0P5H7L _225_ (
    .A(\buf_out[5] ),
    .B(_141_),
    .S0(_114_),
    .Y(_087_)
  );
  MUX4X1P4H7R _226_ (
    .A(\buf_mem[0]_4_ ),
    .B(\buf_mem[1]_4_ ),
    .C(\buf_mem[2]_4_ ),
    .D(\buf_mem[3]_4_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_142_)
  );
  MUX4X1P4H7R _227_ (
    .A(\buf_mem[4]_4_ ),
    .B(\buf_mem[5]_4_ ),
    .C(\buf_mem[6]_4_ ),
    .D(\buf_mem[7]_4_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_143_)
  );
  MUX2X1P4H7L _228_ (
    .A(_142_),
    .B(_143_),
    .S0(rd_ptr_2_),
    .Y(_144_)
  );
  MUX2X0P5H7R _229_ (
    .A(\buf_out[4] ),
    .B(_144_),
    .S0(_114_),
    .Y(_086_)
  );
  MUX4X1P4H7R _230_ (
    .A(\buf_mem[0]_3_ ),
    .B(\buf_mem[1]_3_ ),
    .C(\buf_mem[2]_3_ ),
    .D(\buf_mem[3]_3_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_145_)
  );
  MUX4X1P4H7R _231_ (
    .A(\buf_mem[4]_3_ ),
    .B(\buf_mem[5]_3_ ),
    .C(\buf_mem[6]_3_ ),
    .D(\buf_mem[7]_3_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_146_)
  );
  MUX2X1P4H7L _232_ (
    .A(_145_),
    .B(_146_),
    .S0(rd_ptr_2_),
    .Y(_147_)
  );
  MUX2X0P5H7R _233_ (
    .A(\buf_out[3] ),
    .B(_147_),
    .S0(_114_),
    .Y(_085_)
  );
  MUX4X1P4H7R _234_ (
    .A(\buf_mem[0]_2_ ),
    .B(\buf_mem[1]_2_ ),
    .C(\buf_mem[2]_2_ ),
    .D(\buf_mem[3]_2_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_148_)
  );
  MUX4X1P4H7R _235_ (
    .A(\buf_mem[4]_2_ ),
    .B(\buf_mem[5]_2_ ),
    .C(\buf_mem[6]_2_ ),
    .D(\buf_mem[7]_2_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_149_)
  );
  MUX2X1P4H7L _236_ (
    .A(_148_),
    .B(_149_),
    .S0(rd_ptr_2_),
    .Y(_150_)
  );
  MUX2X0P5H7R _237_ (
    .A(\buf_out[2] ),
    .B(_150_),
    .S0(_114_),
    .Y(_084_)
  );
  MUX4X1P4H7R _238_ (
    .A(\buf_mem[0]_1_ ),
    .B(\buf_mem[1]_1_ ),
    .C(\buf_mem[2]_1_ ),
    .D(\buf_mem[3]_1_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_151_)
  );
  MUX4X1P4H7R _239_ (
    .A(\buf_mem[4]_1_ ),
    .B(\buf_mem[5]_1_ ),
    .C(\buf_mem[6]_1_ ),
    .D(\buf_mem[7]_1_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_152_)
  );
  MUX2X1P4H7L _240_ (
    .A(_151_),
    .B(_152_),
    .S0(rd_ptr_2_),
    .Y(_153_)
  );
  MUX2X0P5H7R _241_ (
    .A(\buf_out[1] ),
    .B(_153_),
    .S0(_114_),
    .Y(_083_)
  );
  MUX4X1P4H7R _242_ (
    .A(\buf_mem[0]_0_ ),
    .B(\buf_mem[1]_0_ ),
    .C(\buf_mem[2]_0_ ),
    .D(\buf_mem[3]_0_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_154_)
  );
  MUX4X1P4H7R _243_ (
    .A(\buf_mem[4]_0_ ),
    .B(\buf_mem[5]_0_ ),
    .C(\buf_mem[6]_0_ ),
    .D(\buf_mem[7]_0_ ),
    .S0(rd_ptr_0_),
    .S1(rd_ptr_1_),
    .Y(_155_)
  );
  MUX2X1P4H7L _244_ (
    .A(_154_),
    .B(_155_),
    .S0(rd_ptr_2_),
    .Y(_156_)
  );
  MUX2X0P5H7R _245_ (
    .A(\buf_out[0] ),
    .B(_156_),
    .S0(_114_),
    .Y(_082_)
  );
  INVX0P5H7R _246_ (
    .A(_111_),
    .Y(buf_empty)
  );
  NOR2X0P5H7R _247_ (
    .A(_101_),
    .B(_102_),
    .Y(buf_full)
  );
  INVX0P5H7R _248_ (
    .A(wr_ptr_2_),
    .Y(_157_)
  );
  NAND3BX1P4H7L _249_ (
    .AN(_108_),
    .B(_100_),
    .C(_157_),
    .Y(_158_)
  );
  BUFX7H7L _250_ (
    .A(_158_),
    .Y(_159_)
  );
  MUX2X0P5H7L _251_ (
    .A(\buf_in[0] ),
    .B(\buf_mem[0]_0_ ),
    .S0(_159_),
    .Y(_018_)
  );
  MUX2X0P5H7L _252_ (
    .A(\buf_in[1] ),
    .B(\buf_mem[0]_1_ ),
    .S0(_159_),
    .Y(_019_)
  );
  MUX2X0P5H7L _253_ (
    .A(\buf_in[2] ),
    .B(\buf_mem[0]_2_ ),
    .S0(_159_),
    .Y(_020_)
  );
  MUX2X0P5H7L _254_ (
    .A(\buf_in[3] ),
    .B(\buf_mem[0]_3_ ),
    .S0(_159_),
    .Y(_021_)
  );
  MUX2X0P5H7L _255_ (
    .A(\buf_in[4] ),
    .B(\buf_mem[0]_4_ ),
    .S0(_159_),
    .Y(_022_)
  );
  MUX2X0P5H7L _256_ (
    .A(\buf_in[5] ),
    .B(\buf_mem[0]_5_ ),
    .S0(_159_),
    .Y(_023_)
  );
  MUX2X0P5H7L _257_ (
    .A(\buf_in[6] ),
    .B(\buf_mem[0]_6_ ),
    .S0(_159_),
    .Y(_024_)
  );
  MUX2X0P5H7L _258_ (
    .A(\buf_in[7] ),
    .B(\buf_mem[0]_7_ ),
    .S0(_159_),
    .Y(_025_)
  );
  NOR3X1P4H7L _259_ (
    .A(wr_ptr_2_),
    .B(wr_ptr_1_),
    .C(_103_),
    .Y(_160_)
  );
  BUFX5H7L _260_ (
    .A(_160_),
    .Y(_161_)
  );
  MUX2X0P5H7R _261_ (
    .A(\buf_mem[1]_0_ ),
    .B(\buf_in[0] ),
    .S0(_161_),
    .Y(_026_)
  );
  MUX2X0P5H7R _262_ (
    .A(\buf_mem[1]_1_ ),
    .B(\buf_in[1] ),
    .S0(_161_),
    .Y(_027_)
  );
  MUX2X0P5H7R _263_ (
    .A(\buf_mem[1]_2_ ),
    .B(\buf_in[2] ),
    .S0(_161_),
    .Y(_028_)
  );
  MUX2X0P5H7R _264_ (
    .A(\buf_mem[1]_3_ ),
    .B(\buf_in[3] ),
    .S0(_161_),
    .Y(_029_)
  );
  MUX2X0P5H7R _265_ (
    .A(\buf_mem[1]_4_ ),
    .B(\buf_in[4] ),
    .S0(_161_),
    .Y(_030_)
  );
  MUX2X0P5H7R _266_ (
    .A(\buf_mem[1]_5_ ),
    .B(\buf_in[5] ),
    .S0(_161_),
    .Y(_031_)
  );
  MUX2X0P5H7R _267_ (
    .A(\buf_mem[1]_6_ ),
    .B(\buf_in[6] ),
    .S0(_161_),
    .Y(_032_)
  );
  MUX2X0P5H7R _268_ (
    .A(\buf_mem[1]_7_ ),
    .B(\buf_in[7] ),
    .S0(_161_),
    .Y(_033_)
  );
  NOR3X1P4H7L _269_ (
    .A(wr_ptr_2_),
    .B(_100_),
    .C(_108_),
    .Y(_162_)
  );
  BUFX5H7L _270_ (
    .A(_162_),
    .Y(_163_)
  );
  MUX2X0P5H7R _271_ (
    .A(\buf_mem[2]_0_ ),
    .B(\buf_in[0] ),
    .S0(_163_),
    .Y(_034_)
  );
  MUX2X0P5H7R _272_ (
    .A(\buf_mem[2]_1_ ),
    .B(\buf_in[1] ),
    .S0(_163_),
    .Y(_035_)
  );
  MUX2X0P5H7R _273_ (
    .A(\buf_mem[2]_2_ ),
    .B(\buf_in[2] ),
    .S0(_163_),
    .Y(_036_)
  );
  MUX2X0P5H7R _274_ (
    .A(\buf_mem[2]_3_ ),
    .B(\buf_in[3] ),
    .S0(_163_),
    .Y(_037_)
  );
  MUX2X0P5H7R _275_ (
    .A(\buf_mem[2]_4_ ),
    .B(\buf_in[4] ),
    .S0(_163_),
    .Y(_038_)
  );
  MUX2X0P5H7R _276_ (
    .A(\buf_mem[2]_5_ ),
    .B(\buf_in[5] ),
    .S0(_163_),
    .Y(_039_)
  );
  MUX2X0P5H7R _277_ (
    .A(\buf_mem[2]_6_ ),
    .B(\buf_in[6] ),
    .S0(_163_),
    .Y(_040_)
  );
  MUX2X0P5H7R _278_ (
    .A(\buf_mem[2]_7_ ),
    .B(\buf_in[7] ),
    .S0(_163_),
    .Y(_041_)
  );
  MUX2X0P5H7R _279_ (
    .A(\buf_mem[3]_0_ ),
    .B(\buf_in[0] ),
    .S0(_105_),
    .Y(_042_)
  );
  MUX2X0P5H7R _280_ (
    .A(\buf_mem[3]_1_ ),
    .B(\buf_in[1] ),
    .S0(_105_),
    .Y(_043_)
  );
  MUX2X0P5H7R _281_ (
    .A(\buf_mem[3]_2_ ),
    .B(\buf_in[2] ),
    .S0(_105_),
    .Y(_044_)
  );
  MUX2X0P5H7R _282_ (
    .A(\buf_mem[3]_3_ ),
    .B(\buf_in[3] ),
    .S0(_105_),
    .Y(_045_)
  );
  MUX2X0P5H7R _283_ (
    .A(\buf_mem[3]_4_ ),
    .B(\buf_in[4] ),
    .S0(_105_),
    .Y(_046_)
  );
  MUX2X0P5H7R _284_ (
    .A(\buf_mem[3]_5_ ),
    .B(\buf_in[5] ),
    .S0(_105_),
    .Y(_047_)
  );
  MUX2X0P5H7R _285_ (
    .A(\buf_mem[3]_6_ ),
    .B(\buf_in[6] ),
    .S0(_105_),
    .Y(_048_)
  );
  MUX2X0P5H7R _286_ (
    .A(\buf_mem[3]_7_ ),
    .B(\buf_in[7] ),
    .S0(_105_),
    .Y(_049_)
  );
  NAND2X1P4H7L _287_ (
    .A(wr_ptr_2_),
    .B(_100_),
    .Y(_164_)
  );
  NOR2X6H7L _288_ (
    .A(_108_),
    .B(_164_),
    .Y(_165_)
  );
  MUX2X0P5H7R _289_ (
    .A(\buf_mem[4]_0_ ),
    .B(\buf_in[0] ),
    .S0(_165_),
    .Y(_050_)
  );
  MUX2X0P5H7R _290_ (
    .A(\buf_mem[4]_1_ ),
    .B(\buf_in[1] ),
    .S0(_165_),
    .Y(_051_)
  );
  MUX2X0P5H7R _291_ (
    .A(\buf_mem[4]_2_ ),
    .B(\buf_in[2] ),
    .S0(_165_),
    .Y(_052_)
  );
  MUX2X0P5H7L _292_ (
    .A(\buf_mem[4]_3_ ),
    .B(\buf_in[3] ),
    .S0(_165_),
    .Y(_053_)
  );
  MUX2X0P5H7R _293_ (
    .A(\buf_mem[4]_4_ ),
    .B(\buf_in[4] ),
    .S0(_165_),
    .Y(_054_)
  );
  MUX2X0P5H7R _294_ (
    .A(\buf_mem[4]_5_ ),
    .B(\buf_in[5] ),
    .S0(_165_),
    .Y(_055_)
  );
  MUX2X0P5H7R _295_ (
    .A(\buf_mem[4]_6_ ),
    .B(\buf_in[6] ),
    .S0(_165_),
    .Y(_056_)
  );
  MUX2X0P5H7R _296_ (
    .A(\buf_mem[4]_7_ ),
    .B(\buf_in[7] ),
    .S0(_165_),
    .Y(_057_)
  );
  NOR2X6H7L _297_ (
    .A(_103_),
    .B(_164_),
    .Y(_166_)
  );
  MUX2X0P5H7R _298_ (
    .A(\buf_mem[5]_0_ ),
    .B(\buf_in[0] ),
    .S0(_166_),
    .Y(_058_)
  );
  MUX2X0P5H7R _299_ (
    .A(\buf_mem[5]_1_ ),
    .B(\buf_in[1] ),
    .S0(_166_),
    .Y(_059_)
  );
  MUX2X0P5H7R _300_ (
    .A(\buf_mem[5]_2_ ),
    .B(\buf_in[2] ),
    .S0(_166_),
    .Y(_060_)
  );
  MUX2X0P5H7L _301_ (
    .A(\buf_mem[5]_3_ ),
    .B(\buf_in[3] ),
    .S0(_166_),
    .Y(_061_)
  );
  MUX2X0P5H7R _302_ (
    .A(\buf_mem[5]_4_ ),
    .B(\buf_in[4] ),
    .S0(_166_),
    .Y(_062_)
  );
  MUX2X0P5H7R _303_ (
    .A(\buf_mem[5]_5_ ),
    .B(\buf_in[5] ),
    .S0(_166_),
    .Y(_063_)
  );
  MUX2X0P5H7R _304_ (
    .A(\buf_mem[5]_6_ ),
    .B(\buf_in[6] ),
    .S0(_166_),
    .Y(_064_)
  );
  MUX2X0P5H7R _305_ (
    .A(\buf_mem[5]_7_ ),
    .B(\buf_in[7] ),
    .S0(_166_),
    .Y(_065_)
  );
  OR3X1P4H7L _306_ (
    .A(_157_),
    .B(_100_),
    .C(_108_),
    .Y(_167_)
  );
  BUFX5H7L _307_ (
    .A(_167_),
    .Y(_168_)
  );
  MUX2X0P5H7L _308_ (
    .A(\buf_in[0] ),
    .B(\buf_mem[6]_0_ ),
    .S0(_168_),
    .Y(_066_)
  );
  MUX2X0P5H7L _309_ (
    .A(\buf_in[1] ),
    .B(\buf_mem[6]_1_ ),
    .S0(_168_),
    .Y(_067_)
  );
  MUX2X0P5H7L _310_ (
    .A(\buf_in[2] ),
    .B(\buf_mem[6]_2_ ),
    .S0(_168_),
    .Y(_068_)
  );
  MUX2X0P5H7L _311_ (
    .A(\buf_in[3] ),
    .B(\buf_mem[6]_3_ ),
    .S0(_168_),
    .Y(_069_)
  );
  MUX2X0P5H7L _312_ (
    .A(\buf_in[4] ),
    .B(\buf_mem[6]_4_ ),
    .S0(_168_),
    .Y(_070_)
  );
  MUX2X0P5H7L _313_ (
    .A(\buf_in[5] ),
    .B(\buf_mem[6]_5_ ),
    .S0(_168_),
    .Y(_071_)
  );
  MUX2X0P5H7L _314_ (
    .A(\buf_in[6] ),
    .B(\buf_mem[6]_6_ ),
    .S0(_168_),
    .Y(_072_)
  );
  MUX2X0P5H7L _315_ (
    .A(\buf_in[7] ),
    .B(\buf_mem[6]_7_ ),
    .S0(_168_),
    .Y(_073_)
  );
  OR3X1P4H7L _316_ (
    .A(_157_),
    .B(_100_),
    .C(_103_),
    .Y(_169_)
  );
  BUFX7H7L _317_ (
    .A(_169_),
    .Y(_170_)
  );
  MUX2X0P5H7L _318_ (
    .A(\buf_in[0] ),
    .B(\buf_mem[7]_0_ ),
    .S0(_170_),
    .Y(_074_)
  );
  MUX2X0P5H7L _319_ (
    .A(\buf_in[1] ),
    .B(\buf_mem[7]_1_ ),
    .S0(_170_),
    .Y(_075_)
  );
  MUX2X0P5H7L _320_ (
    .A(\buf_in[2] ),
    .B(\buf_mem[7]_2_ ),
    .S0(_170_),
    .Y(_076_)
  );
  MUX2X0P5H7L _321_ (
    .A(\buf_in[3] ),
    .B(\buf_mem[7]_3_ ),
    .S0(_170_),
    .Y(_077_)
  );
  MUX2X0P5H7L _322_ (
    .A(\buf_in[4] ),
    .B(\buf_mem[7]_4_ ),
    .S0(_170_),
    .Y(_078_)
  );
  MUX2X0P5H7L _323_ (
    .A(\buf_in[5] ),
    .B(\buf_mem[7]_5_ ),
    .S0(_170_),
    .Y(_079_)
  );
  MUX2X0P5H7L _324_ (
    .A(\buf_in[6] ),
    .B(\buf_mem[7]_6_ ),
    .S0(_170_),
    .Y(_080_)
  );
  MUX2X0P5H7L _325_ (
    .A(\buf_in[7] ),
    .B(\buf_mem[7]_7_ ),
    .S0(_170_),
    .Y(_081_)
  );
  INVX0P5H7R _326_ (
    .A(rst),
    .Y(_000_)
  );
  INVX0P5H7R _327_ (
    .A(rst),
    .Y(_001_)
  );
  INVX0P5H7R _328_ (
    .A(rst),
    .Y(_002_)
  );
  INVX0P5H7R _329_ (
    .A(rst),
    .Y(_003_)
  );
  INVX0P5H7R _330_ (
    .A(rst),
    .Y(_004_)
  );
  INVX0P5H7R _331_ (
    .A(rst),
    .Y(_005_)
  );
  INVX0P5H7R _332_ (
    .A(rst),
    .Y(_006_)
  );
  INVX0P5H7R _333_ (
    .A(rst),
    .Y(_007_)
  );
  INVX0P5H7R _334_ (
    .A(rst),
    .Y(_008_)
  );
  INVX0P5H7R _335_ (
    .A(rst),
    .Y(_009_)
  );
  INVX0P5H7R _336_ (
    .A(rst),
    .Y(_010_)
  );
  INVX0P5H7R _337_ (
    .A(rst),
    .Y(_011_)
  );
  INVX0P5H7R _338_ (
    .A(rst),
    .Y(_012_)
  );
  INVX0P5H7R _339_ (
    .A(rst),
    .Y(_013_)
  );
  INVX0P5H7R _340_ (
    .A(rst),
    .Y(_014_)
  );
  INVX0P5H7R _341_ (
    .A(rst),
    .Y(_015_)
  );
  INVX0P5H7R _342_ (
    .A(rst),
    .Y(_016_)
  );
  INVX0P5H7R _343_ (
    .A(rst),
    .Y(_017_)
  );
  DFFQX1H7R \buf_mem[0]_0__reg_p  (
    .CK(clk),
    .D(_018_),
    .Q(\buf_mem[0]_0_ )
  );
  DFFQX1H7R \buf_mem[0]_1__reg_p  (
    .CK(clk),
    .D(_019_),
    .Q(\buf_mem[0]_1_ )
  );
  DFFQX1H7R \buf_mem[0]_2__reg_p  (
    .CK(clk),
    .D(_020_),
    .Q(\buf_mem[0]_2_ )
  );
  DFFQX1H7R \buf_mem[0]_3__reg_p  (
    .CK(clk),
    .D(_021_),
    .Q(\buf_mem[0]_3_ )
  );
  DFFQX1H7R \buf_mem[0]_4__reg_p  (
    .CK(clk),
    .D(_022_),
    .Q(\buf_mem[0]_4_ )
  );
  DFFQX1H7R \buf_mem[0]_5__reg_p  (
    .CK(clk),
    .D(_023_),
    .Q(\buf_mem[0]_5_ )
  );
  DFFQX1H7R \buf_mem[0]_6__reg_p  (
    .CK(clk),
    .D(_024_),
    .Q(\buf_mem[0]_6_ )
  );
  DFFQX1H7R \buf_mem[0]_7__reg_p  (
    .CK(clk),
    .D(_025_),
    .Q(\buf_mem[0]_7_ )
  );
  DFFQX1H7R \buf_mem[1]_0__reg_p  (
    .CK(clk),
    .D(_026_),
    .Q(\buf_mem[1]_0_ )
  );
  DFFQX1H7R \buf_mem[1]_1__reg_p  (
    .CK(clk),
    .D(_027_),
    .Q(\buf_mem[1]_1_ )
  );
  DFFQX1H7R \buf_mem[1]_2__reg_p  (
    .CK(clk),
    .D(_028_),
    .Q(\buf_mem[1]_2_ )
  );
  DFFQX1H7R \buf_mem[1]_3__reg_p  (
    .CK(clk),
    .D(_029_),
    .Q(\buf_mem[1]_3_ )
  );
  DFFQX1H7R \buf_mem[1]_4__reg_p  (
    .CK(clk),
    .D(_030_),
    .Q(\buf_mem[1]_4_ )
  );
  DFFQX1H7R \buf_mem[1]_5__reg_p  (
    .CK(clk),
    .D(_031_),
    .Q(\buf_mem[1]_5_ )
  );
  DFFQX1H7R \buf_mem[1]_6__reg_p  (
    .CK(clk),
    .D(_032_),
    .Q(\buf_mem[1]_6_ )
  );
  DFFQX1H7R \buf_mem[1]_7__reg_p  (
    .CK(clk),
    .D(_033_),
    .Q(\buf_mem[1]_7_ )
  );
  DFFQX1H7R \buf_mem[2]_0__reg_p  (
    .CK(clk),
    .D(_034_),
    .Q(\buf_mem[2]_0_ )
  );
  DFFQX1H7R \buf_mem[2]_1__reg_p  (
    .CK(clk),
    .D(_035_),
    .Q(\buf_mem[2]_1_ )
  );
  DFFQX1H7R \buf_mem[2]_2__reg_p  (
    .CK(clk),
    .D(_036_),
    .Q(\buf_mem[2]_2_ )
  );
  DFFQX1H7R \buf_mem[2]_3__reg_p  (
    .CK(clk),
    .D(_037_),
    .Q(\buf_mem[2]_3_ )
  );
  DFFQX1H7R \buf_mem[2]_4__reg_p  (
    .CK(clk),
    .D(_038_),
    .Q(\buf_mem[2]_4_ )
  );
  DFFQX1H7R \buf_mem[2]_5__reg_p  (
    .CK(clk),
    .D(_039_),
    .Q(\buf_mem[2]_5_ )
  );
  DFFQX1H7R \buf_mem[2]_6__reg_p  (
    .CK(clk),
    .D(_040_),
    .Q(\buf_mem[2]_6_ )
  );
  DFFQX1H7R \buf_mem[2]_7__reg_p  (
    .CK(clk),
    .D(_041_),
    .Q(\buf_mem[2]_7_ )
  );
  DFFQX1H7R \buf_mem[3]_0__reg_p  (
    .CK(clk),
    .D(_042_),
    .Q(\buf_mem[3]_0_ )
  );
  DFFQX1H7R \buf_mem[3]_1__reg_p  (
    .CK(clk),
    .D(_043_),
    .Q(\buf_mem[3]_1_ )
  );
  DFFQX1H7R \buf_mem[3]_2__reg_p  (
    .CK(clk),
    .D(_044_),
    .Q(\buf_mem[3]_2_ )
  );
  DFFQX1H7R \buf_mem[3]_3__reg_p  (
    .CK(clk),
    .D(_045_),
    .Q(\buf_mem[3]_3_ )
  );
  DFFQX1H7R \buf_mem[3]_4__reg_p  (
    .CK(clk),
    .D(_046_),
    .Q(\buf_mem[3]_4_ )
  );
  DFFQX1H7R \buf_mem[3]_5__reg_p  (
    .CK(clk),
    .D(_047_),
    .Q(\buf_mem[3]_5_ )
  );
  DFFQX1H7R \buf_mem[3]_6__reg_p  (
    .CK(clk),
    .D(_048_),
    .Q(\buf_mem[3]_6_ )
  );
  DFFQX1H7R \buf_mem[3]_7__reg_p  (
    .CK(clk),
    .D(_049_),
    .Q(\buf_mem[3]_7_ )
  );
  DFFQX1H7R \buf_mem[4]_0__reg_p  (
    .CK(clk),
    .D(_050_),
    .Q(\buf_mem[4]_0_ )
  );
  DFFQX1H7R \buf_mem[4]_1__reg_p  (
    .CK(clk),
    .D(_051_),
    .Q(\buf_mem[4]_1_ )
  );
  DFFQX1H7R \buf_mem[4]_2__reg_p  (
    .CK(clk),
    .D(_052_),
    .Q(\buf_mem[4]_2_ )
  );
  DFFQX1H7R \buf_mem[4]_3__reg_p  (
    .CK(clk),
    .D(_053_),
    .Q(\buf_mem[4]_3_ )
  );
  DFFQX1H7R \buf_mem[4]_4__reg_p  (
    .CK(clk),
    .D(_054_),
    .Q(\buf_mem[4]_4_ )
  );
  DFFQX1H7R \buf_mem[4]_5__reg_p  (
    .CK(clk),
    .D(_055_),
    .Q(\buf_mem[4]_5_ )
  );
  DFFQX1H7R \buf_mem[4]_6__reg_p  (
    .CK(clk),
    .D(_056_),
    .Q(\buf_mem[4]_6_ )
  );
  DFFQX1H7R \buf_mem[4]_7__reg_p  (
    .CK(clk),
    .D(_057_),
    .Q(\buf_mem[4]_7_ )
  );
  DFFQX1H7R \buf_mem[5]_0__reg_p  (
    .CK(clk),
    .D(_058_),
    .Q(\buf_mem[5]_0_ )
  );
  DFFQX1H7R \buf_mem[5]_1__reg_p  (
    .CK(clk),
    .D(_059_),
    .Q(\buf_mem[5]_1_ )
  );
  DFFQX1H7R \buf_mem[5]_2__reg_p  (
    .CK(clk),
    .D(_060_),
    .Q(\buf_mem[5]_2_ )
  );
  DFFQX1H7R \buf_mem[5]_3__reg_p  (
    .CK(clk),
    .D(_061_),
    .Q(\buf_mem[5]_3_ )
  );
  DFFQX1H7R \buf_mem[5]_4__reg_p  (
    .CK(clk),
    .D(_062_),
    .Q(\buf_mem[5]_4_ )
  );
  DFFQX1H7R \buf_mem[5]_5__reg_p  (
    .CK(clk),
    .D(_063_),
    .Q(\buf_mem[5]_5_ )
  );
  DFFQX1H7R \buf_mem[5]_6__reg_p  (
    .CK(clk),
    .D(_064_),
    .Q(\buf_mem[5]_6_ )
  );
  DFFQX1H7R \buf_mem[5]_7__reg_p  (
    .CK(clk),
    .D(_065_),
    .Q(\buf_mem[5]_7_ )
  );
  DFFQX1H7R \buf_mem[6]_0__reg_p  (
    .CK(clk),
    .D(_066_),
    .Q(\buf_mem[6]_0_ )
  );
  DFFQX1H7R \buf_mem[6]_1__reg_p  (
    .CK(clk),
    .D(_067_),
    .Q(\buf_mem[6]_1_ )
  );
  DFFQX1H7R \buf_mem[6]_2__reg_p  (
    .CK(clk),
    .D(_068_),
    .Q(\buf_mem[6]_2_ )
  );
  DFFQX1H7R \buf_mem[6]_3__reg_p  (
    .CK(clk),
    .D(_069_),
    .Q(\buf_mem[6]_3_ )
  );
  DFFQX1H7R \buf_mem[6]_4__reg_p  (
    .CK(clk),
    .D(_070_),
    .Q(\buf_mem[6]_4_ )
  );
  DFFQX1H7R \buf_mem[6]_5__reg_p  (
    .CK(clk),
    .D(_071_),
    .Q(\buf_mem[6]_5_ )
  );
  DFFQX1H7R \buf_mem[6]_6__reg_p  (
    .CK(clk),
    .D(_072_),
    .Q(\buf_mem[6]_6_ )
  );
  DFFQX1H7R \buf_mem[6]_7__reg_p  (
    .CK(clk),
    .D(_073_),
    .Q(\buf_mem[6]_7_ )
  );
  DFFQX1H7R \buf_mem[7]_0__reg_p  (
    .CK(clk),
    .D(_074_),
    .Q(\buf_mem[7]_0_ )
  );
  DFFQX1H7R \buf_mem[7]_1__reg_p  (
    .CK(clk),
    .D(_075_),
    .Q(\buf_mem[7]_1_ )
  );
  DFFQX1H7R \buf_mem[7]_2__reg_p  (
    .CK(clk),
    .D(_076_),
    .Q(\buf_mem[7]_2_ )
  );
  DFFQX1H7R \buf_mem[7]_3__reg_p  (
    .CK(clk),
    .D(_077_),
    .Q(\buf_mem[7]_3_ )
  );
  DFFQX1H7R \buf_mem[7]_4__reg_p  (
    .CK(clk),
    .D(_078_),
    .Q(\buf_mem[7]_4_ )
  );
  DFFQX1H7R \buf_mem[7]_5__reg_p  (
    .CK(clk),
    .D(_079_),
    .Q(\buf_mem[7]_5_ )
  );
  DFFQX1H7R \buf_mem[7]_6__reg_p  (
    .CK(clk),
    .D(_080_),
    .Q(\buf_mem[7]_6_ )
  );
  DFFQX1H7R \buf_mem[7]_7__reg_p  (
    .CK(clk),
    .D(_081_),
    .Q(\buf_mem[7]_7_ )
  );
  DFFRQX2H7R \buf_out[0]_reg_p  (
    .CK(clk),
    .D(_082_),
    .Q(\buf_out[0] ),
    .RN(_000_)
  );
  DFFRQX2H7R \buf_out[1]_reg_p  (
    .CK(clk),
    .D(_083_),
    .Q(\buf_out[1] ),
    .RN(_001_)
  );
  DFFRQX2H7R \buf_out[2]_reg_p  (
    .CK(clk),
    .D(_084_),
    .Q(\buf_out[2] ),
    .RN(_002_)
  );
  DFFRQX2H7R \buf_out[3]_reg_p  (
    .CK(clk),
    .D(_085_),
    .Q(\buf_out[3] ),
    .RN(_003_)
  );
  DFFRQX2H7R \buf_out[4]_reg_p  (
    .CK(clk),
    .D(_086_),
    .Q(\buf_out[4] ),
    .RN(_004_)
  );
  DFFRQX2H7R \buf_out[5]_reg_p  (
    .CK(clk),
    .D(_087_),
    .Q(\buf_out[5] ),
    .RN(_005_)
  );
  DFFRQX2H7R \buf_out[6]_reg_p  (
    .CK(clk),
    .D(_088_),
    .Q(\buf_out[6] ),
    .RN(_006_)
  );
  DFFRQX2H7R \buf_out[7]_reg_p  (
    .CK(clk),
    .D(_089_),
    .Q(\buf_out[7] ),
    .RN(_007_)
  );
  DFFRQX2H7R \fifo_counter[0]_reg_p  (
    .CK(clk),
    .D(_090_),
    .Q(\fifo_counter[0] ),
    .RN(_008_)
  );
  DFFRQX2H7R \fifo_counter[1]_reg_p  (
    .CK(clk),
    .D(_091_),
    .Q(\fifo_counter[1] ),
    .RN(_009_)
  );
  DFFRQX2H7R \fifo_counter[2]_reg_p  (
    .CK(clk),
    .D(_092_),
    .Q(\fifo_counter[2] ),
    .RN(_010_)
  );
  DFFRQX2H7R \fifo_counter[3]_reg_p  (
    .CK(clk),
    .D(_093_),
    .Q(\fifo_counter[3] ),
    .RN(_011_)
  );
  DFFRQX2H7R rd_ptr_0__reg_p (
    .CK(clk),
    .D(_094_),
    .Q(rd_ptr_0_),
    .RN(_012_)
  );
  DFFRQX2H7R rd_ptr_1__reg_p (
    .CK(clk),
    .D(_095_),
    .Q(rd_ptr_1_),
    .RN(_013_)
  );
  DFFRQX2H7R rd_ptr_2__reg_p (
    .CK(clk),
    .D(_096_),
    .Q(rd_ptr_2_),
    .RN(_014_)
  );
  DFFRQX2H7R wr_ptr_0__reg_p (
    .CK(clk),
    .D(_097_),
    .Q(wr_ptr_0_),
    .RN(_015_)
  );
  DFFRQX2H7R wr_ptr_1__reg_p (
    .CK(clk),
    .D(_098_),
    .Q(wr_ptr_1_),
    .RN(_016_)
  );
  DFFRQX2H7R wr_ptr_2__reg_p (
    .CK(clk),
    .D(_099_),
    .Q(wr_ptr_2_),
    .RN(_017_)
  );
endmodule
