/* Generated by Yosys 0.59+110 (git sha1 25ba41f42, clang++ 18.1.8 -fPIC -O3) */

module serdes_top(clk, rst_n, \parallel_data_in[0] , \parallel_data_in[1] , \parallel_data_in[2] , \parallel_data_in[3] , \parallel_data_in[4] , \parallel_data_in[5] , \parallel_data_in[6] , \parallel_data_in[7] , \parallel_data_out[0] , \parallel_data_out[1] , \parallel_data_out[2] , \parallel_data_out[3] , \parallel_data_out[4] , \parallel_data_out[5] , \parallel_data_out[6] , \parallel_data_out[7] );
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input \parallel_data_in[0] ;
  wire \parallel_data_in[0] ;
  input \parallel_data_in[1] ;
  wire \parallel_data_in[1] ;
  input \parallel_data_in[2] ;
  wire \parallel_data_in[2] ;
  input \parallel_data_in[3] ;
  wire \parallel_data_in[3] ;
  input \parallel_data_in[4] ;
  wire \parallel_data_in[4] ;
  input \parallel_data_in[5] ;
  wire \parallel_data_in[5] ;
  input \parallel_data_in[6] ;
  wire \parallel_data_in[6] ;
  input \parallel_data_in[7] ;
  wire \parallel_data_in[7] ;
  output \parallel_data_out[0] ;
  wire \parallel_data_out[0] ;
  output \parallel_data_out[1] ;
  wire \parallel_data_out[1] ;
  output \parallel_data_out[2] ;
  wire \parallel_data_out[2] ;
  output \parallel_data_out[3] ;
  wire \parallel_data_out[3] ;
  output \parallel_data_out[4] ;
  wire \parallel_data_out[4] ;
  output \parallel_data_out[5] ;
  wire \parallel_data_out[5] ;
  output \parallel_data_out[6] ;
  wire \parallel_data_out[6] ;
  output \parallel_data_out[7] ;
  wire \parallel_data_out[7] ;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire data_8b_out;
  wire \decode_data.temp_3b_0_ ;
  AND2X1H7L _4_ (
    .A(rst_n),
    .B(data_8b_out),
    .Y(data_8b_out)
  );
  MUX2X3H7L _5_ (
    .A(data_8b_out),
    .B(\decode_data.temp_3b_0_ ),
    .S0(rst_n),
    .Y(_0_)
  );
  AND2X1H7L _6_ (
    .A(\decode_data.temp_3b_0_ ),
    .B(rst_n),
    .Y(_1_)
  );
  AND2X1H7L _7_ (
    .A(rst_n),
    .B(data_8b_out),
    .Y(_2_)
  );
  TIELOH7R _8_ (
    .Z(_3_)
  );
  DFFQX1H7R data_8b_out_reg_p (
    .CK(clk),
    .D(_0_),
    .Q(data_8b_out)
  );
  DFFQX1H7R \decode_data.temp_3b_0__reg_p  (
    .CK(clk),
    .D(_1_),
    .Q(\decode_data.temp_3b_0_ )
  );
  DFFQX1H7R \parallel_data_out[0]_reg_p  (
    .CK(clk),
    .D(_2_),
    .Q(\parallel_data_out[0] )
  );
  assign \parallel_data_out[5]  = _3_;
  assign \parallel_data_out[4]  = _3_;
  assign \parallel_data_out[3]  = _3_;
  assign \parallel_data_out[2]  = _3_;
  assign \parallel_data_out[1]  = _3_;
  assign \parallel_data_out[6]  = _3_;
  assign \parallel_data_out[7]  = _3_;
endmodule
